import { httpsCallable } from "firebase/functions";
import { cloudFunctions, firebaseReady } from "./firebase";
const pending = new Map(), running = new Map();
const ID = /^[A-Za-z0-9][A-Za-z0-9._:@-]{0,179}$/u, RID = /^attendance_command_[a-f0-9]{48}$/u;
const canonical = (value) => Array.isArray(value) ? value.map(canonical) : value && typeof value === "object" ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])])) : value;
const fingerprint = (value) => JSON.stringify(canonical(value));
function freeze(value) { if (value && typeof value === "object") { Object.values(value).forEach(freeze); Object.freeze(value); } return value; }
function fail(message = "Attendance evidence could not be verified.", code = "invalid-server-response") { throw Object.assign(new Error(message), { code }); }
const id = (value) => typeof value === "string" && ID.test(value) && ![".", ".."].includes(value);
const count = (value) => Number.isInteger(value) && value >= 1 && value <= 400;
const revision = (value) => Number.isInteger(value) && value >= 0 && value <= 100;
const iso = (value) => typeof value === "string" && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;
function exact(value, fields) { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== fields.length || fields.some((field) => !Object.hasOwn(value, field))) fail(); }
function access(input) { if (input.accessMode === "portal") { if (!/^[A-Za-z0-9_-]{20,128}$/u.test(input.portalKey || "")) fail("Open the current customer portal link.", "invalid-argument"); return { accessMode: "portal", portalKey: input.portalKey }; } if (input.accessMode !== "staff" || !id(input.organizationId) || !id(input.quoteId)) fail("Open an exact saved event.", "invalid-argument"); return { accessMode: "staff", organizationId: input.organizationId, quoteId: input.quoteId }; }
const scopeKey = (input) => fingerprint(input.accessMode === "portal" ? ["portal", input.portalKey] : ["staff", input.principalId, input.organizationId, input.quoteId]);
function envelope(value, scope, field, mutation = false) { exact(value, ["ok", "storage", "organizationId", "quoteId", field, ...(mutation ? ["idempotent"] : [])]); if (value.ok !== true || value.storage !== "firebase" || !id(value.organizationId) || !id(value.quoteId) || scope.accessMode === "staff" && (value.organizationId !== scope.organizationId || value.quoteId !== scope.quoteId) || mutation && typeof value.idempotent !== "boolean") fail(); }
function normalizeSnapshot(s, outer, mode) { exact(s, ["schemaVersion", "organizationId", "quoteId", "sourceVersionId", ...(mode === "staff" ? ["acceptanceReceiptId"] : []), "pricedCount", "revision", "availability", "request", "latestResponse", "lastReceiptId", "updatedAtISO", "historyCoverage", "evidenceBoundary"]); if (s.schemaVersion !== 1 || s.organizationId !== outer.organizationId || s.quoteId !== outer.quoteId || !id(s.sourceVersionId) || mode === "staff" && !id(s.acceptanceReceiptId) || !count(s.pricedCount) || !revision(s.revision) || s.historyCoverage !== "latest_request_and_response" || typeof s.evidenceBoundary !== "string" || s.evidenceBoundary.length > 500) fail(); if (!s.revision) { if (s.availability !== "not_yet_available" || s.request !== null || s.latestResponse !== null || s.lastReceiptId !== "" || s.updatedAtISO !== "") fail(); return; } if (s.availability !== "available" || !RID.test(s.lastReceiptId) || !iso(s.updatedAtISO)) fail(); const r = s.request; exact(r, ["requestReceiptId", "sourceVersionId", "pricedCount", "dueDate", "requestedAtISO"]); if (!RID.test(r.requestReceiptId) || r.sourceVersionId !== s.sourceVersionId || r.pricedCount !== s.pricedCount || !/^\d{4}-\d{2}-\d{2}$/u.test(r.dueDate) || !iso(`${r.dueDate}T00:00:00.000Z`) || !iso(r.requestedAtISO) || r.requestedAtISO > s.updatedAtISO) fail(); if (s.latestResponse !== null) { const response = s.latestResponse; exact(response, ["submissionReceiptId", "requestReceiptId", "count", "sourceType", "submittedByRole", "submittedAtISO", "supersedesReceiptId"]); if (!RID.test(response.submissionReceiptId) || response.submissionReceiptId !== s.lastReceiptId || response.requestReceiptId !== r.requestReceiptId || !count(response.count) || !["staff_recorded", "customer_portal"].includes(response.sourceType) || response.sourceType === "customer_portal" && response.submittedByRole !== "customer" || response.sourceType === "staff_recorded" && !["admin", "sales"].includes(response.submittedByRole) || mode === "portal" && response.sourceType !== "customer_portal" || !iso(response.submittedAtISO) || response.submittedAtISO < r.requestedAtISO || response.submittedAtISO > s.updatedAtISO || response.supersedesReceiptId !== "" && !RID.test(response.supersedesReceiptId)) fail(); } }
async function call(name, input) { if (!firebaseReady || !cloudFunctions) fail("Attendance requires a connected workspace.", "failed-precondition"); return (await httpsCallable(cloudFunctions, name)(input)).data; }
function safeError(error) { const code = String(error?.code || "unknown").replace(/^functions\//u, ""); return Object.assign(new Error({ aborted: "The request or accepted event changed. Refresh and review before continuing.", "permission-denied": "This account or portal cannot access the current attendance request.", "failed-precondition": "Attendance is unavailable for this source or connection.", "invalid-argument": "Review the count and required source fields.", "resource-exhausted": "This attendance source has reached its receipt limit.", "already-exists": "This request identity belongs to a different attendance response." }[code] || "The attendance result could not be verified. Keep the original request unchanged."), { code }); }
export async function getQuoteAttendance(input) { const scope = access(input); try { const value = await call("getQuoteAttendance", scope); envelope(value, scope, "snapshot"); normalizeSnapshot(value.snapshot, value, scope.accessMode); return freeze(value); } catch (error) { throw safeError(error); } }
export const createAttendanceRequestId = () => `attendance_${crypto.randomUUID()}`;
export const readPendingAttendanceCommand = (scope) => pending.has(scopeKey(scope)) ? structuredClone(pending.get(scopeKey(scope))) : null;
export function resetDefinitiveAttendanceCommand(scope) { const key = scopeKey(scope); if (!pending.get(key)?.definitive || running.has(key)) return false; pending.delete(key); return true; }
export const isDefinitiveAttendanceError = (error) => error?.uncertain !== true && ["unauthenticated", "permission-denied", "invalid-argument", "failed-precondition", "not-found", "already-exists", "aborted", "resource-exhausted"].includes(error?.code);
function normalizeCommand(input, portal) { const fields = portal ? ["portalKey", "confirmationRequestId", "expectedSourceVersionId", "expectedPortalIssuedAtISO", "expectedAttendanceRevision", "requestId", "count"] : ["organizationId", "quoteId", "sourceVersionId", "acceptanceReceiptId", "requestId", "expectedAttendanceRevision", "command", "principalId", ...(input.command === "record_response" ? ["confirmationRequestId", "count", "note"] : [])]; try { exact(input, fields); } catch { fail("Unsupported attendance command fields.", "invalid-argument"); } if (!/^[A-Za-z0-9][A-Za-z0-9._:@-]{19,159}$/u.test(input.requestId) || !revision(input.expectedAttendanceRevision)) fail("An exact request identity and revision are required.", "invalid-argument"); if (portal) { access({ ...input, accessMode: "portal" }); if (!id(input.expectedSourceVersionId) || !iso(input.expectedPortalIssuedAtISO)) fail("The current portal issuance is required.", "invalid-argument"); } else { if (!["request_confirmation", "record_response"].includes(input.command) || !id(input.principalId) || !id(input.sourceVersionId) || !id(input.acceptanceReceiptId)) fail("Exact signed-in source is required.", "invalid-argument"); access({ ...input, accessMode: "staff" }); } const command = { ...input }; delete command.principalId; if (portal || input.command === "record_response") { if (!count(input.count) || !RID.test(input.confirmationRequestId)) fail("Enter a whole guest count from 1 to 400 for the current request.", "invalid-argument"); } if (!portal && input.command === "record_response") { if (typeof input.note !== "string" || !input.note.trim() || input.note.trim().length > 240 || /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(input.note)) fail("Describe the staff-recorded source in 1 to 240 characters.", "invalid-argument"); command.note = input.note.trim(); } return command; }
function mutate(input, portal) { let command; try { command = normalizeCommand(input, portal); } catch (error) { return Promise.reject(error); } const scope = { ...input, accessMode: portal ? "portal" : "staff" }, key = scopeKey(scope), payload = fingerprint(command), active = running.get(key), prior = pending.get(key); if (active) return active.payload === payload ? active.promise : Promise.reject(Object.assign(new Error("The original attendance request is still running."), { code: "attendance-pending" })); if (prior && fingerprint(prior.command) !== payload) return Promise.reject(Object.assign(new Error("Check the unchanged original attendance request first."), { code: "attendance-pending" })); if (!prior && pending.size >= 25) return Promise.reject(Object.assign(new Error("Review an unresolved attendance request first."), { code: "resource-exhausted" })); pending.set(key, { command, definitive: false, uncertainEver: prior?.uncertainEver || false }); const promise = (async () => { try { const value = await call(portal ? "submitQuoteAttendanceResponse" : "applyQuoteAttendanceCommand", command); envelope(value, scope, "receipt", true); const r = value.receipt, kind = portal ? "submit_response" : command.command; exact(r, ["receiptId", "requestId", "command", "priorRevision", "resultRevision", "recordedAtISO", "confirmationRequestId", "submissionReceiptId", "count", "sourceType"]); if (!RID.test(r.receiptId) || r.requestId !== command.requestId || r.command !== kind || r.priorRevision !== command.expectedAttendanceRevision || r.resultRevision !== r.priorRevision + 1 || r.resultRevision > 100 || !iso(r.recordedAtISO) || (kind === "request_confirmation" ? r.confirmationRequestId !== r.receiptId || r.submissionReceiptId !== "" || r.count !== null || r.sourceType !== "" : r.confirmationRequestId !== command.confirmationRequestId || r.submissionReceiptId !== r.receiptId || r.count !== command.count || r.sourceType !== (portal ? "customer_portal" : "staff_recorded"))) fail(); pending.delete(key); return freeze(value); } catch (error) { const safe = safeError(error), unknown = prior?.uncertainEver || !isDefinitiveAttendanceError(safe); pending.set(key, { command, definitive: !unknown, uncertainEver: unknown }); if (unknown) safe.uncertain = true; throw safe; } })(); running.set(key, { payload, promise }); promise.then(() => { if (running.get(key)?.promise === promise) running.delete(key); }, () => { if (running.get(key)?.promise === promise) running.delete(key); }); return promise; }
export const applyQuoteAttendanceCommand = (input) => mutate(input, false);
export const submitQuoteAttendanceResponse = (input) => mutate(input, true);
