import { httpsCallable } from "firebase/functions";
import { cloudFunctions, firebaseReady } from "./firebase";
import { beginEventOperatingMutation, failEventOperatingMutation, releaseEventOperatingMutation } from "./eventOperatingMutationGuard";
export const WORKFLOW_KINDS = ["event_execution", "quote_review", "final_guest_count", "closeout_follow_up"];
export const CHECKPOINT_CODES = ["venue_access", "team_briefing", "service_handoff", "pack_down"];
const KIND = "event_execution", HANDOFFS = ["internal_event_brief_v1", "post_event_review_v1"];
const SEED_CONFIG = { schemaVersion: 1, workflowKind: KIND, name: "QuotePilot event coordination", allowedRoles: ["admin", "sales"], actualsReviewThresholdCents: null, comparisonPolicy: null, duePolicy: { offsetMinutes: 0 }, escalationPolicy: { afterMinutes: 60, role: "admin" }, taskTemplates: [{ taskKey: "review_event_context", label: "Review event context", instruction: "Review the accepted event context before recording operational work.", ownerRole: "admin", dueOffsetMinutes: 0, communicationTemplateRef: null }] };
const attempts = new Map(), active = new Map();
const id = (value) => typeof value === "string" && /^[^\s/?#\\\u0000]{1,180}$/u.test(value) && ![".", ".."].includes(value);
const int = (value, max = Number.MAX_SAFE_INTEGER - 1) => Number.isSafeInteger(value) && value >= 0 && value <= max;
const digest = (value) => typeof value === "string" && /^[a-f0-9]{64}$/u.test(value);
const iso = (value) => typeof value === "string" && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;
const canonical = (value) => Array.isArray(value) ? value.map(canonical) : value && typeof value === "object" ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])])) : value;
const fingerprint = (value) => JSON.stringify(canonical(value));
const freeze = (value) => { if (value && typeof value === "object") { Object.values(value).forEach(freeze); Object.freeze(value); } return value; };
function fail(message = "Workflow evidence could not be verified.", code = "invalid-server-response") { throw Object.assign(new Error(message), { code }); }
function exact(value, fields) { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== fields.length || fields.some((field) => !Object.hasOwn(value, field))) fail(); }
function plain(value, limit = 240, blank = false) { if (typeof value !== "string" || value.length > limit || (!blank && !value.trim()) || /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(value) || /(?:[a-z][a-z0-9+.-]*:\/\/|javascript:|data:|<\/?[a-z]|=>|\$\{|[\w.+-]+@[\w.-]+\.[a-z]{2,})/iu.test(value)) fail("Use bounded plain operator text without links, code, or recipients.", "invalid-argument"); return value.trim(); }
function note(value) { if (typeof value !== "string" || /[\u0000-\u001f\u007f]/u.test(value) || !value.trim() || value.trim().length > 240) fail("Enter a single-line reason of 1 to 240 characters.", "invalid-argument"); return value.trim(); }
export function workflowMoneyInputToCents(value) { if (typeof value !== "string" || !/^\d{1,8}(?:\.\d{1,2})?$/u.test(value.trim())) return null; const [whole, fraction = ""] = value.trim().split("."); const cents = Number(whole) * 100 + Number(fraction.padEnd(2, "0")); return int(cents, 1_000_000_000) ? cents : null; }
export function normalizeWorkflowConfig(value) {
  if (value?.schemaVersion === 2) {
    exact(value, ["schemaVersion", "workflowKind", "name", "allowedRoles", "actualsReviewThresholdCents", "comparisonPolicy", "duePolicy", "escalationPolicy", "taskTemplates", "packPolicy"]);
    if (!WORKFLOW_KINDS.includes(value.workflowKind)) fail();
    const { packPolicy, ...common } = value;
    const validated = normalizeWorkflowConfig({ ...common, schemaVersion: 1, workflowKind: KIND });
    if (value.workflowKind !== KIND && (value.actualsReviewThresholdCents !== null || value.comparisonPolicy !== null)) fail();
    const roles = roles => { if (!Array.isArray(roles) || !roles.includes("admin") || roles.length > 2 || new Set(roles).size !== roles.length || roles.some(role => !validated.allowedRoles.includes(role))) fail(); return [...roles].sort(); };
    const codes = codes => { if (!Array.isArray(codes) || codes.length > 4 || new Set(codes).size !== codes.length || codes.some(code => !CHECKPOINT_CODES.includes(code))) fail(); return CHECKPOINT_CODES.filter(code => codes.includes(code)); };
    let policy;
    if (value.workflowKind === "quote_review") { exact(packPolicy, ["approval"]); exact(packPolicy.approval, ["basis", "thresholdCents", "allowedRoles"]); if (packPolicy.approval.basis !== "absolute_total_delta_cents" || packPolicy.approval.thresholdCents !== null && !int(packPolicy.approval.thresholdCents, 1e9)) fail(); policy = { approval: { ...packPolicy.approval, allowedRoles: roles(packPolicy.approval.allowedRoles) } }; }
    else if (value.workflowKind === KIND) {
      exact(packPolicy, ["phaseConstraints", "checkpointPrerequisites"]); exact(packPolicy.phaseConstraints, ["in_progress", "completed"]); exact(packPolicy.checkpointPrerequisites, CHECKPOINT_CODES);
      const phaseConstraints = Object.fromEntries(["in_progress", "completed"].map(phase => { const rule = packPolicy.phaseConstraints[phase]; exact(rule, ["requiredCheckpoints", "blockOpenUrgentIssues"]); if (typeof rule.blockOpenUrgentIssues !== "boolean") fail(); return [phase, { requiredCheckpoints: codes(rule.requiredCheckpoints), blockOpenUrgentIssues: rule.blockOpenUrgentIssues }]; }));
      const checkpointPrerequisites = Object.fromEntries(CHECKPOINT_CODES.map(code => [code, codes(packPolicy.checkpointPrerequisites[code])]));
      const visit = (code, seen) => { if (seen.has(code)) fail("Checkpoint prerequisites cannot form a cycle.", "invalid-argument"); checkpointPrerequisites[code].forEach(dependency => visit(dependency, new Set([...seen, code]))); }; CHECKPOINT_CODES.forEach(code => visit(code, new Set()));
      policy = { phaseConstraints, checkpointPrerequisites };
    } else { exact(packPolicy, value.workflowKind === "closeout_follow_up" ? ["responsibleRoles", "followUpOffsetDays"] : ["responsibleRoles"]); if (value.workflowKind === "closeout_follow_up" && !int(packPolicy.followUpOffsetDays, 90)) fail(); policy = { ...packPolicy, responsibleRoles: roles(packPolicy.responsibleRoles) }; }
    return freeze({ ...validated, schemaVersion: 2, workflowKind: value.workflowKind, packPolicy: policy });
  }
  exact(value, ["schemaVersion", "workflowKind", "name", "allowedRoles", "actualsReviewThresholdCents", "comparisonPolicy", "duePolicy", "escalationPolicy", "taskTemplates"]);
  if (value.schemaVersion !== 1 || value.workflowKind !== KIND || !Array.isArray(value.allowedRoles) || !value.allowedRoles.includes("admin") || value.allowedRoles.length > 2 || new Set(value.allowedRoles).size !== value.allowedRoles.length || value.allowedRoles.some((role) => !["admin", "sales"].includes(role)) || (value.actualsReviewThresholdCents !== null && !int(value.actualsReviewThresholdCents, 1_000_000_000))) fail();
  exact(value.duePolicy, ["offsetMinutes"]); exact(value.escalationPolicy, ["afterMinutes", "role"]);
  if (!int(value.duePolicy.offsetMinutes, 43_200) || !int(value.escalationPolicy.afterMinutes, 43_200) || value.escalationPolicy.role !== "admin") fail();
  if (value.comparisonPolicy !== null) { exact(value.comparisonPolicy, ["laborBasisPoints", "purchasingBasisPoints", "minimumCents"]); if (!int(value.comparisonPolicy.laborBasisPoints, 10_000) || !int(value.comparisonPolicy.purchasingBasisPoints, 10_000) || !int(value.comparisonPolicy.minimumCents, 1_000_000_000)) fail(); }
  if (!Array.isArray(value.taskTemplates) || value.taskTemplates.length > 12) fail();
  const keys = new Set(); const taskTemplates = value.taskTemplates.map((task) => { exact(task, ["taskKey", "label", "instruction", "ownerRole", "dueOffsetMinutes", "communicationTemplateRef"]); if (!/^[a-z][a-z0-9_]{0,47}$/u.test(task.taskKey) || keys.has(task.taskKey) || !value.allowedRoles.includes(task.ownerRole) || !int(task.dueOffsetMinutes, 43_200) || (task.communicationTemplateRef !== null && !HANDOFFS.includes(task.communicationTemplateRef))) fail(); keys.add(task.taskKey); return { ...task, label: plain(task.label, 80), instruction: plain(task.instruction, 240, true) }; });
  return freeze({ ...structuredClone(value), name: plain(value.name, 80), allowedRoles: [...value.allowedRoles].sort(), taskTemplates });
}
function pin(value, kind = KIND) { exact(value, ["workflowKind", "schemaVersion", "definitionId", "versionId", "version", "definitionDigest"]); if (value.workflowKind !== kind || ![1, 2].includes(value.schemaVersion) || value.schemaVersion === 1 && kind !== KIND || value.schemaVersion === 2 && value.version < 1 || value.definitionId !== kind || !int(value.version, 50) || value.versionId !== `${kind}_v${value.version}` || !digest(value.definitionDigest)) fail(); }
function version(value, org, kind = KIND) { exact(value, ["schemaVersion", "organizationId", "definitionId", "workflowKind", "versionId", "version", "config", "publishedBy", "publishedAtISO", "seed", "definitionDigest"]); pin(Object.fromEntries(["workflowKind", "schemaVersion", "definitionId", "versionId", "version", "definitionDigest"].map((key) => [key, value[key]])), kind); normalizeWorkflowConfig(value.config); if (value.config.workflowKind !== kind || value.config.schemaVersion !== value.schemaVersion) fail(); exact(value.publishedBy, ["organizationId", "uid", "role"]); if (!iso(value.publishedAtISO) || (value.seed === true ? value.version !== 0 || value.organizationId !== null || value.publishedBy.organizationId !== null || value.publishedBy.uid !== "quotepilot_source_seed" || value.publishedBy.role !== "system" || fingerprint(value.config) !== fingerprint(SEED_CONFIG) || value.publishedAtISO !== "2026-09-05T00:00:00.000Z" : value.seed !== false || value.version < 1 || value.organizationId !== org || value.publishedBy.organizationId !== org || !id(value.publishedBy.uid) || value.publishedBy.role !== "admin")) fail(); }
function definitionSnapshot(s, scope) {
  if (s?.availability === "schema_drift") { exact(s, ["organizationId", "workflowKind", "availability", "reasonCode", "revision", "draft", "activeVersion"]); if (s.reasonCode !== "definition_schema_unsupported" || s.revision !== null || s.draft !== null || s.activeVersion !== null) fail(); }
  else { exact(s, ["organizationId", "workflowKind", "availability", "revision", "draftRevision", "draft", "lifetimeVersionCount", "activeVersion", "state", "newInstanceEligible", "lastReceiptId", "updatedAtISO"]); if (s.availability !== "available" || !int(s.revision) || !int(s.draftRevision) || s.draftRevision > s.revision || !int(s.lifetimeVersionCount, 50) || !["seed", "published", "retired", "unpublished"].includes(s.state) || s.newInstanceEligible !== Boolean(s.activeVersion) || (s.revision === 0 ? s.lastReceiptId !== "" || s.updatedAtISO !== "" : !/^workflow_definition_command_[a-f0-9]{48}$/u.test(s.lastReceiptId) || !iso(s.updatedAtISO))) fail(); if (s.draft !== null) { normalizeWorkflowConfig(s.draft); if (s.draft.workflowKind !== scope.workflowKind) fail(); } if (s.activeVersion !== null) version(s.activeVersion, scope.organizationId, scope.workflowKind); if (s.state === "unpublished" ? scope.workflowKind === KIND || s.lifetimeVersionCount !== 0 || s.activeVersion !== null : s.state === "seed" ? s.lifetimeVersionCount !== 0 || !s.activeVersion?.seed : s.state === "published" ? !s.activeVersion || s.activeVersion.seed || s.activeVersion.version !== s.lifetimeVersionCount : s.activeVersion !== null || s.lifetimeVersionCount < 1) fail(); }
  if (s.organizationId !== scope.organizationId || s.workflowKind !== scope.workflowKind) fail(); return s;
}
function source(value, scope) { exact(value, ["organizationId", "workflowKind", "subjectId", "sourceVersionId", "sourceReceiptId"]); if (value.organizationId !== scope.organizationId || value.subjectId !== scope.quoteId || value.workflowKind !== KIND || !id(value.sourceVersionId) || !id(value.sourceReceiptId)) fail(); }
function domain(value) { exact(value, ["kind", "revision", "receiptId", "policyDigest", "receiptDigest"]); if (value.kind !== "event_phase" || !int(value.revision) || value.revision < 1 || !/^event_ops_command_[a-f0-9]{48}$/u.test(value.receiptId) || !digest(value.policyDigest) || !digest(value.receiptDigest)) fail(); }
function eventSnapshot(s, scope) {
  const base = ["source", "instanceId", "observedAtISO", "historyCoverage", "availability", "reasonCode", "revision", "tasks", "actualsReview", "organizationId", "quoteId", "sourceVersionId", "acceptanceReceiptId", "ledgerId", "phaseRevision", "phaseReceiptId"];
  source(s.source, scope); if (s.organizationId !== scope.organizationId || s.quoteId !== scope.quoteId || s.sourceVersionId !== s.source.sourceVersionId || s.acceptanceReceiptId !== s.source.sourceReceiptId || !/^workflow_instance_[a-f0-9]{48}$/u.test(s.instanceId) || !/^event_ops_[a-f0-9]{48}$/u.test(s.ledgerId) || !iso(s.observedAtISO) || s.historyCoverage !== "latest_receipt_only" || !int(s.phaseRevision) || (s.phaseRevision ? !/^event_ops_command_[a-f0-9]{48}$/u.test(s.phaseReceiptId) : s.phaseReceiptId !== "")) fail();
  if (s.availability === "not_yet_available") { exact(s, [...base, "nextDefinition", "initializationEligibility"]); exact(s.actualsReview, ["state"]); exact(s.initializationEligibility, ["eligible", "reasonCode"]); if (!["phase_ledger_missing", "legacy_unbound"].includes(s.reasonCode) || s.revision !== 0 || !Array.isArray(s.tasks) || s.tasks.length || s.actualsReview.state !== "not_yet_available" || !["seed", "published", "retired", "definition_schema_unsupported", "legacy_unbound"].includes(s.initializationEligibility.reasonCode) || s.initializationEligibility.eligible !== Boolean(s.nextDefinition)) fail(); if (s.nextDefinition) version(s.nextDefinition, scope.organizationId); const eligibility = s.initializationEligibility; if (s.reasonCode === "phase_ledger_missing" ? s.phaseRevision !== 0 || s.phaseReceiptId !== "" || eligibility.reasonCode === "legacy_unbound" : s.phaseRevision < 1 || eligibility.eligible || eligibility.reasonCode !== "legacy_unbound" || s.nextDefinition !== null) fail(); if (eligibility.eligible ? !["seed", "published"].includes(eligibility.reasonCode) || (eligibility.reasonCode === "seed") !== s.nextDefinition.seed : !["retired", "definition_schema_unsupported", "legacy_unbound"].includes(eligibility.reasonCode) || s.nextDefinition !== null) fail(); return s; }
  exact(s, [...base, "definitionPin", "definitionName", "domainRef", "configuration", "definitionSource", "publishedBy", "publishedAtISO", "dueAtISO", "escalationAtISO", "comparisonPolicy", "lastReceiptId", "updatedAtISO"]);
  if (s.availability !== "available" || s.reasonCode !== "" || !int(s.revision) || s.revision < 1 || !/^workflow_command_[a-f0-9]{48}$/u.test(s.lastReceiptId) || !iso(s.updatedAtISO) || s.updatedAtISO > s.observedAtISO || !iso(s.dueAtISO) || !iso(s.escalationAtISO) || s.escalationAtISO < s.dueAtISO || !iso(s.publishedAtISO)) fail(); pin(s.definitionPin); domain(s.domainRef); normalizeWorkflowConfig(s.configuration); exact(s.publishedBy, ["uid", "role"]);
  if (s.definitionName !== s.configuration.name || !id(s.publishedBy.uid) || (s.definitionPin.version === 0 ? s.definitionSource !== "source_controlled_seed" || s.publishedBy.role !== "system" || s.publishedBy.uid !== "quotepilot_source_seed" || fingerprint(s.configuration) !== fingerprint(SEED_CONFIG) : s.definitionSource !== "tenant_published" || s.publishedBy.role !== "admin") || s.domainRef.revision !== s.phaseRevision || s.domainRef.receiptId !== s.phaseReceiptId) fail();
  if (!Array.isArray(s.tasks) || s.tasks.length !== s.configuration.taskTemplates.length) fail();
  s.tasks.forEach((task, index) => { exact(task, ["taskKey", "label", "instruction", "ownerRole", "dueOffsetMinutes", "communicationTemplateRef", "state", "note", "updatedAtISO", "lastReceiptId", "dueAtISO", "escalationAtISO", "communicationHandoff", "urgency", "escalationRole"]); const template = s.configuration.taskTemplates[index]; if (Object.keys(template).some((field) => template[field] !== task[field]) || !["pending", "acknowledged"].includes(task.state) || !iso(task.dueAtISO) || !iso(task.escalationAtISO) || task.escalationAtISO < task.dueAtISO || task.escalationRole !== "admin" || !["acknowledged", "upcoming", "due", "escalated"].includes(task.urgency)) fail(); if (task.urgency !== (task.state === "acknowledged" ? "acknowledged" : s.observedAtISO >= task.escalationAtISO ? "escalated" : s.observedAtISO >= task.dueAtISO ? "due" : "upcoming")) fail(); if (task.updatedAtISO === "" ? task.state !== "pending" || task.note !== "" || task.lastReceiptId !== "" : !iso(task.updatedAtISO) || task.updatedAtISO > s.updatedAtISO || !/^workflow_command_[a-f0-9]{48}$/u.test(task.lastReceiptId) || note(task.note) !== task.note) fail(); if (task.communicationTemplateRef === null ? task.communicationHandoff !== null : !task.communicationHandoff) fail(); if (task.communicationHandoff) { exact(task.communicationHandoff, ["reference", "label", "guidance"]); if (task.communicationHandoff.reference !== task.communicationTemplateRef) fail(); plain(task.communicationHandoff.label, 80); plain(task.communicationHandoff.guidance, 500); } });
  exact(s.actualsReview, ["state", "actualsRef", "thresholdCents"]); const review = s.actualsReview, ref = review.actualsRef; if (review.thresholdCents !== s.configuration.actualsReviewThresholdCents) fail(); if (ref !== null) { exact(ref, ["revision", "receiptId", "receiptDigest", "totalCostCents"]); if (!int(ref.revision) || ref.revision < 1 || !/^event_actuals_command_[a-f0-9]{48}$/u.test(ref.receiptId) || !digest(ref.receiptDigest) || !int(ref.totalCostCents, 50e9)) fail(); }
  const allowedReview = review.thresholdCents === null ? ["not_applicable"] : ref === null ? ["not_yet_available"] : ref.totalCostCents < review.thresholdCents ? ["not_required"] : ["required", "acknowledged"]; if (!allowedReview.includes(review.state)) fail();
  if (s.configuration.comparisonPolicy === null ? s.comparisonPolicy !== null : !s.comparisonPolicy) fail(); if (s.comparisonPolicy) { exact(s.comparisonPolicy, ["laborBasisPoints", "purchasingBasisPoints", "minimumCents", "declaredBy", "declaredAtISO"]); if (Object.keys(s.configuration.comparisonPolicy).some((field) => s.configuration.comparisonPolicy[field] !== s.comparisonPolicy[field]) || s.comparisonPolicy.declaredBy !== s.publishedBy.uid || s.comparisonPolicy.declaredAtISO !== s.publishedAtISO) fail(); } return s;
}
function requested(input, type, exactSource = false) { if (!id(input.organizationId) || (type === "definition" ? !WORKFLOW_KINDS.includes(input.workflowKind) : !id(input.quoteId)) || (exactSource && (!id(input.sourceVersionId) || !id(input.acceptanceReceiptId)))) fail("Exact workflow scope is required.", "invalid-argument"); return type === "definition" ? { organizationId: input.organizationId, workflowKind: input.workflowKind } : { organizationId: input.organizationId, quoteId: input.quoteId, ...(exactSource ? { sourceVersionId: input.sourceVersionId, acceptanceReceiptId: input.acceptanceReceiptId } : {}) }; }
function errorFor(error) { const code = String(error?.code || "unknown").replace(/^functions\//u, ""); return Object.assign(new Error({ aborted: "The workflow changed. Refresh and review the exact source.", "permission-denied": "Your current role cannot perform this workflow action.", "failed-precondition": "The current workflow definition or event binding does not allow this action.", "invalid-argument": "Review the bounded workflow fields and confirmation.", "resource-exhausted": "The workflow publication or pending-request limit was reached." }[code] || "The workflow result could not be verified. Keep the original request for reconciliation."), { code }); }
async function call(name, request) { if (!firebaseReady || !cloudFunctions) fail("Workflow operations require a connected workspace.", "unavailable"); return (await httpsCallable(cloudFunctions, name)(request)).data; }
function envelope(value, scope, field, mutation = false) { exact(value, ["ok", "storage", ...Object.keys(scope).filter((key) => !["sourceVersionId", "acceptanceReceiptId"].includes(key)), ...(mutation ? ["idempotent"] : []), field]); if (value.ok !== true || value.storage !== "firebase" || Object.keys(scope).filter((key) => !["sourceVersionId", "acceptanceReceiptId"].includes(key)).some((key) => value[key] !== scope[key]) || (mutation && typeof value.idempotent !== "boolean")) fail(); }
export async function getWorkflowConfiguration(input) { const scope = requested(input, "definition"); try { const value = await call("getWorkflowConfiguration", scope); envelope(value, scope, "snapshot"); definitionSnapshot(value.snapshot, scope); return freeze(value); } catch (error) { throw errorFor(error); } }
export async function getEventWorkflowSnapshot(input) { const scope = requested(input, "event"); try { const value = await call("getEventWorkflowSnapshot", scope); envelope(value, scope, "snapshot"); if (value.snapshot?.schemaVersion === 2) {
      const { normalizeWorkflowPackSnapshot } = await import("./workflowPackClient");
      const { organizationId, quoteId, sourceVersionId, acceptanceReceiptId, ledgerId, phaseRevision, phaseReceiptId, ...common } = value.snapshot;
      if (organizationId !== scope.organizationId || quoteId !== scope.quoteId || sourceVersionId !== common.source?.sourceVersionId || acceptanceReceiptId !== common.source?.sourceReceiptId || !/^event_ops_[a-f0-9]{48}$/u.test(ledgerId) || !int(phaseRevision) || phaseRevision < 1 || !/^event_ops_command_[a-f0-9]{48}$/u.test(phaseReceiptId) || common.domainRef?.evidenceId !== phaseReceiptId || !["prepared", "in_progress", "completed"].includes(common.domainRef?.stateCode)) fail();
      normalizeWorkflowPackSnapshot(common, { ...scope, workflowKind: KIND });
    } else eventSnapshot(value.snapshot, scope); return freeze(value); } catch (error) { throw errorFor(error); } }
export async function previewWorkflowDefinition(input) { const scope = requested(input, "definition"); if (!int(input.expectedRevision) || !id(input.principalId)) fail("A current principal and draft revision are required.", "invalid-argument"); try { const value = await call("previewWorkflowDefinition", { ...scope, expectedRevision: input.expectedRevision }); envelope(value, scope, "preview"); const p = value.preview; exact(p, ["schemaVersion", "organizationId", "workflowKind", "definitionId", "headRevision", "draftRevision", "draftDigest", "headDigest", "candidateVersion", "candidateVersionId", "actor", "previewDigest", "confirmationText", "config"]); exact(p.actor, ["organizationId", "uid", "role"]); if (p.schemaVersion !== 1 || p.organizationId !== scope.organizationId || p.workflowKind !== scope.workflowKind || p.definitionId !== scope.workflowKind || p.headRevision !== input.expectedRevision || !int(p.draftRevision) || !digest(p.draftDigest) || !digest(p.headDigest) || !digest(p.previewDigest) || !int(p.candidateVersion, 50) || p.candidateVersion < 1 || p.candidateVersionId !== `${scope.workflowKind}_v${p.candidateVersion}` || p.confirmationText !== `PUBLISH ${p.candidateVersionId} ${p.previewDigest.slice(0, 12)}` || p.actor.organizationId !== scope.organizationId || p.actor.role !== "admin" || p.actor.uid !== input.principalId) fail(); normalizeWorkflowConfig(p.config); if (p.config.workflowKind !== scope.workflowKind) fail(); return freeze(value); } catch (error) { throw errorFor(error); } }
export async function previewEventWorkflowMigration(input) { if (input.schemaVersion === 2) { const { previewWorkflowPackMigration } = await import("./workflowPackClient"); const { schemaVersion, acceptanceReceiptId, ...base } = input; const result = await previewWorkflowPackMigration({ ...base, workflowKind: KIND, sourceReceiptId: acceptanceReceiptId }); const { workflowKind, ...compatibleEnvelope } = result; return compatibleEnvelope; } const scope = requested(input, "event", true); if (!int(input.expectedRevision)) fail(); try { const value = await call("previewEventWorkflowMigration", { ...scope, expectedRevision: input.expectedRevision }); envelope(value, scope, "preview"); const p = value.preview; exact(p, ["instanceId", "source", "expectedRevision", "currentDefinitionPin", "targetDefinitionPin", "targetConfiguration", "domainRef", "compatible", "reasons", "confirmation", "previewDigest"]); source(p.source, scope); pin(p.currentDefinitionPin); pin(p.targetDefinitionPin); normalizeWorkflowConfig(p.targetConfiguration); domain(p.domainRef); if (!/^workflow_instance_[a-f0-9]{48}$/u.test(p.instanceId) || p.source.sourceVersionId !== scope.sourceVersionId || p.source.sourceReceiptId !== scope.acceptanceReceiptId || p.expectedRevision !== input.expectedRevision || !digest(p.previewDigest) || typeof p.compatible !== "boolean" || !Array.isArray(p.reasons) || p.reasons.length > 20 || p.reasons.some((reason) => typeof reason !== "string" || reason.length > 240) || p.confirmation !== `MIGRATE ${p.targetDefinitionPin.versionId}`) fail(); return freeze(value); } catch (error) { throw errorFor(error); } }
const keyFor = (scope, type) => fingerprint([type, scope.principalId, scope.organizationId, type === "event" ? scope.quoteId : "organization_definition"]);
export function createWorkflowRequestId() { return `workflow_${crypto.randomUUID()}`; }
export function readPendingWorkflowCommand(scope, type = "event") { const attempt = attempts.get(keyFor(scope, type)); return attempt ? structuredClone(attempt) : null; }
export function resetDefinitiveWorkflowCommand(scope, type = "event") { const key = keyFor(scope, type), attempt = attempts.get(key); if (!attempt?.definitive || active.has(key) || (type === "event" && !releaseEventOperatingMutation(scope, "workflow", attempt.command.requestId, { reviewedReset: true }))) return false; attempts.delete(key); return true; }
export function isDefinitiveWorkflowError(error) { return error?.uncertain !== true && new Set(["unauthenticated", "permission-denied", "invalid-argument", "failed-precondition", "not-found", "already-exists", "aborted", "resource-exhausted"]).has(error?.code); }
function commandInput(input, type) {
  const scope = requested(input, type, type === "event"); if (!id(input.principalId) || !/^[A-Za-z0-9][A-Za-z0-9._:@-]{19,159}$/u.test(input.requestId) || !int(input.expectedRevision)) fail("An exact principal, revision and request identity are required.", "invalid-argument");
  const fields = type === "definition" ? { save_draft: ["config"], publish: ["previewDigest", "confirmationText"], retire: ["versionId", "reason"] } : { task_ack: ["taskKey", "note"], task_reopen: ["taskKey", "note"], review_ack: ["actualsRevision", "actualsReceiptId", "note"], migrate: ["previewDigest", "confirmation", "note"] };
  if (!fields[input.command]) fail("Unsupported workflow command.", "invalid-argument");
  try { exact(input, [...Object.keys(scope), "principalId", "requestId", "expectedRevision", "command", ...fields[input.command]]); } catch { fail("Unsupported workflow command fields.", "invalid-argument"); }
  const command = { ...scope, requestId: input.requestId, expectedRevision: input.expectedRevision, command: input.command };
  for (const field of fields[input.command]) command[field] = field === "config" ? normalizeWorkflowConfig(input.config) : field === "reason" ? plain(input.reason) : field === "note" ? note(input.note) : input[field];
  if (command.config && command.config.workflowKind !== scope.workflowKind) fail("Draft belongs to another workflow pack.", "invalid-argument");
  if (command.previewDigest && !digest(command.previewDigest) || input.command === "retire" && !id(command.versionId) || ["task_ack", "task_reopen"].includes(input.command) && !/^[a-z][a-z0-9_]{0,47}$/u.test(command.taskKey) || input.command === "review_ack" && (!int(command.actualsRevision) || command.actualsRevision < 1 || !/^event_actuals_command_[a-f0-9]{48}$/u.test(command.actualsReceiptId)) || input.command === "publish" && typeof command.confirmationText !== "string" || input.command === "migrate" && typeof command.confirmation !== "string") fail("Review the exact workflow request fields.", "invalid-argument"); return command;
}
function mutate(input, type) {
  let command; try { command = commandInput(input, type); } catch (error) { return Promise.reject(error); } const key = keyFor(input, type), payload = fingerprint(command), running = active.get(key); if (running) return running.payload === payload ? running.promise : Promise.reject(Object.assign(new Error("The original workflow request is still running."), { code: "event-mutation-blocked" }));
  const prior = attempts.get(key); if (prior && fingerprint(prior.command) !== payload) return Promise.reject(Object.assign(new Error("Check the unchanged original workflow request first."), { code: "event-mutation-blocked" }));
  if (!prior && attempts.size >= 25) return Promise.reject(Object.assign(new Error("Review an unresolved workflow request first."), { code: "resource-exhausted" }));
  try { if (type === "event") beginEventOperatingMutation(input, "workflow", command); } catch (error) { return Promise.reject(error); }
  attempts.set(key, { command, definitive: prior?.definitive || false, uncertainEver: prior?.uncertainEver || false });
  const promise = (async () => { try {
    const value = await call(type === "definition" ? "applyWorkflowDefinitionCommand" : "applyEventWorkflowCommand", command); const scope = requested(input, type, type === "event"); envelope(value, scope, "receipt", true); const r = value.receipt; exact(r, ["receiptId", "requestId", "command", "priorRevision", "resultRevision", "recordedAtISO", type === "definition" ? "versionId" : "definitionPin"]); if (!new RegExp(`^${type === "definition" ? "workflow_definition_command_" : "workflow_command_"}[a-f0-9]{48}$`, "u").test(r.receiptId) || r.requestId !== command.requestId || r.command !== command.command || r.priorRevision !== command.expectedRevision || r.resultRevision !== r.priorRevision + 1 || !iso(r.recordedAtISO)) fail(); if (type === "event") { pin(r.definitionPin); if (command.command === "migrate" && command.confirmation !== `MIGRATE ${r.definitionPin.versionId}`) fail(); } else if (command.command === "save_draft" ? r.versionId !== "" : !new RegExp(`^${scope.workflowKind}_v[1-9][0-9]?$`, "u").test(r.versionId) || command.command === "retire" && r.versionId !== command.versionId || command.command === "publish" && command.confirmationText.split(" ")[1] !== r.versionId) fail();
    attempts.delete(key); if (type === "event") releaseEventOperatingMutation(input, "workflow", command.requestId); return freeze(value);
  } catch (error) { const safe = errorFor(error), unknown = prior?.uncertainEver || !isDefinitiveWorkflowError(safe); attempts.set(key, { command, definitive: !unknown, uncertainEver: unknown }); if (type === "event") failEventOperatingMutation(input, "workflow", command.requestId, !unknown); if (unknown) safe.uncertain = true; throw safe; } })(); active.set(key, { payload, promise }); promise.then(() => { if (active.get(key)?.promise === promise) active.delete(key); }, () => { if (active.get(key)?.promise === promise) active.delete(key); }); return promise;
}
export const applyWorkflowDefinitionCommand = (input) => mutate(input, "definition");
export const applyEventWorkflowCommand = (input) => mutate(input, "event");

export const workflowProjectionTools = { exact, id, int, iso, digest, plain, note, pin, version, freeze, fingerprint, fail, errorFor };
