import { httpsCallable } from "firebase/functions";
import { cloudFunctions, firebaseReady } from "./firebase";
import { normalizeWorkflowConfig, WORKFLOW_KINDS, workflowProjectionTools as v } from "./tenantWorkflowClient";
import { beginEventOperatingMutation, failEventOperatingMutation, releaseEventOperatingMutation } from "./eventOperatingMutationGuard";
const attempts = new Map(), active = new Map();
const receiptId = value => /^workflow_command_[a-f0-9]{48}$/u.test(value);
function source(value, scope) {
  v.exact(value, ["schemaVersion", "organizationId", "workflowKind", "subjectId", "sourceVersionId", "sourceReceiptId"]);
  if (value.schemaVersion !== 2 || value.organizationId !== scope.organizationId || value.workflowKind !== scope.workflowKind || value.subjectId !== scope.quoteId || !v.id(value.sourceVersionId) || !v.id(value.sourceReceiptId)) v.fail();
}
function domain(value, kind) {
  v.exact(value, ["schemaVersion", "adapterId", "sourceDigest", "observationKind", "evidenceId", "evidenceDigest", "domainPolicyDigest", "stateCode", "recordedAtISO"]);
  if (value.schemaVersion !== 2 || value.adapterId !== `${kind}_v2` || !v.digest(value.sourceDigest) || !v.digest(value.evidenceDigest) || !v.digest(value.domainPolicyDigest) || !v.id(value.evidenceId) || !["immutable_receipt", "record_snapshot"].includes(value.observationKind) || !/^[a-z][a-z0-9_]{0,63}$/u.test(value.stateCode) || !v.iso(value.recordedAtISO)) v.fail();
}
function schedule(value, anchor = false) {
  if (value?.kind === "instant") { v.exact(value, ["kind", "atISO"]); if (!v.iso(value.atISO)) v.fail(); return Date.parse(value.atISO); }
  v.exact(value, ["kind", "date", "timeZone", ...(anchor ? [] : ["minuteOfDay"])]);
  if (value.kind !== "tenant_calendar_date" || typeof value.timeZone !== "string" || !value.timeZone || value.timeZone.length > 80 || typeof value.date !== "string" || !/^\d{4}-\d{2}-\d{2}$/u.test(value.date) || new Date(`${value.date}T00:00:00.000Z`).toISOString().slice(0, 10) !== value.date || !anchor && !v.int(value.minuteOfDay, 1439)) v.fail();
  try { new Intl.DateTimeFormat("en-US", { timeZone: value.timeZone }); } catch { v.fail(); }
  return Date.parse(`${value.date}T00:00:00.000Z`) + (anchor ? 0 : value.minuteOfDay * 60000);
}
function observedSerial(iso, anchor) {
  if (anchor.kind === "instant") return Date.parse(iso);
  const p = Object.fromEntries(new Intl.DateTimeFormat("en-CA", { timeZone: anchor.timeZone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(iso)).map(part => [part.type, part.value]));
  return Date.parse(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:00.000Z`);
}
function sameSchedule(value, anchor, minutes) { const serial = schedule(value); if (value.kind !== anchor.kind || value.kind === "tenant_calendar_date" && value.timeZone !== anchor.timeZone || serial !== schedule(anchor, true) + minutes * 60000) v.fail(); return serial; }
export function normalizeWorkflowPackSnapshot(s, scope) {
  const base = ["source", "instanceId", "observedAtISO", "historyCoverage", "schemaVersion", "availability", "reasonCode", "revision", "tasks", "actualsReview"];
  source(s.source, scope);
  if (s.schemaVersion !== 2 || !/^workflow_instance_[a-f0-9]{48}$/u.test(s.instanceId) || !v.iso(s.observedAtISO) || s.historyCoverage !== "latest_receipt_only") v.fail();
  if (s.availability === "not_yet_available") {
    v.exact(s, [...base, "nextDefinition", "initializationEligibility"]); v.exact(s.actualsReview, ["state"]); v.exact(s.initializationEligibility, ["eligible", "reasonCode"]);
    if (s.reasonCode !== "not_initialized" || s.revision !== 0 || !Array.isArray(s.tasks) || s.tasks.length || s.actualsReview.state !== "not_yet_available" || !["unpublished", "retired", "published", "domain_missing"].includes(s.initializationEligibility.reasonCode) || typeof s.initializationEligibility.eligible !== "boolean") v.fail();
    if (s.nextDefinition !== null) v.version(s.nextDefinition, scope.organizationId, scope.workflowKind);
    if (s.initializationEligibility.eligible ? s.initializationEligibility.reasonCode !== "published" || !s.nextDefinition : s.initializationEligibility.reasonCode === "published" || s.initializationEligibility.reasonCode !== "domain_missing" && s.nextDefinition !== null) v.fail();
    return s;
  }
  v.exact(s, [...base, "definitionPin", "definitionName", "domainRef", "configuration", "definitionSource", "publishedBy", "publishedAtISO", "scheduleAnchor", "due", "escalation", "comparisonPolicy", "lastReceiptId", "updatedAtISO"]);
  if (s.availability !== "available" || s.reasonCode !== "" || !v.int(s.revision) || s.revision < 1 || !receiptId(s.lastReceiptId) || !v.iso(s.updatedAtISO) || s.updatedAtISO > s.observedAtISO || !v.iso(s.publishedAtISO) || s.publishedAtISO > s.updatedAtISO || s.definitionSource !== "tenant_published") v.fail();
  v.pin(s.definitionPin, scope.workflowKind); normalizeWorkflowConfig(s.configuration); domain(s.domainRef, scope.workflowKind); v.exact(s.publishedBy, ["uid", "role"]);
  if (s.configuration.schemaVersion !== 2 || s.definitionPin.schemaVersion !== 2 || s.configuration.workflowKind !== scope.workflowKind || s.definitionName !== s.configuration.name || s.publishedBy.role !== "admin" || !v.id(s.publishedBy.uid) || s.domainRef.recordedAtISO > s.updatedAtISO) v.fail();
  schedule(s.scheduleAnchor, true); sameSchedule(s.due, s.scheduleAnchor, s.configuration.duePolicy.offsetMinutes); sameSchedule(s.escalation, s.scheduleAnchor, s.configuration.duePolicy.offsetMinutes + s.configuration.escalationPolicy.afterMinutes);
  if (!Array.isArray(s.tasks) || s.tasks.length !== s.configuration.taskTemplates.length) v.fail();
  const observed = observedSerial(s.observedAtISO, s.scheduleAnchor);
  s.tasks.forEach((task, index) => {
    const template = s.configuration.taskTemplates[index]; v.exact(task, [...Object.keys(template), "state", "note", "updatedAtISO", "lastReceiptId", "due", "escalation", "urgency", "escalationRole", "communicationHandoff"]);
    if (Object.keys(template).some(key => task[key] !== template[key]) || !["pending", "acknowledged"].includes(task.state) || task.escalationRole !== "admin") v.fail();
    const due = sameSchedule(task.due, s.scheduleAnchor, template.dueOffsetMinutes), escalation = sameSchedule(task.escalation, s.scheduleAnchor, template.dueOffsetMinutes + s.configuration.escalationPolicy.afterMinutes);
    if (task.urgency !== (task.state === "acknowledged" ? "acknowledged" : observed >= escalation ? "escalated" : observed >= due ? "due" : "upcoming")) v.fail();
    if (task.updatedAtISO === "" ? task.state !== "pending" || task.note !== "" || task.lastReceiptId !== "" : !v.iso(task.updatedAtISO) || task.updatedAtISO > s.updatedAtISO || !receiptId(task.lastReceiptId) || v.note(task.note) !== task.note) v.fail();
    if (template.communicationTemplateRef === null ? task.communicationHandoff !== null : !task.communicationHandoff) v.fail();
    if (task.communicationHandoff) { v.exact(task.communicationHandoff, ["reference", "label", "guidance"]); if (task.communicationHandoff.reference !== template.communicationTemplateRef) v.fail(); v.plain(task.communicationHandoff.label, 80); v.plain(task.communicationHandoff.guidance, 500); }
  });
  const review = s.actualsReview; v.exact(review, ["state", "actualsRef", "thresholdCents"]); if (review.thresholdCents !== s.configuration.actualsReviewThresholdCents) v.fail();
  if (review.actualsRef !== null) { const ref = review.actualsRef; v.exact(ref, ["revision", "receiptId", "receiptDigest", "totalCostCents"]); if (!v.int(ref.revision) || ref.revision < 1 || !/^event_actuals_command_[a-f0-9]{48}$/u.test(ref.receiptId) || !v.digest(ref.receiptDigest) || !v.int(ref.totalCostCents, 50e9)) v.fail(); }
  const states = review.thresholdCents === null ? ["not_applicable"] : !review.actualsRef ? ["not_yet_available"] : review.actualsRef.totalCostCents < review.thresholdCents ? ["not_required"] : ["required", "acknowledged"]; if (!states.includes(review.state)) v.fail();
  if (s.configuration.comparisonPolicy === null ? s.comparisonPolicy !== null : !s.comparisonPolicy) v.fail();
  if (s.comparisonPolicy) { v.exact(s.comparisonPolicy, ["laborBasisPoints", "purchasingBasisPoints", "minimumCents", "declaredBy", "declaredAtISO"]); if (Object.keys(s.configuration.comparisonPolicy).some(key => s.configuration.comparisonPolicy[key] !== s.comparisonPolicy[key]) || s.comparisonPolicy.declaredBy !== s.publishedBy.uid || s.comparisonPolicy.declaredAtISO !== s.publishedAtISO) v.fail(); }
  return s;
}
function requestScope(input, exactSource = false) { if (!v.id(input.organizationId) || !v.id(input.quoteId) || !WORKFLOW_KINDS.includes(input.workflowKind) || input.workflowKind === "quote_review" && !v.id(input.simulationReceiptId) || exactSource && (!v.id(input.sourceVersionId) || !v.id(input.sourceReceiptId))) v.fail("The exact workflow pack source is required.", "invalid-argument"); return { organizationId: input.organizationId, quoteId: input.quoteId, workflowKind: input.workflowKind, ...(input.workflowKind === "quote_review" ? { simulationReceiptId: input.simulationReceiptId } : {}), ...(exactSource ? { sourceVersionId: input.sourceVersionId, sourceReceiptId: input.sourceReceiptId } : {}) }; }
function envelope(value, scope, field, mutation = false) { v.exact(value, ["ok", "storage", "organizationId", "quoteId", "workflowKind", field, ...(mutation ? ["idempotent"] : [])]); if (value.ok !== true || value.storage !== "firebase" || ["organizationId", "quoteId", "workflowKind"].some(key => value[key] !== scope[key]) || mutation && typeof value.idempotent !== "boolean") v.fail(); }
async function call(name, request) { if (!firebaseReady || !cloudFunctions) v.fail("Workflow packs require a connected workspace.", "unavailable"); return (await httpsCallable(cloudFunctions, name)(request)).data; }
async function verifySourceHash(value) {
  const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(v.fingerprint(value.source)));
  const hash = Array.from(new Uint8Array(bytes), byte => byte.toString(16).padStart(2, "0")).join("");
  if (value.instanceId !== `workflow_instance_${hash.slice(0, 48)}` || value.domainRef && value.domainRef.sourceDigest !== hash) v.fail();
}
export async function getWorkflowPackSnapshot(input) { const scope = requestScope(input); try { const result = await call("getWorkflowPackSnapshot", scope); envelope(result, scope, "snapshot"); normalizeWorkflowPackSnapshot(result.snapshot, scope); await verifySourceHash(result.snapshot); if (scope.workflowKind === "quote_review" && result.snapshot.source.sourceReceiptId !== scope.simulationReceiptId) v.fail(); return v.freeze(result); } catch (error) { throw v.errorFor(error); } }
export async function previewWorkflowPackMigration(input) { const scope = requestScope(input, true); if (!v.int(input.expectedRevision)) v.fail(); try { const result = await call("previewWorkflowPackMigration", { ...scope, expectedRevision: input.expectedRevision }); envelope(result, scope, "preview"); const p = result.preview; v.exact(p, ["instanceId", "source", "expectedRevision", "currentDefinitionPin", "targetDefinitionPin", "targetConfiguration", "domainRef", "compatible", "reasons", "confirmation", "previewDigest"]); source(p.source, scope); v.pin(p.currentDefinitionPin, scope.workflowKind); v.pin(p.targetDefinitionPin, scope.workflowKind); domain(p.domainRef, scope.workflowKind); normalizeWorkflowConfig(p.targetConfiguration); if (!/^workflow_instance_[a-f0-9]{48}$/u.test(p.instanceId) || p.source.sourceVersionId !== scope.sourceVersionId || p.source.sourceReceiptId !== scope.sourceReceiptId || p.expectedRevision !== input.expectedRevision || p.targetConfiguration.workflowKind !== scope.workflowKind || p.targetConfiguration.schemaVersion !== 2 || !v.digest(p.previewDigest) || typeof p.compatible !== "boolean" || !Array.isArray(p.reasons) || p.reasons.length > 20 || p.reasons.some(reason => typeof reason !== "string" || reason.length > 240) || p.confirmation !== `MIGRATE ${p.targetDefinitionPin.versionId}` || p.compatible !== (p.reasons.length === 0)) v.fail(); await verifySourceHash(p); return v.freeze(result); } catch (error) { throw v.errorFor(error); } }
const keyFor = input => v.fingerprint([input.principalId, input.organizationId, input.quoteId, input.workflowKind]);
export function readPendingWorkflowPackCommand(input) { const pending = attempts.get(keyFor(input)); return pending ? structuredClone(pending) : null; }
export function resetDefinitiveWorkflowPackCommand(input) { const key = keyFor(input), pending = attempts.get(key); if (!pending?.definitive || active.has(key) || input.workflowKind === "event_execution" && !releaseEventOperatingMutation(input, "workflow", pending.command.requestId, { reviewedReset: true })) return false; attempts.delete(key); return true; }
export function applyWorkflowPackCommand(input) {
  let command; try { const scope = requestScope(input, true); const fields = { task_ack: ["taskKey", "note"], task_reopen: ["taskKey", "note"], migrate: ["previewDigest", "confirmation", "note"], review_ack: ["actualsRevision", "actualsReceiptId", "note"] }[input.command]; if (!fields || !v.id(input.principalId) || !/^[A-Za-z0-9][A-Za-z0-9._:@-]{19,159}$/u.test(input.requestId) || !v.int(input.expectedRevision) || input.command === "review_ack" && input.workflowKind !== "event_execution") v.fail("Review the exact pack command.", "invalid-argument"); v.exact(input, [...Object.keys(scope), "principalId", "requestId", "expectedRevision", "command", ...fields]); command = { ...scope, requestId: input.requestId, expectedRevision: input.expectedRevision, command: input.command, ...Object.fromEntries(fields.map(key => [key, key === "note" ? v.note(input[key]) : input[key]])) }; if (fields.includes("taskKey") && !/^[a-z][a-z0-9_]{0,47}$/u.test(command.taskKey) || fields.includes("previewDigest") && (!v.digest(command.previewDigest) || typeof command.confirmation !== "string") || input.command === "review_ack" && (!v.int(command.actualsRevision) || command.actualsRevision < 1 || !/^event_actuals_command_[a-f0-9]{48}$/u.test(command.actualsReceiptId))) v.fail(); } catch (error) { return Promise.reject(error); }
  const key = keyFor(input), payload = v.fingerprint(command), running = active.get(key), prior = attempts.get(key); if (running) return running.payload === payload ? running.promise : Promise.reject(Object.assign(Error("Check the original pack request first."), { code: "event-mutation-blocked" }));
  if (prior && v.fingerprint(prior.command) !== payload) return Promise.reject(Object.assign(Error("Check the original pack request first."), { code: "event-mutation-blocked" }));
  if (!prior && attempts.size >= 25) return Promise.reject(Object.assign(Error("Review an unresolved pack request first."), { code: "resource-exhausted" }));
  try { if (input.workflowKind === "event_execution") beginEventOperatingMutation(input, "workflow", command); } catch (error) { return Promise.reject(error); }
  attempts.set(key, { command, definitive: false, uncertainEver: prior?.uncertainEver || false });
  const promise = (async () => { try { const result = await call("applyWorkflowPackCommand", command); envelope(result, input, "receipt", true); const r = result.receipt; v.exact(r, ["receiptId", "requestId", "command", "priorRevision", "resultRevision", "recordedAtISO", "definitionPin"]); v.pin(r.definitionPin, input.workflowKind); if (!receiptId(r.receiptId) || r.requestId !== command.requestId || r.command !== command.command || r.priorRevision !== command.expectedRevision || r.resultRevision !== command.expectedRevision + 1 || !v.iso(r.recordedAtISO) || r.definitionPin.schemaVersion !== 2 || command.command === "migrate" && command.confirmation !== `MIGRATE ${r.definitionPin.versionId}`) v.fail(); attempts.delete(key); if (input.workflowKind === "event_execution") releaseEventOperatingMutation(input, "workflow", command.requestId); return v.freeze(result); } catch (error) { const safe = v.errorFor(error), definitive = !prior?.uncertainEver && ["aborted", "already-exists", "failed-precondition", "invalid-argument", "not-found", "permission-denied", "resource-exhausted", "unauthenticated"].includes(safe.code); attempts.set(key, { command, definitive, uncertainEver: !definitive }); if (input.workflowKind === "event_execution") failEventOperatingMutation(input, "workflow", command.requestId, definitive); if (!definitive) safe.uncertain = true; throw safe; } })(); active.set(key, { payload, promise }); promise.then(() => { if (active.get(key)?.promise === promise) active.delete(key); }, () => { if (active.get(key)?.promise === promise) active.delete(key); }); return promise;
}
export function formatWorkflowSchedule(value) { if (!value) return "Unavailable"; if (value.kind === "instant") return value.atISO; const hour = String(Math.floor(value.minuteOfDay / 60)).padStart(2, "0"), minute = String(value.minuteOfDay % 60).padStart(2, "0"); return `${value.date} at ${hour}:${minute} (${value.timeZone}, tenant calendar)`; }
