"use strict";
const { createHash } = require("node:crypto");
class QuoteAttendanceError extends Error { constructor(code, message) { super(message); this.name = "QuoteAttendanceError"; this.code = code; } }
const fail = (code, message) => { throw new QuoteAttendanceError(code, message); };
const clone = (value) => structuredClone(value);
const canonical = (value) => Array.isArray(value) ? value.map(canonical) : value && typeof value === "object" ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])])) : value;
const digest = (value) => createHash("sha256").update(JSON.stringify(canonical(value))).digest("hex");
function freeze(value) { if (value && typeof value === "object") { Object.values(value).forEach(freeze); Object.freeze(value); } return value; }
const POLICY = freeze({ schemaVersion: 1, workflowKind: "final_guest_count", minimumCount: 1, maximumCount: 400, maximumCommands: 100, maximumNoteCharacters: 240, evidenceBoundary: "Requested and submitted guest counts only. A response does not change pricing, acceptance, staffing, payment, readiness or actual attendance." });
const POLICY_DIGEST = digest(POLICY);
const REF_KEYS = ["organizationId", "quoteId", "sourceVersionId", "acceptanceReceiptId"];
const ID = /^[A-Za-z0-9][A-Za-z0-9._:@-]{0,179}$/u, REQUEST_ID = /^[A-Za-z0-9][A-Za-z0-9._:@-]{19,159}$/u, RECEIPT_ID = /^attendance_command_[a-f0-9]{48}$/u;
function keys(value, expected) { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== expected.length || expected.some((key) => !Object.hasOwn(value, key))) fail("invalid-argument", "Attendance fields are missing or unsupported."); }
function identifier(value) { if (typeof value !== "string" || !ID.test(value) || [".", ".."].includes(value)) fail("invalid-argument", "Exact attendance source is required."); return value; }
function integer(value, min = 0, max = POLICY.maximumCommands) { if (!Number.isSafeInteger(value) || value < min || value > max) fail("invalid-argument", "Attendance count or revision is outside its supported bounds."); return value; }
function time(value) { if (typeof value !== "string" || !Number.isFinite(Date.parse(value)) || new Date(value).toISOString() !== value) fail("invalid-argument", "Canonical attendance time is required."); return value; }
function note(value) { if (typeof value !== "string" || !value.trim() || value.trim().length > 240 || /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(value)) fail("invalid-argument", "Describe the staff-recorded source in 1 to 240 characters."); return value.trim(); }
function refs(value) { return Object.fromEntries(REF_KEYS.map((key) => [key, identifier(value[key])])); }
function normalizeSource(value) { keys(value, [...REF_KEYS, "pricedCount"]); return { ...refs(value), pricedCount: integer(value.pricedCount, 1, 400) }; }
function resolveAcceptedSource({ organizationId, quoteId, sourceQuote, sourceVersion, acceptanceReceiptDocument } = {}) {
  const org = identifier(organizationId), quoteKey = identifier(quoteId), quote = sourceQuote || {}, version = sourceVersion || {}, snapshot = version.snapshot;
  if (quote.organizationId !== org) fail("permission-denied", "Attendance source belongs to another organization.");
  if ((quote.id || quoteKey) !== quoteKey || !["accepted", "booked"].includes(quote.status)) fail("failed-precondition", "Attendance requires the exact accepted or booked quote.");
  const customerId = identifier(quote.customerId), sourceVersionId = identifier(quote.activeVersionId || quote.versionMeta?.versionId), receipt = quote.acceptanceReceipt;
  if (!receipt) fail("failed-precondition", "Private acceptance evidence is required.");
  const acceptanceReceiptId = identifier(receipt.receiptId), acceptedAtISO = time(receipt.acceptedAtISO), issuedAtISO = time(receipt.portalIssuedAtISO);
  if (acceptedAtISO < issuedAtISO || ![sourceVersionId, `${sourceVersionId}@${issuedAtISO}`].includes(receipt.quoteRevisionId)) fail("failed-precondition", "Acceptance does not match the current immutable version and issuance.");
  const privateReceipt = acceptanceReceiptDocument, proposal = privateReceipt?.proposalSnapshot;
  const hash = proposal ? createHash("sha256").update(JSON.stringify(proposal)).digest("hex") : "";
  if (!privateReceipt || privateReceipt.receiptId !== acceptanceReceiptId || privateReceipt.organizationId !== org || privateReceipt.quoteId !== quoteKey
    || privateReceipt.quoteRevisionId !== receipt.quoteRevisionId || privateReceipt.acceptedAtISO !== acceptedAtISO || privateReceipt.portalIssuedAtISO !== issuedAtISO
    || !/^[a-f0-9]{64}$/u.test(receipt.snapshotSha256) || privateReceipt.snapshotSha256 !== receipt.snapshotSha256 || hash !== receipt.snapshotSha256
    || proposal.organizationId !== org || proposal.quoteId !== quoteKey || proposal.revisionId !== receipt.quoteRevisionId || proposal.portalIssuedAtISO !== issuedAtISO) fail("failed-precondition", "The private acceptance snapshot cannot be verified.");
  const date = quote.event?.date;
  if (typeof date !== "string" || !/^\d{4}-\d{2}-\d{2}$/u.test(date) || !Number.isFinite(Date.parse(`${date}T00:00:00.000Z`)) || new Date(`${date}T00:00:00.000Z`).toISOString().slice(0, 10) !== date
    || version.legacySynthetic === true || !snapshot || (version.versionId || version.id || version.revisionId) !== sourceVersionId || version.quoteId !== quoteKey || version.organizationId !== org
    || snapshot.id !== quoteKey || snapshot.organizationId !== org || (version.customerId || snapshot.customerId) !== customerId || snapshot.customerId && snapshot.customerId !== customerId
    || snapshot.event?.date !== date) fail("failed-precondition", "The accepted immutable source does not match the quote, customer, and event.");
  const pricedCount = integer(snapshot.event.guests, 1, 400);
  if (quote.event?.guests !== pricedCount || proposal.event?.guests !== undefined && proposal.event.guests !== pricedCount
    || proposal.event?.date !== undefined && proposal.event.date !== date || proposal.customerId !== undefined && proposal.customerId !== customerId) fail("failed-precondition", "Accepted guest-count evidence is contradictory.");
  return freeze({ organizationId: org, quoteId: quoteKey, sourceVersionId, acceptanceReceiptId, pricedCount });
}
function normalizeActor(value) { if (value?.role === "customer") { keys(value, ["organizationId", "role", "portalKeySha256", "portalIssuedAtISO"]); if (!/^[a-f0-9]{64}$/u.test(value.portalKeySha256)) fail("invalid-argument", "A verified portal issuance is required."); return { organizationId: identifier(value.organizationId), role: "customer", portalKeySha256: value.portalKeySha256, portalIssuedAtISO: time(value.portalIssuedAtISO) }; } keys(value, ["organizationId", "role", "uid"]); if (!["admin", "sales"].includes(value.role)) fail("permission-denied", "Attendance requires authorized staff."); return { organizationId: identifier(value.organizationId), role: value.role, uid: identifier(value.uid) }; }
function normalizeTiming(value) { keys(value, ["dueDate", "policyReferenceId", "timezone"]); const date = typeof value.dueDate === "string" && /^\d{4}-\d{2}-\d{2}$/u.test(value.dueDate) ? new Date(`${value.dueDate}T00:00:00.000Z`) : null; if (!date || !Number.isFinite(date.getTime()) || date.toISOString().slice(0, 10) !== value.dueDate || typeof value.timezone !== "string") fail("failed-precondition", "Current tenant-local final-count timing is unavailable."); try { new Intl.DateTimeFormat("en-US", { timeZone: value.timezone }); } catch { fail("failed-precondition", "The tenant timezone is unavailable."); } return { dueDate: value.dueDate, policyReferenceId: identifier(value.policyReferenceId), timezone: value.timezone }; }
function normalizeRequest(input) { const extra = input?.command === "request_confirmation" ? [] : input?.command === "record_response" ? ["confirmationRequestId", "count", "note"] : input?.command === "submit_response" ? ["confirmationRequestId", "count"] : null; if (!extra) fail("invalid-argument", "Unsupported attendance command."); keys(input, [...REF_KEYS, "requestId", "expectedAttendanceRevision", "command", ...extra]); if (!REQUEST_ID.test(input.requestId)) fail("invalid-argument", "A stable attendance request identity is required."); const value = { ...refs(input), requestId: input.requestId, expectedAttendanceRevision: integer(input.expectedAttendanceRevision), command: input.command }; if (extra.length) { if (!RECEIPT_ID.test(input.confirmationRequestId)) fail("invalid-argument", "The exact confirmation request is required."); Object.assign(value, { confirmationRequestId: input.confirmationRequestId, count: integer(input.count, 1, 400) }); if (input.command === "record_response") value.note = note(input.note); } return value; }
function normalizeStaffCommand(input) { const request = normalizeRequest(input); if (request.command === "submit_response") fail("permission-denied", "Customer submission requires portal authority."); return request; }
function normalizePortalCommand(input) { keys(input, ["portalKey", "confirmationRequestId", "expectedSourceVersionId", "expectedPortalIssuedAtISO", "expectedAttendanceRevision", "requestId", "count"]); if (typeof input.portalKey !== "string" || !/^[A-Za-z0-9_-]{20,128}$/u.test(input.portalKey) || !REQUEST_ID.test(input.requestId) || !RECEIPT_ID.test(input.confirmationRequestId)) fail("invalid-argument", "The current portal and original request are required."); return { ...input, expectedSourceVersionId: identifier(input.expectedSourceVersionId), expectedPortalIssuedAtISO: time(input.expectedPortalIssuedAtISO), expectedAttendanceRevision: integer(input.expectedAttendanceRevision), count: integer(input.count, 1, 400) }; }
const ledgerIdFor = (source) => `attendance_${digest(refs(source)).slice(0, 48)}`;
const receiptIdFor = (request) => `attendance_command_${digest({ ...refs(request), requestId: request.requestId }).slice(0, 48)}`;
function emptyState(source) { return { ...source, schemaVersion: 1, attendancePolicyVersion: 1, attendancePolicyDigest: POLICY_DIGEST, ledgerId: ledgerIdFor(source), revision: 0, currentRequest: null, latestResponse: null, createdAtISO: "", updatedAtISO: "", lastReceiptId: "" }; }
function validateState(state, source) { keys(state, [...REF_KEYS, "pricedCount", "schemaVersion", "attendancePolicyVersion", "attendancePolicyDigest", "ledgerId", "revision", "currentRequest", "latestResponse", "createdAtISO", "updatedAtISO", "lastReceiptId"]); if (digest(Object.fromEntries([...REF_KEYS, "pricedCount"].map((key) => [key, state[key]]))) !== digest(source) || state.schemaVersion !== 1 || state.attendancePolicyVersion !== 1 || state.attendancePolicyDigest !== POLICY_DIGEST || state.ledgerId !== ledgerIdFor(source)) fail("data-loss", "Attendance source or policy evidence is inconsistent."); integer(state.revision); if (!state.revision) { if (digest(state) !== digest(emptyState(source))) fail("data-loss", "Empty attendance contains unsupported evidence."); return; } if (!RECEIPT_ID.test(state.lastReceiptId) || !state.currentRequest) fail("data-loss", "Attendance request evidence is missing."); time(state.createdAtISO); time(state.updatedAtISO); if (state.createdAtISO > state.updatedAtISO) fail("data-loss", "Attendance timing is inconsistent."); const r = state.currentRequest; keys(r, ["requestReceiptId", "sourceVersionId", "pricedCount", "dueDate", "requestedAtISO", "requestedBy", "timing"]); normalizeTiming(r.timing); normalizeActor(r.requestedBy); if (r.requestedBy.role === "customer" || r.requestedBy.organizationId !== source.organizationId || !RECEIPT_ID.test(r.requestReceiptId) || r.sourceVersionId !== source.sourceVersionId || r.pricedCount !== source.pricedCount || r.dueDate !== r.timing.dueDate || time(r.requestedAtISO) < state.createdAtISO || r.requestedAtISO > state.updatedAtISO) fail("data-loss", "The current attendance request is inconsistent."); if (state.latestResponse) { const s = state.latestResponse; keys(s, ["submissionReceiptId", "requestReceiptId", "count", "sourceType", "submittedByRole", "submittedAtISO", "supersedesReceiptId", "actor", "note"]); normalizeActor(s.actor); integer(s.count, 1, 400); if (!RECEIPT_ID.test(s.submissionReceiptId) || s.requestReceiptId !== r.requestReceiptId || s.actor.organizationId !== source.organizationId || s.submittedByRole !== s.actor.role || s.sourceType !== (s.actor.role === "customer" ? "customer_portal" : "staff_recorded") || time(s.submittedAtISO) < r.requestedAtISO || s.submittedAtISO > state.updatedAtISO || s.supersedesReceiptId && !RECEIPT_ID.test(s.supersedesReceiptId) || (s.actor.role === "customer" ? s.note !== "" : note(s.note) !== s.note)) fail("data-loss", "Attendance response evidence is inconsistent."); } }
function reduce({ request, actor, source, prior, timing, nowISO, receiptId }) { if (actor.organizationId !== source.organizationId) fail("permission-denied", "Attendance requires the same organization."); if (digest(refs(request)) !== digest(refs(source))) fail("aborted", "The accepted attendance source changed."); if ((actor.role === "customer") !== (request.command === "submit_response")) fail("permission-denied", "This actor cannot perform the attendance command."); if (request.expectedAttendanceRevision !== prior.revision) fail("aborted", "Attendance changed. Refresh the original source."); if (prior.revision >= POLICY.maximumCommands) fail("resource-exhausted", "The attendance receipt limit was reached."); if (prior.updatedAtISO && nowISO < prior.updatedAtISO || actor.role === "customer" && nowISO < actor.portalIssuedAtISO) fail("failed-precondition", "Attendance recording time precedes its source."); const next = { ...clone(prior), revision: prior.revision + 1, createdAtISO: prior.createdAtISO || nowISO, updatedAtISO: nowISO, lastReceiptId: receiptId }; if (request.command === "request_confirmation") { const due = normalizeTiming(timing); next.currentRequest = { requestReceiptId: receiptId, sourceVersionId: source.sourceVersionId, pricedCount: source.pricedCount, dueDate: due.dueDate, requestedAtISO: nowISO, requestedBy: clone(actor), timing: due }; next.latestResponse = null; } else { if (!prior.currentRequest || prior.currentRequest.requestReceiptId !== request.confirmationRequestId) fail("aborted", "The final-count request was replaced. Review the current request."); next.latestResponse = { submissionReceiptId: receiptId, requestReceiptId: request.confirmationRequestId, count: request.count, sourceType: actor.role === "customer" ? "customer_portal" : "staff_recorded", submittedByRole: actor.role, submittedAtISO: nowISO, supersedesReceiptId: prior.latestResponse?.submissionReceiptId || "", actor: clone(actor), note: request.note || "" }; } return next; }
function verifyReceipt(receipt) { try { keys(receipt, ["schemaVersion", "attendancePolicyVersion", "attendancePolicyDigest", "source", "ledgerId", "receiptId", "request", "actor", "timing", "recordedAtISO", "priorRevision", "resultRevision", "priorState", "resultState", "commandDigest", "receiptDigest"]); const { receiptDigest, ...body } = receipt; if (digest(body) !== receiptDigest || body.schemaVersion !== 1 || body.attendancePolicyVersion !== 1 || body.attendancePolicyDigest !== POLICY_DIGEST) fail("data-loss", "Attendance receipt integrity failed."); const source = normalizeSource(body.source), request = normalizeRequest(body.request), actor = normalizeActor(body.actor); if (body.commandDigest !== digest({ request, actor }) || body.ledgerId !== ledgerIdFor(source) || body.receiptId !== receiptIdFor(request) || body.priorRevision !== request.expectedAttendanceRevision || body.resultRevision !== body.priorRevision + 1) fail("data-loss", "Attendance receipt identity failed."); validateState(body.priorState, source); validateState(body.resultState, source); const next = reduce({ source, request, actor, prior: body.priorState, timing: body.timing, nowISO: time(body.recordedAtISO), receiptId: body.receiptId }); if (digest(next) !== digest(body.resultState)) fail("data-loss", "Attendance receipt outcome failed."); return receipt; } catch (error) { if (error.code === "data-loss") throw error; fail("data-loss", "Attendance receipt is malformed or contradictory."); } }
function planCommand({ request: input, actor: actorInput, source: sourceInput, state = null, currentReceipt = null, existingReceipt = null, timing = null, nowISO }) { const request = normalizeRequest(input), actor = normalizeActor(actorInput); if (existingReceipt) { verifyReceipt(existingReceipt); if (existingReceipt.commandDigest !== digest({ request, actor }) || existingReceipt.receiptId !== receiptIdFor(request)) fail("already-exists", "This request identity already belongs to a different attendance command."); return freeze({ idempotent: true, nextState: null, receipt: clone(existingReceipt) }); } const source = normalizeSource(sourceInput), prior = state || emptyState(source); if (state) { verifyReceipt(currentReceipt); if (digest(currentReceipt.resultState) !== digest(state)) fail("data-loss", "The attendance journal and latest receipt disagree."); } else if (currentReceipt) fail("data-loss", "Attendance receipt exists without its journal."); validateState(prior, source); const recordedAtISO = time(nowISO), receiptId = receiptIdFor(request), trustedTiming = request.command === "request_confirmation" ? normalizeTiming(timing) : null; const resultState = reduce({ request, actor, source, prior, timing: trustedTiming, nowISO: recordedAtISO, receiptId }); const body = { schemaVersion: 1, attendancePolicyVersion: 1, attendancePolicyDigest: POLICY_DIGEST, source, ledgerId: ledgerIdFor(source), receiptId, request, actor, timing: trustedTiming, recordedAtISO, priorRevision: prior.revision, resultRevision: resultState.revision, priorState: clone(prior), resultState, commandDigest: digest({ request, actor }) }; const receipt = { ...body, receiptDigest: digest(body) }; verifyReceipt(receipt); return freeze({ idempotent: false, nextState: resultState, receipt }); }
function publicReceipt(receipt) { verifyReceipt(receipt); return freeze({ receiptId: receipt.receiptId, requestId: receipt.request.requestId, command: receipt.request.command, priorRevision: receipt.priorRevision, resultRevision: receipt.resultRevision, recordedAtISO: receipt.recordedAtISO, confirmationRequestId: receipt.resultState.currentRequest.requestReceiptId, submissionReceiptId: receipt.request.command === "request_confirmation" ? "" : receipt.receiptId, count: receipt.request.count ?? null, sourceType: receipt.request.command === "request_confirmation" ? "" : receipt.actor.role === "customer" ? "customer_portal" : "staff_recorded" }); }
function projectSnapshot({ source: sourceInput, state = null, receipt = null, accessMode = "staff", portalIdentity = null }) { const source = normalizeSource(sourceInput); if (!["staff", "portal"].includes(accessMode)) fail("permission-denied", "Attendance projection access is invalid."); if (state) { verifyReceipt(receipt); validateState(state, source); if (digest(receipt.resultState) !== digest(state)) fail("data-loss", "Attendance journal and receipt disagree."); } else if (receipt) fail("data-loss", "Attendance receipt exists without its journal."); const value = state || emptyState(source), r = value.currentRequest, s = value.latestResponse; const ownResponse = accessMode === "staff" || s?.actor.role === "customer" && portalIdentity?.portalKeySha256 === s.actor.portalKeySha256 && portalIdentity?.portalIssuedAtISO === s.actor.portalIssuedAtISO; return freeze({ schemaVersion: 1, organizationId: source.organizationId, quoteId: source.quoteId, sourceVersionId: source.sourceVersionId, ...(accessMode === "staff" ? { acceptanceReceiptId: source.acceptanceReceiptId } : {}), pricedCount: source.pricedCount, revision: value.revision, availability: state ? "available" : "not_yet_available", request: r ? Object.fromEntries(["requestReceiptId", "sourceVersionId", "pricedCount", "dueDate", "requestedAtISO"].map((key) => [key, r[key]])) : null, latestResponse: s && ownResponse ? Object.fromEntries(["submissionReceiptId", "requestReceiptId", "count", "sourceType", "submittedByRole", "submittedAtISO", "supersedesReceiptId"].map((key) => [key, s[key]])) : null, lastReceiptId: value.lastReceiptId, updatedAtISO: value.updatedAtISO, historyCoverage: "latest_request_and_response", evidenceBoundary: POLICY.evidenceBoundary }); }
function submissionReference(receipt) { verifyReceipt(receipt); if (receipt.request.command === "request_confirmation") fail("failed-precondition", "A submitted attendance response is required."); return freeze({ ...receipt.source, ...receipt.resultState.latestResponse, receiptDigest: receipt.receiptDigest }); }
module.exports = { resolveAcceptedSource, QuoteAttendanceError, POLICY, POLICY_DIGEST, digest, normalizeSource, normalizeActor, normalizeTiming, normalizeRequest, normalizeStaffCommand, normalizePortalCommand, ledgerIdFor, receiptIdFor, verifyReceipt, planCommand, publicReceipt, projectSnapshot, submissionReference };
