"""Record builders for the rule tests.

Every test starts from the exporter-produced worked-example bundle and breaks
exactly one thing, so a failure names the rule that regressed rather than a
tangle of inputs. The fixtures are generated by the real exporter from
documents produced by the real writer modules, so these tests exercise the
shape QuotePilot actually writes rather than a belief about it.
"""

from __future__ import annotations

import copy
import json
import os
from typing import Any

from quotepilot_truthloop.loader import load_record
from quotepilot_truthloop.model import CommercialRecord

FIXTURE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "fixtures")
EXAMPLE_BUNDLE_PATH = os.path.join(FIXTURE_DIR, "example-bundle.json")
CURRENT_STATE_BUNDLE_PATH = os.path.join(FIXTURE_DIR, "current-state-bundle.json")


def _read(path: str) -> dict[str, Any]:
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def example_bundle() -> dict[str, Any]:
    """The worked example: the state after payout and fee-schedule producers land."""
    return _read(EXAMPLE_BUNDLE_PATH)


def current_state_bundle() -> dict[str, Any]:
    """What the exporter produces today, with its real producer coverage."""
    return _read(CURRENT_STATE_BUNDLE_PATH)


def clean_record_dict() -> dict[str, Any]:
    """The example record with its one known gap (travel revenue) removed."""
    raw = copy.deepcopy(example_bundle()["records"][0])
    totals = raw["evidence"]["acceptedSnapshot"]["value"]["totalsMinor"]
    totals["total"] -= totals["travel"]
    totals["travel"] = 0
    return raw


#: Keys that live on the record itself rather than inside an evidence section.
RECORD_FIELDS = frozenset(
    {"eventCompleted", "currentCatalogRevision", "quoteNumber", "eventDate",
     "organizationId", "quoteId", "overrunThresholds", "overrunPolicyEvidence"}
)


def record_from(
    values: dict[str, Any] | None = None,
    *,
    unavailable: dict[str, str] | None = None,
) -> CommercialRecord:
    """Build a record, patching evidence values and availability.

    Keys in ``values`` that name an evidence section patch
    ``evidence.<section>.value``; keys that name a record field patch the
    record. ``unavailable`` sets a section's availability and drops its value,
    which is how a test says "this evidence could not be produced" rather than
    "this evidence is empty" -- the distinction the whole contract exists for.
    """
    raw = clean_record_dict()
    for section, patch in (values or {}).items():
        if section in RECORD_FIELDS:
            raw[section] = patch
            if section == "overrunThresholds" and "overrunPolicyEvidence" not in (values or {}):
                # An explicit synthetic policy override supplies its own matching
                # envelope, just as evidence-value overrides do below.
                raw["overrunPolicyEvidence"] = {
                    "availability": "available", "value": copy.deepcopy(patch),
                    "constraintClass": "none", "detail": "Explicit synthetic operator declaration.",
                    "provenance": {},
                }
            continue
        if section not in raw["evidence"]:
            raise AssertionError(f"Unknown evidence section in test: {section}")
        envelope = raw["evidence"][section]
        if isinstance(patch, dict) and isinstance(envelope.get("value"), dict) and patch:
            _deep_update(envelope["value"], patch)
        else:
            envelope["value"] = patch
        envelope["availability"] = "available"
    for section, availability in (unavailable or {}).items():
        envelope = raw["evidence"][section]
        envelope.pop("value", None)
        envelope["availability"] = availability
        envelope.setdefault("detail", f"{section} is {availability} in this test.")
        if availability == "blocked_by_integration":
            envelope.setdefault("blockedBy", "test_integration_gate")
        if availability == "contradictory":
            envelope.setdefault("conflict", {"left": 1, "right": 2})
    return load_record(raw)


def _deep_update(target: dict[str, Any], patch: dict[str, Any]) -> None:
    """Merge ``patch`` into ``target``; an empty dict replaces rather than merges."""
    for key, value in patch.items():
        if isinstance(value, dict) and isinstance(target.get(key), dict) and value:
            _deep_update(target[key], value)
        else:
            target[key] = value


def finding_for(record: CommercialRecord, rule_id: str):
    from quotepilot_truthloop.engine import reconcile_record

    result = reconcile_record(record, "2026-08-21T14:00:00.000Z")
    for finding in result.findings:
        if finding.rule_id == rule_id:
            return finding
    raise AssertionError(f"No finding produced for rule {rule_id}.")
