// @vitest-environment jsdom
import React from "react";
import { act } from "react-dom/test-utils";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import EventWorkflowPolicyPanel from "../EventWorkflowPolicyPanel";
const api = vi.hoisted(() => ({ applyEventWorkflowCommand: vi.fn(), createWorkflowRequestId: vi.fn(), getEventWorkflowSnapshot: vi.fn(), isDefinitiveWorkflowError: vi.fn(), previewEventWorkflowMigration: vi.fn(), readPendingWorkflowCommand: vi.fn(), resetDefinitiveWorkflowCommand: vi.fn() })); vi.mock("../../lib/tenantWorkflowClient", () => api);
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const refs = { sourceVersionId: "version-a", acceptanceReceiptId: "accept-a" }, pin = { versionId: "event_execution_v1" };
const task = { taskKey: "review_context", label: "Review context", instruction: "Review source", ownerRole: "sales", state: "pending", urgency: "due", dueAtISO: "2026-09-05T10:00:00.000Z", escalationAtISO: "2026-09-05T11:00:00.000Z", communicationHandoff: { label: "Internal brief", guidance: "Use an approved communication surface." } };
const snapshot = (overrides = {}) => ({ ...refs, availability: "available", revision: 2, phaseRevision: 1, phaseReceiptId: "phase-receipt", definitionPin: pin, definitionName: "Tenant policy", definitionSource: "tenant_published", configuration: { name: "Tenant policy", allowedRoles: ["admin", "sales"], actualsReviewThresholdCents: 0, comparisonPolicy: null, duePolicy: { offsetMinutes: 0 }, escalationPolicy: { afterMinutes: 60, role: "admin" }, taskTemplates: [{ ...task, dueOffsetMinutes: 0, communicationTemplateRef: "internal_event_brief_v1" }] }, tasks: [task], actualsReview: { state: "not_yet_available", thresholdCents: 0, actualsRef: null }, publishedBy: { uid: "admin-a", role: "admin" }, publishedAtISO: "2026-09-05T09:00:00.000Z", dueAtISO: task.dueAtISO, escalationAtISO: task.escalationAtISO, updatedAtISO: task.dueAtISO, comparisonPolicy: null, lastReceiptId: "workflow-receipt", ...overrides });
const empty = () => snapshot({ availability: "not_yet_available", reasonCode: "phase_ledger_missing", nextDefinition: { config: { name: "Seed coordination" }, versionId: "event_execution_v0", seed: true }, initializationEligibility: { eligible: true, reasonCode: "seed" } });
const props = { organizationId: "org-a", quoteId: "quote-a", principalId: "admin-a", role: "admin", enabled: true, source: "firebase", ...refs, phaseSnapshot: { revision: 1, lastReceiptId: "phase-receipt" }, phaseReadState: "success", onWorkflowMutationBlockedChange: vi.fn(), onInitializationEligibilityChange: vi.fn() };
const deferred = () => { let resolve, reject; const promise = new Promise((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; };
let host, root; async function render(overrides = {}) { await act(async () => root.render(<EventWorkflowPolicyPanel {...props} {...overrides} />)); } async function click(label) { const node = [...host.querySelectorAll("button")].find((node) => node.textContent === label); expect(node).toBeTruthy(); await act(async () => node.click()); } async function fill(index, value) { const node = host.querySelectorAll("input")[index]; expect(node).toBeTruthy(); await act(async () => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set.call(node, value); node.dispatchEvent(new Event("input", { bubbles: true })); }); }
beforeEach(() => { vi.resetAllMocks(); api.getEventWorkflowSnapshot.mockResolvedValue({ snapshot: snapshot() }); api.createWorkflowRequestId.mockReturnValue("workflow_request_00000001"); api.readPendingWorkflowCommand.mockReturnValue(null); host = document.createElement("div"); document.body.append(host); root = createRoot(host); }); afterEach(async () => { await act(async () => root.unmount()); host.remove(); });
test("event coordination renders all canonical read states", async () => {
  const pending = deferred(); api.getEventWorkflowSnapshot.mockReturnValueOnce(pending.promise); await render(); expect(host.innerHTML).toContain('data-capability-state="loading"'); await act(async () => pending.resolve({ snapshot: empty() })); expect(host.innerHTML).toContain('data-capability-state="empty"'); expect(host.innerHTML).toContain('data-capability-state="ready"'); expect(props.onInitializationEligibilityChange).toHaveBeenLastCalledWith(true);
  await click("Refresh coordination"); expect(host.innerHTML).toContain('data-capability-state="success"'); expect(host.innerHTML).toContain('data-capability-state="partial"'); api.getEventWorkflowSnapshot.mockRejectedValueOnce(new Error("Unavailable")); await click("Refresh coordination"); expect(host.innerHTML).toContain('data-capability-state="stale"');
  api.getEventWorkflowSnapshot.mockRejectedValueOnce(new Error("Unavailable")); await render({ quoteId: "quote-b" }); expect(host.innerHTML).toContain('data-capability-state="error"'); await render({ role: "customer" }); expect(host.innerHTML).toContain('data-capability-state="recovery"');
});
test("event coordination renders all canonical mutation states", async () => {
  await render(); await click("Acknowledge Review context"); expect(document.activeElement).toBe(host.querySelector("input")); await fill(0, "Source reviewed"); const request = deferred(); api.applyEventWorkflowCommand.mockReturnValueOnce(request.promise); await click("Record coordination change"); expect(host.innerHTML).toContain('data-capability-state="submitting"'); expect(props.onWorkflowMutationBlockedChange).toHaveBeenLastCalledWith(true);
  await act(async () => request.reject(new Error("Unknown"))); expect(host.innerHTML).toContain('data-capability-state="uncertain"'); await render({ otherMutationBlocked: true }); const replay = deferred(); api.applyEventWorkflowCommand.mockReturnValueOnce(replay.promise); await click("Check original coordination request"); expect(host.innerHTML).toContain('data-capability-state="reconciliation"'); expect(api.applyEventWorkflowCommand.mock.calls[1][0]).toEqual(api.applyEventWorkflowCommand.mock.calls[0][0]);
  api.getEventWorkflowSnapshot.mockResolvedValueOnce({ snapshot: snapshot({ revision: 5 }) }); await act(async () => replay.resolve({ idempotent: true, receipt: { command: "task_ack", receiptId: "old-receipt" } })); expect(host.innerHTML).toContain('data-capability-state="receipt"'); expect(host.textContent).toContain("Coordinator revision 5"); expect(document.activeElement).toBe(host.querySelector('[aria-label="Coordination request outcome"]'));
});
test("coordination sales can acknowledge assigned tasks but cannot review costs or migrate", async () => {
  api.getEventWorkflowSnapshot.mockResolvedValueOnce({ snapshot: snapshot({ actualsReview: { state: "required", thresholdCents: 0, actualsRef: { revision: 7, receiptId: "actuals-receipt", totalCostCents: 0 } } }) }); await render({ role: "sales" }); expect(host.textContent).toContain("Acknowledge Review context"); expect(host.textContent).not.toContain("Acknowledge actuals review"); expect(host.textContent).not.toContain("Preview migration"); expect(host.textContent).toContain("No message is sent");
  await render({ role: "admin" }); expect(host.textContent).toContain("All three cost categories must be declared complete"); api.getEventWorkflowSnapshot.mockResolvedValueOnce({ snapshot: snapshot({ actualsReview: { state: "required", thresholdCents: 0, actualsRef: { revision: 7, receiptId: "actuals-receipt", totalCostCents: 0 } } }) }); await click("Refresh coordination"); await click("Acknowledge actuals review"); await fill(0, "Reviewed explicit zero"); api.applyEventWorkflowCommand.mockResolvedValueOnce({ receipt: { command: "review_ack", receiptId: "receipt" } }); await click("Record coordination change"); expect(api.applyEventWorkflowCommand.mock.calls[0][0]).toMatchObject({ command: "review_ack", actualsRevision: 7, actualsReceiptId: "actuals-receipt" });
});
test("coordination migration is exact event preview typed confirmation and never automatic", async () => {
  await render(); const preview = { targetConfiguration: { ...snapshot().configuration, name: "Updated coordination" }, compatible: false, reasons: ["acknowledged_task_changed"], currentDefinitionPin: pin, targetDefinitionPin: { versionId: "event_execution_v2" }, previewDigest: "b".repeat(64), confirmation: "MIGRATE event_execution_v2" }; api.previewEventWorkflowMigration.mockResolvedValueOnce({ preview }); await click("Preview migration to current published version"); expect(host.textContent).toContain("Migration is incompatible"); expect(host.textContent).toContain("Updated coordination"); expect(host.textContent).toContain("Current configuration"); expect(host.querySelector("form")).toBeNull(); expect(api.applyEventWorkflowCommand).not.toHaveBeenCalled();
  api.previewEventWorkflowMigration.mockResolvedValueOnce({ preview: { ...preview, compatible: true, reasons: [] } }); await click("Preview migration to current published version"); await fill(0, "Reviewed compatible migration"); await fill(1, preview.confirmation); api.applyEventWorkflowCommand.mockResolvedValueOnce({ receipt: { command: "migrate", receiptId: "migration-receipt" } }); await click("Record coordination change"); expect(api.applyEventWorkflowCommand.mock.calls[0][0]).toMatchObject({ ...refs, command: "migrate", expectedRevision: 2, previewDigest: preview.previewDigest, confirmation: preview.confirmation });
});
test("coordination retired initialization and source changes cannot substitute bindings", async () => {
  api.getEventWorkflowSnapshot.mockResolvedValueOnce({ snapshot: { ...empty(), nextDefinition: null, initializationEligibility: { eligible: false, reasonCode: "retired" } } }); await render(); expect(props.onInitializationEligibilityChange).toHaveBeenLastCalledWith(false); expect(host.textContent).toContain("initialization is blocked: retired");
  const command = { ...refs, requestId: "original_request_0000001", expectedRevision: 2, command: "task_ack", taskKey: "review_context", note: "Original note" }; api.readPendingWorkflowCommand.mockReturnValueOnce({ command, definitive: false }); await render({ sourceVersionId: "new-version", acceptanceReceiptId: "new-accept" }); expect(host.textContent).toContain("accepted event source changed"); api.applyEventWorkflowCommand.mockRejectedValueOnce(new Error("Still unknown")); await click("Check original coordination request"); expect(api.applyEventWorkflowCommand.mock.calls[0][0]).toMatchObject(command);
});

test("coordination refreshes actuals obligations after sibling receipt without a phase transition", async () => {
  api.getEventWorkflowSnapshot.mockResolvedValueOnce({ snapshot: snapshot({ actualsReview: { state: "acknowledged", thresholdCents: 0, actualsRef: { revision: 3, receiptId: "actuals-three", totalCostCents: 0 } } }) });
  await render(); await render({ otherMutationBlocked: true }); expect(host.innerHTML).toContain('data-capability-state="stale"');
  api.getEventWorkflowSnapshot.mockResolvedValueOnce({ snapshot: snapshot() }); await render({ otherMutationBlocked: false });
  expect(api.getEventWorkflowSnapshot).toHaveBeenCalledTimes(2); expect(host.textContent).toContain("not yet available"); expect(host.textContent).not.toContain("Acknowledge actuals review");
});
