// @vitest-environment jsdom
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import PortalAttendanceQuestionnaire from "../PortalAttendanceQuestionnaire";
const api = vi.hoisted(() => ({ applyQuoteAttendanceCommand: vi.fn(), submitQuoteAttendanceResponse: vi.fn(), createAttendanceRequestId: vi.fn(), getQuoteAttendance: vi.fn(), isDefinitiveAttendanceError: vi.fn(), readPendingAttendanceCommand: vi.fn(), resetDefinitiveAttendanceCommand: vi.fn() })); vi.mock("../../lib/quoteAttendanceClient", () => api);
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const props = { portalKey: "portal_key_abcdefghijklmnop", enabled: true, expectedSourceVersionId: "version-a", expectedPortalIssuedAtISO: "2026-09-01T00:00:00.000Z" }, empty = { sourceVersionId: "version-a", availability: "not_yet_available", pricedCount: 120, revision: 0, request: null, latestResponse: null }, requested = { ...empty, availability: "available", revision: 1, request: { requestReceiptId: "request-receipt", dueDate: "2026-09-12", requestedAtISO: "2026-09-05T20:00:00.000Z" } };
let host, root; const deferred = () => { let resolve, reject; const promise = new Promise((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; };
async function render(extra = {}) { await act(async () => root.render(<PortalAttendanceQuestionnaire {...props} {...extra} />)); }
async function click(text) { const b = [...host.querySelectorAll("button")].find((n) => n.textContent === text); expect(b).toBeTruthy(); await act(async () => b.click()); }
async function count(value) { const n = host.querySelector("input"); await act(async () => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set.call(n, value); n.dispatchEvent(new Event("input", { bubbles: true })); }); }
beforeEach(() => { vi.resetAllMocks(); api.getQuoteAttendance.mockResolvedValue({ snapshot: requested }); api.createAttendanceRequestId.mockReturnValue("attendance_request_0001"); api.readPendingAttendanceCommand.mockReturnValue(null); host = document.createElement("div"); document.body.append(host); root = createRoot(host); });
afterEach(async () => { await act(async () => root.unmount()); host.remove(); });
test("portal attendance renders all canonical read states", async () => { const d = deferred(); api.getQuoteAttendance.mockReturnValueOnce(d.promise); await render(); expect(host.innerHTML).toContain('data-capability-state="loading"'); await act(async () => d.resolve({ snapshot: empty })); expect(host.innerHTML).toContain('data-capability-state="empty"'); expect(host.innerHTML).toContain('data-capability-state="ready"'); expect(host.innerHTML).toContain('data-capability-state="partial"'); api.getQuoteAttendance.mockResolvedValueOnce({ snapshot: requested }); await click("Refresh count request"); expect(host.innerHTML).toContain('data-capability-state="success"'); api.getQuoteAttendance.mockRejectedValueOnce(Error("Unavailable")); await click("Refresh count request"); expect(host.innerHTML).toContain('data-capability-state="stale"'); api.getQuoteAttendance.mockRejectedValueOnce(Error("Unavailable")); await render({ portalKey: "different_portal_key_abcdef" }); expect(host.innerHTML).toContain('data-capability-state="error"'); await render({ enabled: false }); expect(host.innerHTML).toContain('data-capability-state="recovery"'); });
test("portal attendance renders all canonical mutation states", async () => { await render(); await click("Submit guest count"); await count("130"); const d = deferred(); api.submitQuoteAttendanceResponse.mockReturnValueOnce(d.promise); await click("Record my response"); expect(host.innerHTML).toContain('data-capability-state="submitting"'); await act(async () => d.reject(Error("Unknown"))); expect(host.innerHTML).toContain('data-capability-state="uncertain"'); const replay = deferred(); api.submitQuoteAttendanceResponse.mockReturnValueOnce(replay.promise); await click("Check original attendance request"); expect(host.innerHTML).toContain('data-capability-state="reconciliation"'); expect(api.submitQuoteAttendanceResponse.mock.calls[0][0]).toEqual(api.submitQuoteAttendanceResponse.mock.calls[1][0]); await act(async () => replay.resolve({ receipt: { command: "submit_response" }, idempotent: true })); expect(host.innerHTML).toContain('data-capability-state="receipt"'); expect(document.activeElement).toBe(host.querySelector('[aria-label="Guest-count response outcome"]')); expect(api.getQuoteAttendance).toHaveBeenCalledTimes(2); });
test("portal questionnaire submits explicit bounded count with exact source and issuance only", async () => { await render(); expect(host.textContent).not.toContain("Request final guest count"); expect(host.textContent).not.toContain("Review and apply"); expect(host.textContent).not.toContain("Acceptance receipt"); await click("Submit guest count"); expect(document.activeElement).toBe(host.querySelector("input")); await count("0"); await click("Record my response"); expect(api.submitQuoteAttendanceResponse).not.toHaveBeenCalled(); await count("120"); api.submitQuoteAttendanceResponse.mockResolvedValueOnce({ receipt: { command: "submit_response" } }); await click("Record my response"); expect(api.submitQuoteAttendanceResponse.mock.calls[0][0]).toEqual({ portalKey: props.portalKey, expectedSourceVersionId: props.expectedSourceVersionId, expectedPortalIssuedAtISO: props.expectedPortalIssuedAtISO, confirmationRequestId: "request-receipt", count: 120, expectedAttendanceRevision: 1, requestId: "attendance_request_0001" }); });
