// @vitest-environment jsdom
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import QuoteAttendancePanel from "../QuoteAttendancePanel";
const api = vi.hoisted(() => ({ applyQuoteAttendanceCommand: vi.fn(), submitQuoteAttendanceResponse: vi.fn(), createAttendanceRequestId: vi.fn(), getQuoteAttendance: vi.fn(), isDefinitiveAttendanceError: vi.fn(), readPendingAttendanceCommand: vi.fn(), resetDefinitiveAttendanceCommand: vi.fn() })); vi.mock("../../lib/quoteAttendanceClient", () => api);
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const refs = { organizationId: "org-a", quoteId: "quote-a", sourceVersionId: "version-a", acceptanceReceiptId: "accept-a" }, props = { ...refs, principalId: "admin-a", role: "admin", enabled: true, source: "firebase", onStageCommercialChange: vi.fn() };
const empty = { ...refs, schemaVersion: 1, pricedCount: 120, availability: "not_yet_available", revision: 0, request: null, latestResponse: null, lastReceiptId: "", updatedAtISO: "" }, requested = { ...empty, availability: "available", revision: 1, request: { requestReceiptId: "request-receipt", sourceVersionId: "version-a", pricedCount: 120, dueDate: "2026-09-12", requestedAtISO: "2026-09-05T20:00:00.000Z" } };
let host, root; const deferred = () => { let resolve, reject; const promise = new Promise((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; };
async function render(extra = {}) { await act(async () => root.render(<QuoteAttendancePanel {...props} {...extra} />)); }
async function click(text) { const b = [...host.querySelectorAll("button")].find((n) => n.textContent === text); expect(b).toBeTruthy(); await act(async () => b.click()); }
async function fill(selector, value) { const n = host.querySelector(selector); await act(async () => { Object.getOwnPropertyDescriptor(n.tagName === "TEXTAREA" ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype, "value").set.call(n, value); n.dispatchEvent(new Event("input", { bubbles: true })); }); }
beforeEach(() => { vi.resetAllMocks(); api.getQuoteAttendance.mockResolvedValue({ snapshot: empty }); api.createAttendanceRequestId.mockReturnValue("attendance_request_0001"); api.readPendingAttendanceCommand.mockReturnValue(null); host = document.createElement("div"); document.body.append(host); root = createRoot(host); });
afterEach(async () => { await act(async () => root.unmount()); host.remove(); });
test("staff attendance renders all canonical read states", async () => { const d = deferred(); api.getQuoteAttendance.mockReturnValueOnce(d.promise); await render(); expect(host.innerHTML).toContain('data-capability-state="loading"'); await act(async () => d.resolve({ snapshot: empty })); expect(host.innerHTML).toContain('data-capability-state="empty"'); expect(host.innerHTML).toContain('data-capability-state="ready"'); expect(host.innerHTML).toContain('data-capability-state="partial"'); api.getQuoteAttendance.mockResolvedValueOnce({ snapshot: requested }); await click("Refresh count request"); expect(host.innerHTML).toContain('data-capability-state="success"'); api.getQuoteAttendance.mockRejectedValueOnce(Error("Unavailable")); await click("Refresh count request"); expect(host.innerHTML).toContain('data-capability-state="stale"'); api.getQuoteAttendance.mockRejectedValueOnce(Error("Unavailable")); await render({ quoteId: "quote-b" }); expect(host.innerHTML).toContain('data-capability-state="error"'); await render({ role: "viewer" }); expect(host.innerHTML).toContain('data-capability-state="recovery"'); });
test("staff attendance renders all canonical mutation states", async () => { await render(); const d = deferred(); api.applyQuoteAttendanceCommand.mockReturnValueOnce(d.promise); await click("Request final guest count"); expect(host.innerHTML).toContain('data-capability-state="submitting"'); await act(async () => d.reject(Error("Unknown"))); expect(host.innerHTML).toContain('data-capability-state="uncertain"'); const replay = deferred(); api.applyQuoteAttendanceCommand.mockReturnValueOnce(replay.promise); await click("Check original attendance request"); expect(host.innerHTML).toContain('data-capability-state="reconciliation"'); expect(api.applyQuoteAttendanceCommand.mock.calls[0][0]).toEqual(api.applyQuoteAttendanceCommand.mock.calls[1][0]); await act(async () => replay.resolve({ receipt: { command: "request_confirmation" }, idempotent: true })); expect(host.innerHTML).toContain('data-capability-state="receipt"'); expect(document.activeElement).toBe(host.querySelector('[aria-label="Attendance request outcome"]')); expect(api.getQuoteAttendance).toHaveBeenCalledTimes(2); });
test("staff source-backed matching response stages exact commercial evidence without applying count", async () => { api.getQuoteAttendance.mockResolvedValueOnce({ snapshot: requested }); await render({ role: "sales" }); await click("Record supplied guest count"); expect(document.activeElement).toBe(host.querySelector("input")); await fill("input", "120"); await fill("textarea", "Customer supplied this number during the planning call"); api.applyQuoteAttendanceCommand.mockResolvedValueOnce({ receipt: { command: "record_response" } }); api.getQuoteAttendance.mockResolvedValueOnce({ snapshot: { ...requested, revision: 2, latestResponse: { submissionReceiptId: "response-receipt", requestReceiptId: "request-receipt", count: 120, sourceType: "staff_recorded", submittedByRole: "sales", submittedAtISO: "2026-09-05T20:10:00.000Z" } } }); await click("Save staff-recorded response"); expect(api.applyQuoteAttendanceCommand.mock.calls[0][0]).toMatchObject({ ...refs, command: "record_response", count: 120, note: "Customer supplied this number during the planning call" }); expect(host.textContent).toContain("Staff-recorded response"); expect(host.textContent).toContain("final application still requires"); await click("Review and apply supplied count"); expect(props.onStageCommercialChange).toHaveBeenCalledWith({ ...refs, submissionReceiptId: "response-receipt", count: 120 }); expect(host.textContent).toContain("No final count has been applied"); });
test("staff source remount retains uncertain original and rejects unverified new-source read", async () => { api.readPendingAttendanceCommand.mockReturnValue({ command: { ...refs, command: "request_confirmation", requestId: "original", expectedAttendanceRevision: 0 }, definitive: false }); await render({ sourceVersionId: "new-version" }); expect(host.textContent).toContain("accepted event source changed"); expect(host.querySelector('[data-capability-state="uncertain"]')).not.toBeNull(); api.applyQuoteAttendanceCommand.mockResolvedValueOnce({ receipt: { command: "request_confirmation" } }); await click("Check original attendance request"); expect(api.applyQuoteAttendanceCommand.mock.calls[0][0].sourceVersionId).toBe("version-a"); });


test("keeps exact-request recovery exposed while supporting evidence stays collapsed", async () => {
  api.readPendingAttendanceCommand.mockReturnValue({ definitive: false, command: { ...refs, command: "request_confirmation", requestId: "original", expectedAttendanceRevision: 0 } });
  api.getQuoteAttendance.mockResolvedValue({ snapshot: requested });
  await render();
  const recovery = [...host.querySelectorAll('button')].find(node => node.textContent === "Check original attendance request");
  expect(recovery.closest('details')).toBeNull();
  expect(host.querySelector('.attendance-workflow-panel__evidence').open).toBe(false);
  expect([...host.querySelectorAll('button')].find(node => node.textContent === "Record supplied guest count").disabled).toBe(true);
  await click("Check original attendance request");
  expect(api.applyQuoteAttendanceCommand.mock.calls[0][0].requestId).toBe("original");
});
