// @vitest-environment jsdom
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { beforeEach, afterEach, expect, test, vi } from "vitest";
const api = vi.hoisted(() => ({ getWorkflowPackSnapshot: vi.fn(), applyWorkflowPackCommand: vi.fn(), previewWorkflowPackMigration: vi.fn(), readPendingWorkflowPackCommand: vi.fn(), resetDefinitiveWorkflowPackCommand: vi.fn(), formatWorkflowSchedule: value => value?.atISO || value?.date || "Unavailable" }));
vi.mock("../../lib/workflowPackClient", () => api);
vi.mock("../../lib/tenantWorkflowClient", () => ({ createWorkflowRequestId: () => "workflow_request_00000001", isDefinitiveWorkflowError: error => error.code === "aborted" }));
import WorkflowPackPolicyPanel from "../WorkflowPackPolicyPanel";
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const props = { organizationId: "org-a", quoteId: "quote-a", principalId: "admin-a", role: "admin", source: "firebase", enabled: true, workflowKind: "final_guest_count", sourceVersionId: "version-a", sourceReceiptId: "accept-a" };
const config = { name: "Final count workflow", allowedRoles: ["admin", "sales"], actualsReviewThresholdCents: null, comparisonPolicy: null, duePolicy: { offsetMinutes: 0 }, escalationPolicy: { afterMinutes: 60, role: "admin" }, taskTemplates: [] };
function snapshot(kind = "final_guest_count", available = true) { const base = { source: { sourceVersionId: "version-a", sourceReceiptId: kind === "quote_review" ? "simulation-a" : "accept-a" }, availability: available ? "available" : "not_yet_available", revision: available ? 1 : 0 }; return available ? { ...base, definitionName: "Published workflow", definitionPin: { version: 1, versionId: `${kind}_v1` }, due: { atISO: "2026-09-06T00:00:00.000Z" }, escalation: { atISO: "2026-09-06T01:00:00.000Z" }, configuration: config, updatedAtISO: "2026-09-05T20:00:00.000Z", lastReceiptId: "receipt-a", tasks: [{ taskKey: "review_context", label: "Review exact source", instruction: "Read the domain receipt", ownerRole: "sales", state: "pending", urgency: "upcoming", due: {}, escalation: {}, communicationHandoff: null }] } : { ...base, initializationEligibility: { eligible: false, reasonCode: "unpublished" }, nextDefinition: null }; }
let host, root;
const deferred = () => { let resolve, reject; const promise = new Promise((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; };
async function render(extra = {}) { await act(async () => root.render(<WorkflowPackPolicyPanel {...props} {...extra} />)); }
async function click(text) { const button = [...host.querySelectorAll("button")].find(node => node.textContent === text); expect(button).toBeTruthy(); await act(async () => button.click()); }
async function fill(value) { const input = host.querySelector('input'); await act(async () => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set.call(input, value); input.dispatchEvent(new Event("input", { bubbles: true })); }); }
beforeEach(() => { vi.resetAllMocks(); api.getWorkflowPackSnapshot.mockResolvedValue({ snapshot: snapshot() }); api.readPendingWorkflowPackCommand.mockReturnValue(null); host = document.createElement("div"); document.body.append(host); root = createRoot(host); });
afterEach(async () => { await act(async () => root.unmount()); host.remove(); });
test("workflow packs render all canonical read states", async () => {
  const d = deferred(); api.getWorkflowPackSnapshot.mockReturnValueOnce(d.promise); await render(); expect(host.innerHTML).toContain('data-capability-state="loading"'); await act(async () => d.resolve({ snapshot: snapshot("final_guest_count", false) })); expect(host.innerHTML).toContain('data-capability-state="empty"'); expect(host.innerHTML).toContain('data-capability-state="ready"'); expect(host.innerHTML).toContain('data-capability-state="partial"'); await click("Refresh pack coordination"); expect(host.innerHTML).toContain('data-capability-state="success"'); api.getWorkflowPackSnapshot.mockRejectedValueOnce(Error("Unavailable")); await click("Refresh pack coordination"); expect(host.innerHTML).toContain('data-capability-state="stale"'); api.getWorkflowPackSnapshot.mockRejectedValueOnce(Error("Unavailable")); await render({ quoteId: "other" }); expect(host.innerHTML).toContain('data-capability-state="error"'); await render({ role: "finance" }); expect(host.innerHTML).toContain('data-capability-state="recovery"');
});
test("workflow packs render all canonical mutation states", async () => {
  await render(); await click("Acknowledge Review exact source"); expect(document.activeElement).toBe(host.querySelector("input")); await fill("Reviewed receipt"); const d = deferred(); api.applyWorkflowPackCommand.mockReturnValueOnce(d.promise); await click("Record pack coordination"); expect(host.innerHTML).toContain('data-capability-state="submitting"'); await act(async () => d.reject(Error("Unknown"))); expect(host.innerHTML).toContain('data-capability-state="uncertain"'); const retry = deferred(); api.applyWorkflowPackCommand.mockReturnValueOnce(retry.promise); await click("Check original pack request"); expect(host.innerHTML).toContain('data-capability-state="reconciliation"'); expect(api.applyWorkflowPackCommand.mock.calls[0][0]).toEqual(api.applyWorkflowPackCommand.mock.calls[1][0]); await act(async () => retry.resolve({ idempotent: true, receipt: { command: "task_ack", receiptId: "receipt-old" } })); expect(host.innerHTML).toContain('data-capability-state="receipt"'); expect(api.getWorkflowPackSnapshot).toHaveBeenCalledTimes(2); expect(document.activeElement).toBe(host.querySelector('[aria-label="Pack request outcome"]'));
});
test.each(["quote_review", "final_guest_count", "closeout_follow_up"])("%s mounts exact staff source and keeps sales migration restricted", async kind => {
  api.getWorkflowPackSnapshot.mockResolvedValue({ snapshot: snapshot(kind) }); const refs = kind === "quote_review" ? { sourceReceiptId: "simulation-a", simulationReceiptId: "simulation-a" } : {};
  await render({ workflowKind: kind, role: "sales", ...refs }); expect(host.querySelector(`[data-workflow-pack="${kind}"]`)).toBeTruthy(); expect(api.getWorkflowPackSnapshot).toHaveBeenCalledWith(expect.objectContaining({ organizationId: "org-a", quoteId: "quote-a", workflowKind: kind, principalId: "admin-a", ...(kind === "quote_review" ? { simulationReceiptId: "simulation-a" } : {}) })); expect(host.textContent).not.toContain("Preview pack migration"); await click("Acknowledge Review exact source"); await fill("Reviewed exact source"); api.applyWorkflowPackCommand.mockResolvedValueOnce({ receipt: { command: "task_ack", receiptId: "receipt-a" } }); await click("Record pack coordination"); expect(api.applyWorkflowPackCommand.mock.calls[0][0]).toMatchObject({ workflowKind: kind, sourceVersionId: "version-a", sourceReceiptId: refs.sourceReceiptId || "accept-a" });
});
test("domain change clears open intent and historical replay refreshes current tasks", async () => {
  await render(); await click("Acknowledge Review exact source"); await render({ otherMutationBlocked: true }); expect(host.querySelector("form")).toBeNull(); expect(host.querySelector('[data-capability-state="stale"]')).toBeTruthy(); api.getWorkflowPackSnapshot.mockResolvedValueOnce({ snapshot: { ...snapshot(), revision: 2, tasks: [] } }); await render({ otherMutationBlocked: false, domainRevision: 2 }); expect(host.textContent).toContain("No named tasks are configured");
});
