import { formatWorkflowSchedule } from "../lib/workflowPackClient";
import WorkflowConfigurationComparison from "./WorkflowConfigurationComparison";
import { useEffect, useRef, useState } from "react";
import { applyEventWorkflowCommand, createWorkflowRequestId, getEventWorkflowSnapshot, isDefinitiveWorkflowError, previewEventWorkflowMigration, readPendingWorkflowCommand, resetDefinitiveWorkflowCommand } from "../lib/tenantWorkflowClient";
const BLOCKS = new Set(["submitting", "uncertain", "reconciliation", "error", "recovery"]);
function State({ state, children }) { const props = { "data-capability-id": "event-workflow-coordination" }; switch (state) {
  case "loading": return <div {...props} data-capability-state="loading">{children}</div>; case "empty": return <div {...props} data-capability-state="empty">{children}</div>; case "success": return <div {...props} data-capability-state="success">{children}</div>; case "stale": return <div {...props} data-capability-state="stale">{children}</div>; case "partial": return <div {...props} data-capability-state="partial">{children}</div>; case "error": return <div {...props} data-capability-state="error">{children}</div>; case "recovery": return <div {...props} data-capability-state="recovery">{children}</div>; case "submitting": return <div {...props} data-capability-state="submitting">{children}</div>; case "uncertain": return <div {...props} data-capability-state="uncertain">{children}</div>; case "reconciliation": return <div {...props} data-capability-state="reconciliation">{children}</div>; case "receipt": return <div {...props} data-capability-state="receipt">{children}</div>; default: return <div {...props} data-capability-state="ready">{children}</div>;
} }
const words = (value) => String(value || "").replaceAll("_", " ");
const money = (cents) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
export default function EventWorkflowPolicyPanel(props) { return <Policy key={JSON.stringify([props.organizationId, props.quoteId, props.principalId, props.role, props.enabled, props.source, props.sourceVersionId, props.acceptanceReceiptId])} {...props} />; }
function Policy({ organizationId, quoteId, principalId, role, source, enabled, sourceVersionId, acceptanceReceiptId, phaseSnapshot, phaseReadState, otherMutationBlocked = false, onWorkflowMutationBlockedChange, onInitializationEligibilityChange }) {
  const eligible = enabled === true && source === "firebase" && ["admin", "sales"].includes(role) && Boolean(organizationId && quoteId && principalId && sourceVersionId && acceptanceReceiptId); const scope = { organizationId, quoteId, principalId };
  const [pending] = useState(() => eligible ? readPendingWorkflowCommand(scope) : null), [read, setRead] = useState({ state: "loading", snapshot: null, error: "" }), [mutation, setMutation] = useState(pending ? { state: pending.definitive ? "error" : "uncertain", command: pending.command, error: "The original coordination request still needs review." } : { state: "ready" });
  const [selection, setSelection] = useState(null), [note, setNote] = useState(""), [migration, setMigration] = useState(null), [confirmation, setConfirmation] = useState("");
  const mounted = useRef(true), sequence = useRef(0), inFlight = useRef(false), editor = useRef(null), outcome = useRef(null), focusRequested = useRef(false), previousMutation = useRef(mutation.state), priorPhase = useRef(phaseSnapshot?.revision), priorOtherMutation = useRef(otherMutationBlocked);
  const blocked = BLOCKS.has(mutation.state), busy = ["submitting", "reconciliation"].includes(mutation.state);
  useEffect(() => { onWorkflowMutationBlockedChange?.(blocked); }, [blocked, onWorkflowMutationBlockedChange]);
  useEffect(() => { onInitializationEligibilityChange?.(read.state === "empty" && read.snapshot?.initializationEligibility?.eligible === true); }, [read.state, read.snapshot, onInitializationEligibilityChange]);
  useEffect(() => { if (selection && focusRequested.current) { focusRequested.current = false; editor.current?.focus(); } }, [selection]);
  useEffect(() => { if (mutation.state !== previousMutation.current && ["receipt", "uncertain", "error", "recovery"].includes(mutation.state)) outcome.current?.focus(); previousMutation.current = mutation.state; }, [mutation.state]);
  const refresh = async () => { if (!eligible) return; const token = ++sequence.current; setRead((prior) => ({ ...prior, state: "loading", error: "" })); setMigration(null); setSelection(null); setNote(""); setConfirmation(""); try { const value = await getEventWorkflowSnapshot({ organizationId, quoteId }); if (!mounted.current || token !== sequence.current) return; if (value.snapshot.sourceVersionId !== sourceVersionId || value.snapshot.acceptanceReceiptId !== acceptanceReceiptId) throw Error("The accepted event source changed. Refresh Event Focus before continuing."); setRead({ state: value.snapshot.availability === "available" ? "success" : "empty", snapshot: value.snapshot, error: "" }); } catch (error) { if (mounted.current && token === sequence.current) setRead((prior) => ({ ...prior, state: prior.snapshot ? "stale" : "error", error: error.message })); } };
  useEffect(() => { mounted.current = true; void refresh(); return () => { mounted.current = false; sequence.current += 1; }; }, []);
  useEffect(() => { if (priorPhase.current !== phaseSnapshot?.revision && !blocked) void refresh(); priorPhase.current = phaseSnapshot?.revision; }, [phaseSnapshot?.revision, blocked]);
  useEffect(() => {
    if (otherMutationBlocked && !priorOtherMutation.current) { sequence.current += 1; setRead((prior) => prior.snapshot ? { ...prior, state: "stale", error: "Operational evidence is changing. Coordination obligations will refresh after the original request is resolved." } : prior); setMigration(null); setSelection(null); setNote(""); }
    if (!otherMutationBlocked && priorOtherMutation.current && !blocked) void refresh();
    priorOtherMutation.current = otherMutationBlocked;
  }, [otherMutationBlocked, blocked]);
  const matches = read.snapshot?.phaseRevision === phaseSnapshot?.revision && read.snapshot?.phaseReceiptId === phaseSnapshot?.lastReceiptId;
  const disabled = blocked || otherMutationBlocked || read.state !== "success" || phaseReadState !== "success" || !matches;
  const run = async (command, replay = false) => { if (inFlight.current) return; inFlight.current = true; sequence.current += 1; setMutation({ state: replay ? "reconciliation" : "submitting", command }); try { const value = await applyEventWorkflowCommand({ ...scope, ...command }); if (!mounted.current) return; setMutation({ state: "receipt", receipt: value.receipt }); setSelection(null); setNote(""); await refresh(); } catch (error) { if (mounted.current) setMutation({ state: error.code === "event-mutation-blocked" ? "ready" : isDefinitiveWorkflowError(error) ? "error" : "uncertain", command, error: error.message }); } finally { inFlight.current = false; } };
  const choose = (value) => { if (disabled) return; focusRequested.current = true; setSelection(value); setNote(""); setConfirmation(""); };
  const submit = (event) => { event.preventDefault(); if (disabled || !selection || !note.trim() || /[\u0000-\u001f\u007f]/u.test(note)) return; const command = { organizationId, quoteId, sourceVersionId, acceptanceReceiptId, requestId: createWorkflowRequestId(), expectedRevision: read.snapshot.revision, command: selection.command, note: note.trim() }; if (selection.taskKey) command.taskKey = selection.taskKey; if (selection.command === "review_ack") Object.assign(command, { actualsRevision: read.snapshot.actualsReview.actualsRef.revision, actualsReceiptId: read.snapshot.actualsReview.actualsRef.receiptId }); if (selection.command === "migrate") { if (!migration?.compatible || confirmation !== migration.confirmation) return; Object.assign(command, { previewDigest: migration.previewDigest, confirmation }); } void run(command); };
  const previewMigration = async () => { if (disabled || role !== "admin") return; const token = ++sequence.current; setRead((prior) => ({ ...prior, state: "loading", error: "" })); try { const result = await previewEventWorkflowMigration({ organizationId, quoteId, sourceVersionId, acceptanceReceiptId, expectedRevision: read.snapshot.revision, ...(read.snapshot.schemaVersion === 2 ? { schemaVersion: 2 } : {}) }); if (!mounted.current || token !== sequence.current) return; setMigration(result.preview); setRead((prior) => ({ ...prior, state: "success" })); if (result.preview.compatible) { focusRequested.current = true; setSelection({ command: "migrate" }); setNote(""); setConfirmation(""); } } catch (error) { if (mounted.current && token === sequence.current) setRead((prior) => ({ ...prior, state: "stale", error: error.message })); } };
  const reset = async () => { if (!resetDefinitiveWorkflowCommand(scope)) return; setMutation({ state: "recovery" }); setSelection(null); await refresh(); if (mounted.current) setMutation({ state: "ready" }); };
  if (!eligible) return <State state="recovery"><p>Event coordination requires an enabled connected workspace, authorized staff, and an exact accepted source.</p></State>;
  const snapshot = read.snapshot;
  return <section aria-label="Event coordination policy" data-capability-id="event-workflow-coordination" style={{ minWidth: 0, overflowWrap: "anywhere", marginBottom: "1rem" }}>
    <h3>Event coordination</h3><button className="ghost" type="button" disabled={blocked || otherMutationBlocked || read.state === "loading"} onClick={() => void refresh()}>Refresh coordination</button>
    <State state={read.state}>{read.state === "loading" && <p role="status">Loading event policy and tasks...</p>}{read.error && <p role="alert">{read.error}</p>}{snapshot?.availability === "not_yet_available" && <p>{snapshot.reasonCode === "legacy_unbound" ? "This earlier event has no workflow binding. No policy is applied automatically." : snapshot.initializationEligibility.eligible ? `Preparing this event will bind ${snapshot.nextDefinition.config.name} (${snapshot.nextDefinition.versionId}), ${snapshot.nextDefinition.seed ? "the source-controlled seed" : "the published tenant version"}.` : `New event initialization is blocked: ${words(snapshot.initializationEligibility.reasonCode)}. Review the tenant definition in Configuration Studio.`}</p>}</State>
    {snapshot?.availability === "available" && <><p><strong>{snapshot.definitionName}</strong> · {snapshot.definitionPin.versionId} · {words(snapshot.definitionSource)}.</p><p>Due {snapshot.schemaVersion === 2 ? formatWorkflowSchedule(snapshot.due) : snapshot.dueAtISO}. Escalation {snapshot.schemaVersion === 2 ? formatWorkflowSchedule(snapshot.escalation) : snapshot.escalationAtISO} to admin.</p><State state="partial"><p className="source-note">This pinned policy coordinates acknowledgements. Published event constraints can block governed phase or checkpoint commands; acknowledgements alone do not establish readiness or grant mutation or communication permissions.</p></State>
      <ul className="command-center-list" aria-label="Coordination tasks">{snapshot.tasks.map((task) => <li className="command-center-row" key={task.taskKey}><div><strong>{task.label}</strong><p>{task.instruction}</p><p className="source-note">Owner: {task.ownerRole} · {words(task.state)} · {task.urgency}. Due {snapshot.schemaVersion === 2 ? formatWorkflowSchedule(task.due) : task.dueAtISO}; escalation {snapshot.schemaVersion === 2 ? formatWorkflowSchedule(task.escalation) : task.escalationAtISO}.</p>{task.note && <p>Recorded note: {task.note}</p>}{task.communicationHandoff && <details><summary>Manual handoff: {task.communicationHandoff.label}</summary><p>{task.communicationHandoff.guidance}</p><p>No message is sent by this acknowledgement.</p></details>}</div>{(role === "admin" || task.ownerRole === role && snapshot.configuration.allowedRoles.includes(role)) && <button type="button" className="ghost" disabled={disabled} onClick={() => choose({ command: task.state === "acknowledged" ? "task_reopen" : "task_ack", taskKey: task.taskKey, label: task.label })}>{task.state === "acknowledged" ? "Reopen" : "Acknowledge"} {task.label}</button>}</li>)}</ul>{!snapshot.tasks.length && <p>No tasks are defined for this pinned version.</p>}
      <h4>Actuals review obligation</h4>{read.state !== "success" || otherMutationBlocked ? <p>Current actuals review is unavailable until coordination refresh completes.</p> : <><p>{words(snapshot.actualsReview.state)}{snapshot.actualsReview.thresholdCents !== null && ` · review threshold ${money(snapshot.actualsReview.thresholdCents)} USD`}. {snapshot.actualsReview.state === "not_yet_available" && "All three cost categories must be declared complete or not applicable before an exact actuals review reference is available."}</p>{snapshot.actualsReview.actualsRef && <p>Captured total {money(snapshot.actualsReview.actualsRef.totalCostCents)} USD · actuals revision {snapshot.actualsReview.actualsRef.revision}.</p>}{role === "admin" && snapshot.actualsReview.state === "required" && <button type="button" className="ghost" disabled={disabled} onClick={() => choose({ command: "review_ack", label: "Review complete actuals" })}>Acknowledge actuals review</button>}</>}
      <details><summary>Pinned policy and source</summary>{snapshot.schemaVersion === 2 && <WorkflowConfigurationComparison current={snapshot.configuration} proposed={null} />}<p>Source version: {snapshot.sourceVersionId}</p><p>Acceptance receipt: {snapshot.acceptanceReceiptId}</p><p>Definition published by {snapshot.publishedBy.role}: {snapshot.publishedBy.uid} at {snapshot.publishedAtISO}</p><p>Coordinator revision {snapshot.revision} · updated {snapshot.updatedAtISO}</p><p>Latest receipt: {snapshot.lastReceiptId}</p>{snapshot.comparisonPolicy ? <p>Declared comparison policy: labor {snapshot.comparisonPolicy.laborBasisPoints} basis points; purchasing {snapshot.comparisonPolicy.purchasingBasisPoints} basis points; minimum {money(snapshot.comparisonPolicy.minimumCents)} USD. Declared at {snapshot.comparisonPolicy.declaredAtISO}.</p> : <p>No comparison tolerance is declared.</p>}</details>
      {role === "admin" && <button type="button" className="ghost" disabled={disabled} onClick={() => void previewMigration()}>Preview migration to current published version</button>}
    </>}
    {migration && <section aria-label="Event workflow migration preview"><h4>Migration to {migration.targetDefinitionPin.versionId}</h4><p>{migration.compatible ? "Compatible migration. Existing task meaning and completed acknowledgements are preserved by the verified migration plan." : "Migration is incompatible."}</p><ul>{migration.reasons.map((reason) => <li key={reason}>{words(reason)}</li>)}</ul><p>Current pin: {migration.currentDefinitionPin.versionId}; target pin: {migration.targetDefinitionPin.versionId}.</p><WorkflowConfigurationComparison current={read.snapshot?.configuration} proposed={migration.targetConfiguration} /></section>}
    {selection && <form aria-label="Review coordination change" onSubmit={submit}><h4>{selection.label || "Migrate event workflow"}</h4><label className="field">Coordination reason<input ref={editor} maxLength={240} required disabled={disabled} value={note} onChange={(e) => setNote(e.target.value)} /></label>{selection.command === "migrate" && migration && <><p>Type exactly: <strong>{migration.confirmation}</strong></p><label className="field">Migration confirmation<input value={confirmation} disabled={disabled} onChange={(e) => setConfirmation(e.target.value)} /></label></>}<button type="submit" className="cta" disabled={disabled || !note.trim() || selection.command === "migrate" && confirmation !== migration?.confirmation}>Record coordination change</button><button type="button" className="ghost" disabled={blocked} onClick={() => { setSelection(null); setMigration(null); }}>Keep current coordination</button></form>}
    <div ref={outcome} tabIndex={-1} role="group" aria-label="Coordination request outcome"><State state={mutation.state}>{mutation.error && <p role="alert">{mutation.error}</p>}{busy && <p role="status">{mutation.state === "reconciliation" ? "Checking the original coordination request..." : "Recording coordination change..."}</p>}{mutation.state === "uncertain" && <><p>Keep the original request unchanged until its outcome is confirmed.</p><button type="button" className="cta" onClick={() => void run(mutation.command, true)}>Check original coordination request</button></>}{mutation.state === "error" && <button type="button" className="ghost" onClick={() => void reset()}>Refresh and review coordination</button>}{mutation.state === "recovery" && <p>Refreshing current workflow before another change.</p>}{mutation.receipt && <p role="status">Coordination {words(mutation.receipt.command)} recorded. Receipt: {mutation.receipt.receiptId}.</p>}</State></div>
  </section>;
}
