import "./attendanceWorkflowPresentation.css";
import WorkflowPackPolicyPanel from "./WorkflowPackPolicyPanel";
import { useEffect, useRef, useState } from "react";
import { applyQuoteAttendanceCommand, createAttendanceRequestId, getQuoteAttendance, isDefinitiveAttendanceError, readPendingAttendanceCommand, resetDefinitiveAttendanceCommand, submitQuoteAttendanceResponse } from "../lib/quoteAttendanceClient";
const BLOCKED = new Set(["submitting", "uncertain", "reconciliation", "error", "recovery"]);
function State({ state, portal, children }) { const props = { "data-capability-id": portal ? "portal-final-guest-count" : "final-guest-count" }; switch (state) {
  case "loading": return <div {...props} data-capability-state="loading">{children}</div>; case "empty": return <div {...props} data-capability-state="empty">{children}</div>; case "success": return <div {...props} data-capability-state="success">{children}</div>; case "stale": return <div {...props} data-capability-state="stale">{children}</div>; case "partial": return <div {...props} data-capability-state="partial">{children}</div>; case "error": return <div {...props} data-capability-state="error">{children}</div>; case "recovery": return <div {...props} data-capability-state="recovery">{children}</div>; case "submitting": return <div {...props} data-capability-state="submitting">{children}</div>; case "uncertain": return <div {...props} data-capability-state="uncertain">{children}</div>; case "reconciliation": return <div {...props} data-capability-state="reconciliation">{children}</div>; case "receipt": return <div {...props} data-capability-state="receipt">{children}</div>; default: return <div {...props} data-capability-state="ready">{children}</div>;
} }
export default function QuoteAttendancePanel(props) { return <div data-capability-id="final-guest-count"><AttendanceInteraction key={JSON.stringify([props.organizationId, props.quoteId, props.principalId, props.role, props.sourceVersionId, props.acceptanceReceiptId, props.enabled, props.source])} {...props} /></div>; }
export function AttendanceInteraction({ portal = false, organizationId, quoteId, principalId, role, enabled, source, sourceVersionId, acceptanceReceiptId, portalKey, expectedSourceVersionId, expectedPortalIssuedAtISO, onStageCommercialChange }) {
  const eligible = enabled === true && (portal ? Boolean(portalKey && expectedSourceVersionId && expectedPortalIssuedAtISO) : source === "firebase" && ["admin", "sales"].includes(role) && Boolean(organizationId && quoteId && principalId && sourceVersionId && acceptanceReceiptId));
  const scope = portal ? { accessMode: "portal", portalKey } : { accessMode: "staff", organizationId, quoteId, principalId };
  const [original] = useState(() => eligible ? readPendingAttendanceCommand(scope) : null), [read, setRead] = useState({ state: "loading", snapshot: null, error: "" }), [mutation, setMutation] = useState(original ? { state: original.definitive ? "error" : "uncertain", command: original.command, error: "The original attendance request needs review." } : { state: "ready" });
  const [editing, setEditing] = useState(false), [count, setCount] = useState(""), [note, setNote] = useState(""), [handoff, setHandoff] = useState("");
  const mounted = useRef(true), sequence = useRef(0), inFlight = useRef(false), editor = useRef(null), outcome = useRef(null), previousMutation = useRef(mutation.state), focusEditor = useRef(false);
  const blocked = BLOCKED.has(mutation.state), busy = ["submitting", "reconciliation"].includes(mutation.state), s = read.snapshot;
  const refresh = async () => { if (!eligible) return; const token = ++sequence.current; setRead((prior) => ({ ...prior, state: "loading", error: "" })); setEditing(false); setHandoff(""); try { const value = await getQuoteAttendance(scope); if (!mounted.current || token !== sequence.current) return; if (value.snapshot.sourceVersionId !== (portal ? expectedSourceVersionId : sourceVersionId) || !portal && value.snapshot.acceptanceReceiptId !== acceptanceReceiptId) throw Error("The accepted event source changed. Reopen the current event before continuing."); setRead({ state: value.snapshot.availability === "available" ? "success" : "empty", snapshot: value.snapshot, error: "" }); } catch (error) { if (mounted.current && token === sequence.current) setRead((prior) => ({ ...prior, state: prior.snapshot ? "stale" : "error", error: error.message })); } };
  useEffect(() => { mounted.current = true; void refresh(); return () => { mounted.current = false; sequence.current += 1; }; }, []);
  useEffect(() => { if (editing && focusEditor.current) { focusEditor.current = false; editor.current?.focus(); } }, [editing]);
  useEffect(() => { if (previousMutation.current !== mutation.state && ["receipt", "uncertain", "error", "recovery"].includes(mutation.state)) outcome.current?.focus(); previousMutation.current = mutation.state; }, [mutation.state]);
  const disabled = blocked || !["empty", "success"].includes(read.state);
  const run = async (command, replay = false) => { if (inFlight.current) return; inFlight.current = true; sequence.current += 1; setMutation({ state: replay ? "reconciliation" : "submitting", command }); setHandoff(""); try { const result = await (portal ? submitQuoteAttendanceResponse(command) : applyQuoteAttendanceCommand({ ...command, principalId })); if (!mounted.current) return; setMutation({ state: "receipt", receipt: result.receipt }); setEditing(false); await refresh(); } catch (error) { if (mounted.current) setMutation({ state: isDefinitiveAttendanceError(error) ? "error" : "uncertain", command, error: error.message }); } finally { inFlight.current = false; } };
  const staffCommand = (command, fields = {}) => ({ organizationId, quoteId, sourceVersionId, acceptanceReceiptId, requestId: createAttendanceRequestId(), expectedAttendanceRevision: s.revision, command, ...fields });
  const chooseResponse = () => { if (disabled || !s?.request) return; focusEditor.current = true; setEditing(true); setCount(""); setNote(""); };
  const validCount = /^\d{1,3}$/u.test(count) && Number(count) >= 1 && Number(count) <= 400;
  const submit = (event) => { event.preventDefault(); if (disabled || !s?.request || !validCount || !portal && !note.trim()) return; const fields = { confirmationRequestId: s.request.requestReceiptId, count: Number(count) }; void run(portal ? { portalKey, expectedSourceVersionId, expectedPortalIssuedAtISO, expectedAttendanceRevision: s.revision, requestId: createAttendanceRequestId(), ...fields } : staffCommand("record_response", { ...fields, note: note.trim() })); };
  const reset = async () => { if (!resetDefinitiveAttendanceCommand(scope)) return; setMutation({ state: "recovery" }); await refresh(); if (mounted.current) setMutation({ state: "ready" }); };
  const stage = async () => { if (disabled || !s?.latestResponse || !onStageCommercialChange) return; setHandoff("Opening the exact commercial review..."); try { const result = await onStageCommercialChange({ organizationId, quoteId, sourceVersionId, acceptanceReceiptId, submissionReceiptId: s.latestResponse.submissionReceiptId, count: s.latestResponse.count }); if (result?.status === "cancelled" || result?.status === "recovery" || result?.ok === false) throw Error(result.reason || "The commercial review did not open. The response remains recorded."); if (mounted.current) setHandoff("Count staged for commercial review. No final count has been applied."); } catch (error) { if (mounted.current) setHandoff(error.message || "Commercial review could not be opened. The response remains recorded."); } };
  if (!eligible) return <State portal={portal} state="recovery"><p>{portal ? "Final guest-count response is unavailable from this portal." : "Final guest count requires an enabled connected workspace, authorized staff and an exact accepted event."}</p></State>;
  return <section className="attendance-workflow-panel" aria-label={portal ? "Your final guest count" : "Final guest-count evidence"}>
    <header className="attendance-workflow-panel__head"><div><p className="eyebrow">{portal ? "Your event" : "Guest count review"}</p><h3>{portal ? "Your final guest count" : "Confirm the number before the event"}</h3></div><button type="button" className="ghost compact" disabled={blocked || read.state === "loading"} onClick={() => void refresh()}>Refresh count request</button></header>
    {s && <p className="attendance-workflow-panel__count">Currently priced for <strong>{s.pricedCount} guests</strong>.</p>}
    <State state={read.state} portal={portal}>{read.state === "loading" && <p role="status">Loading the current count request...</p>}{read.error && <p role="alert">{read.error}</p>}{read.state === "empty" && <p>No final-count request has been recorded.</p>}{s?.request && <p className="attendance-workflow-panel__due">Final count requested · due {s.request.dueDate}.</p>}{s?.latestResponse && <p>{portal ? "You submitted" : s.latestResponse.sourceType === "customer_portal" ? "Portal response" : "Staff-recorded response"}: <strong>{s.latestResponse.count} guests</strong>. {portal ? s.latestResponse.count === s.pricedCount ? "Your response matches the number currently priced. Your caterer still needs to review it." : "Your caterer will review this count and any change to the price." : s.latestResponse.count === s.pricedCount ? "The number matches the quote; final application still requires your price and count review." : "Review the price impact before applying this change."}</p>}{read.state === "success" && portal && !s?.latestResponse && <p>No current response from this issued portal is available.</p>}</State>
    {s && <State state="partial" portal={portal}><p className="source-note">{portal ? "Submitting your count does not change the accepted price or booking. Your caterer will review it." : "The quote stays unchanged until you review and apply a supplied count. Recording a request sends no message."}</p></State>}
    <div className="attendance-workflow-panel__actions">
      {!portal && !s?.request && <button type="button" className="cta" disabled={disabled} onClick={() => void run(staffCommand("request_confirmation"))}>Request final guest count</button>}
      {!portal && s?.latestResponse && onStageCommercialChange && <button type="button" className="cta" disabled={disabled} onClick={() => void stage()}>Review and apply supplied count</button>}
      {s?.request && <button type="button" className={!portal && s?.latestResponse && onStageCommercialChange ? "ghost" : "cta"} disabled={disabled} onClick={chooseResponse}>{portal ? "Submit guest count" : "Record supplied guest count"}</button>}
    </div>
    {!portal && s?.request && <details className="attendance-workflow-panel__secondary"><summary>Start another count request</summary><p>Keep the current response unless you need to ask for a new count. This records a new request; it does not contact the customer.</p><button type="button" className="ghost" disabled={disabled} onClick={() => void run(staffCommand("request_confirmation"))}>Record a new count request</button></details>}
    {handoff && <p role="status">{handoff}</p>}
    {editing && <form aria-label={portal ? "Submit final guest count" : "Record guest-count response"} onSubmit={submit}><label className="field">Guest count<input ref={editor} inputMode="numeric" pattern="[0-9]{1,3}" min={1} max={400} maxLength={3} required disabled={disabled} value={count} onChange={(event) => setCount(event.target.value)} /></label><p className="source-note">Enter a whole number from 1 to 400.</p>{!portal && <label className="field">Source of the supplied count<textarea rows={2} maxLength={240} required disabled={disabled} value={note} onChange={(event) => setNote(event.target.value)} /></label>}<button type="submit" className="cta" disabled={disabled || !validCount || !portal && !note.trim()}>{portal ? "Record my response" : "Save staff-recorded response"}</button><button type="button" className="ghost" disabled={blocked} onClick={() => setEditing(false)}>Keep current response</button></form>}
    <div className="attendance-workflow-panel__outcome" ref={outcome} tabIndex={-1} role="group" aria-label={portal ? "Guest-count response outcome" : "Attendance request outcome"}><State state={mutation.state} portal={portal}>{busy && <p role="status">{mutation.state === "reconciliation" ? "Checking the unchanged original request..." : "Recording attendance evidence..."}</p>}{mutation.error && <p role="alert">{mutation.error}</p>}{mutation.state === "uncertain" && <><p>No outcome is assumed. Keep this request unchanged until its receipt is checked.</p><button type="button" className="cta" onClick={() => void run(mutation.command, true)}>Check original attendance request</button></>}{mutation.state === "error" && <button type="button" className="ghost" onClick={() => void reset()}>Refresh and review attendance</button>}{mutation.state === "recovery" && <p>Refreshing current evidence before another request.</p>}{mutation.receipt && <p role="status">{mutation.receipt.command === "request_confirmation" ? "Count request recorded. Contact the customer separately to ask for their number." : "Guest-count response recorded. No final count or price change has been applied."}</p>}</State></div>
    {!portal && s && <WorkflowPackPolicyPanel organizationId={organizationId} quoteId={quoteId} principalId={principalId} role={role} enabled={enabled} source={source} workflowKind="final_guest_count" sourceVersionId={sourceVersionId} sourceReceiptId={acceptanceReceiptId} domainRevision={s.revision} otherMutationBlocked={blocked} />}
    {!portal && s && <details className="attendance-workflow-panel__evidence"><summary>Count source and latest receipt</summary>{s.request && <p>Request recorded {s.request.requestedAtISO}.</p>}{s.latestResponse && <p>Response recorded {s.latestResponse.submittedAtISO}.</p>}<p>Priced source: {s.sourceVersionId}</p><p>Acceptance receipt: {s.acceptanceReceiptId}</p><p>Attendance revision: {s.revision}. Latest receipt: {s.lastReceiptId || "None"}.</p><p>Only the latest request and response are shown. Earlier immutable receipts remain retained.</p></details>}
  </section>;
}
