import WorkflowConfigurationComparison from "./WorkflowConfigurationComparison";
import { useCallback, useEffect, useRef, useState } from "react";
import { applyWorkflowDefinitionCommand, CHECKPOINT_CODES, createWorkflowRequestId, WORKFLOW_KINDS, getWorkflowConfiguration, isDefinitiveWorkflowError, normalizeWorkflowConfig, previewWorkflowDefinition, readPendingWorkflowCommand, resetDefinitiveWorkflowCommand, workflowMoneyInputToCents } from "../lib/tenantWorkflowClient";
import "./tenantWorkflowStudio.css";

const LABELS = { event_execution: "Event execution", quote_review: "Quote approval", final_guest_count: "Final guest count", closeout_follow_up: "Closeout follow-up" };
const GUIDES = {
  quote_review: { outcome: "Review changes with confidence", description: "Give price changes a clear owner and a consistent approval check before they reach your customer.", anchor: "the price-change review", task: "Review the proposed price change", instruction: "Review the proposed total and its effect on the customer agreement before approving the change." },
  final_guest_count: { outcome: "Give the kitchen a confirmed count", description: "Make it clear who follows up on the guest count. Customer responses stay separate from the priced agreement until reviewed.", anchor: "the guest-count deadline", task: "Review the final guest count", instruction: "Check the customer response against the priced count. Review any change before applying it to the agreement." },
  event_execution: { outcome: "Keep event day moving", description: "Give your team a shared checklist and agree on what must be ready before service starts and the event closes.", anchor: "the event's scheduled start", task: "Review the event brief", instruction: "Check the accepted event details and brief the team before service begins." },
  closeout_follow_up: { outcome: "Follow through after the event", description: "Assign the post-event review so open questions and the next customer conversation have a clear owner.", anchor: "the follow-up due date", task: "Review the event and next steps", instruction: "Review the recorded event outcome and unresolved items before planning the next customer conversation." }
};
const CHECKPOINT_LABELS = { venue_access: "Venue access", team_briefing: "Team briefing", service_handoff: "Service handoff", pack_down: "Pack down" };
const checkpointLabel = value => CHECKPOINT_LABELS[value] || value.replaceAll("_", " ");
const roleLabel = value => value === "admin" ? "Administrator" : "Sales";
const duration = value => value === 0 ? "At the scheduled time" : value % 1440 === 0 ? `${value / 1440} day${value === 1440 ? "" : "s"} later` : value % 60 === 0 ? `${value / 60} hour${value === 60 ? "" : "s"} later` : `${value} minutes later`;
const defaultPolicy = kind => kind === "quote_review" ? { approval: { basis: "absolute_total_delta_cents", thresholdCents: null, allowedRoles: ["admin", "sales"] } } : kind === "event_execution" ? { phaseConstraints: { in_progress: { requiredCheckpoints: [], blockOpenUrgentIssues: false }, completed: { requiredCheckpoints: [], blockOpenUrgentIssues: false } }, checkpointPrerequisites: Object.fromEntries(CHECKPOINT_CODES.map(code => [code, []])) } : { responsibleRoles: ["admin", "sales"], ...(kind === "closeout_follow_up" ? { followUpOffsetDays: 0 } : {}) };
const blankConfig = kind => ({ schemaVersion: 2, workflowKind: kind, name: LABELS[kind], allowedRoles: ["admin", "sales"], actualsReviewThresholdCents: null, comparisonPolicy: null, duePolicy: { offsetMinutes: 0 }, escalationPolicy: { afterMinutes: 60, role: "admin" }, taskTemplates: [], packPolicy: defaultPolicy(kind) });
function nextTaskKey(tasks) { let index = 1; while (tasks.some(task => task.taskKey === `task_${index}`)) index += 1; return `task_${index}`; }
function Check({ children, ...props }) { return <label className="workflow-studio__check"><input type="checkbox" {...props} /><span>{children}</span></label>; }
function Timing({ label, value, onChange, ariaLabel }) {
  const [unit, setUnit] = useState(() => value > 0 && value % 1440 === 0 ? 1440 : value > 0 && value % 60 === 0 ? 60 : 1);
  return <div className="workflow-studio__timing"><label className="field">{label}<input aria-label={ariaLabel || label} type="number" min={0} max={43200 / unit} step="any" required value={value === "" ? "" : Number((value / unit).toFixed(6))} onChange={event => onChange(event.target.value === "" ? "" : Number((Number(event.target.value) * unit).toFixed(6)))} /></label><label className="field"><span className="sr-only">{label} unit</span><select aria-label={`${ariaLabel || label} unit`} value={unit} onChange={event => setUnit(Number(event.target.value))}><option value={1}>Minutes</option><option value={60}>Hours</option><option value={1440}>Days</option></select></label></div>;
}
function PackPolicyEditor({ draft, update }) {
  const policy = draft.packPolicy;
  if (!policy) return <div className="workflow-studio__note"><p>The standard event checks are in use. You can add requirements before service starts or the event closes.</p><button type="button" className="ghost" onClick={() => { update("schemaVersion", 2); update("packPolicy", defaultPolicy("event_execution")); }}>Customize event checks</button></div>;
  const roleValue = policy.approval?.allowedRoles || policy.responsibleRoles;
  const setRole = allowed => update("packPolicy", policy.approval ? { approval: { ...policy.approval, allowedRoles: allowed } } : { ...policy, responsibleRoles: allowed });
  const toggle = (list, code, checked) => checked ? [...list, code] : list.filter(item => item !== code);
  return <div className="workflow-studio__policy">
    {roleValue && <><Check checked={roleValue.includes("sales")} onChange={event => setRole(event.target.checked ? ["admin", "sales"] : ["admin"])}>Sales may take responsibility for this work</Check>{roleValue.some(role => !draft.allowedRoles.includes(role)) && <p className="error-note" role="alert">Allow sales to complete tasks below, or remove sales responsibility before saving.</p>}</>}
    {policy.approval && <><p>Administrator approval is still required when a change affects linked work. You can also require approval based on the absolute total change.</p><Check checked={policy.approval.thresholdCents !== null} onChange={event => update("packPolicy", { approval: { ...policy.approval, thresholdCents: event.target.checked ? 0 : null } })}>Require approval at a declared amount</Check>{policy.approval.thresholdCents !== null && <label className="field">Approval threshold (USD)<input inputMode="decimal" required value={draft.approvalInput} onChange={event => update("approvalInput", event.target.value)} /></label>}<p className="source-note">An explicit $0 requires approval even when the total does not change. Leaving the threshold off adds no amount-based rule.</p></>}
    {draft.workflowKind === "closeout_follow_up" && <label className="field">Follow-up delay (calendar days)<input type="number" min={0} max={90} required value={policy.followUpOffsetDays} onChange={event => update("packPolicy", { ...policy, followUpOffsetDays: event.target.value === "" ? "" : Number(event.target.value) })} /><span className="source-note">Uses your business's calendar and event follow-up date.</span></label>}
    {policy.phaseConstraints && <><div className="workflow-studio__grid">{["in_progress", "completed"].map(phase => <fieldset className="workflow-studio__checks" key={phase}><legend>{phase === "in_progress" ? "Before service starts" : "Before the event closes"}</legend>{CHECKPOINT_CODES.map(code => <Check key={code} checked={policy.phaseConstraints[phase].requiredCheckpoints.includes(code)} onChange={event => update("packPolicy", { ...policy, phaseConstraints: { ...policy.phaseConstraints, [phase]: { ...policy.phaseConstraints[phase], requiredCheckpoints: toggle(policy.phaseConstraints[phase].requiredCheckpoints, code, event.target.checked) } } })}>{checkpointLabel(code)}</Check>)}<Check checked={policy.phaseConstraints[phase].blockOpenUrgentIssues} onChange={event => update("packPolicy", { ...policy, phaseConstraints: { ...policy.phaseConstraints, [phase]: { ...policy.phaseConstraints[phase], blockOpenUrgentIssues: event.target.checked } } })}>Resolve urgent issues first</Check></fieldset>)}</div><details className="workflow-studio__details"><summary>Set the order of individual checks</summary><div className="workflow-studio__grid">{CHECKPOINT_CODES.map(code => <fieldset className="workflow-studio__checks" key={code}><legend>Before {checkpointLabel(code).toLowerCase()}</legend>{CHECKPOINT_CODES.filter(other => other !== code).map(other => <Check key={other} checked={policy.checkpointPrerequisites[code].includes(other)} onChange={event => update("packPolicy", { ...policy, checkpointPrerequisites: { ...policy.checkpointPrerequisites, [code]: toggle(policy.checkpointPrerequisites[code], other, event.target.checked) } })}>{checkpointLabel(other)}</Check>)}</fieldset>)}</div><p className="source-note">Each check needs a clear starting point. Circular dependencies cannot be saved.</p></details></>}
  </div>;
}
function TaskEditor({ task, index, draft, updateTask, removeTask }) {
  const [expanded, setExpanded] = useState(!task.label);
  const invalidOwner = !draft.allowedRoles.includes(task.ownerRole);
  return <details className="workflow-studio__task" open={expanded || invalidOwner} onToggle={event => setExpanded(event.currentTarget.open)}><summary><span className="workflow-studio__number" aria-hidden="true">{String(index + 1).padStart(2, "0")}</span><span><strong>{task.label || "New task"}</strong><span className="workflow-studio__task-meta">{roleLabel(task.ownerRole)} · {duration(task.dueOffsetMinutes)}{invalidOwner ? " · Owner needs review" : ""}</span></span><span className="workflow-studio__edit">Edit</span></summary><div className="workflow-studio__task-body"><label className="field">What needs to happen?<input aria-label={`Task ${index + 1} label`} required maxLength={80} value={task.label} onChange={event => updateTask(index, "label", event.target.value)} /></label><label className="field">Instructions for the team<textarea aria-label={`Task ${index + 1} instruction`} maxLength={240} rows={2} value={task.instruction} onChange={event => updateTask(index, "instruction", event.target.value)} /></label><div className="workflow-studio__grid"><label className="field">Who owns it?<select aria-label={`Task ${index + 1} owner`} value={task.ownerRole} onChange={event => updateTask(index, "ownerRole", event.target.value)}>{invalidOwner && <option value={task.ownerRole}>{roleLabel(task.ownerRole)} — permission removed</option>}{draft.allowedRoles.map(role => <option key={role} value={role}>{roleLabel(role)}</option>)}</select></label><Timing label="Due after the scheduled start" ariaLabel={`Task ${index + 1} due offset`} value={task.dueOffsetMinutes} onChange={value => updateTask(index, "dueOffsetMinutes", value)} /></div>{invalidOwner && <p role="alert" className="error-note">Choose an allowed owner for this task or restore sales permission before saving.</p>}<details className="workflow-studio__details"><summary>Task reference and handoff</summary><label className="field">Task reference<input aria-label={`Task ${index + 1} key`} required maxLength={48} pattern="[a-z][a-z0-9_]{0,47}" value={task.taskKey} onChange={event => updateTask(index, "taskKey", event.target.value)} /><span className="source-note">A stable reference used to match this task across versions.</span></label><label className="field">Manual handoff guide<select aria-label={`Task ${index + 1} handoff`} value={task.communicationTemplateRef || ""} onChange={event => updateTask(index, "communicationTemplateRef", event.target.value || null)}><option value="">No guide</option><option value="internal_event_brief_v1">Internal event brief</option><option value="post_event_review_v1">Post-event review</option></select><span className="source-note">A guide for the team. Selecting it does not send a message.</span></label></details><button className="ghost" type="button" onClick={removeTask}>Remove task {index + 1}</button></div></details>;
}
const BLOCKED = new Set(["submitting", "uncertain", "reconciliation", "error", "recovery"]);
function State({ state, children }) { const props = { "data-capability-id": "tenant-workflow-configuration" }; switch (state) {
  case "loading": return <div {...props} data-capability-state="loading">{children}</div>; case "empty": return <div {...props} data-capability-state="empty">{children}</div>; case "success": return <div {...props} data-capability-state="success">{children}</div>; case "stale": return <div {...props} data-capability-state="stale">{children}</div>; case "partial": return <div {...props} data-capability-state="partial">{children}</div>; case "error": return <div {...props} data-capability-state="error">{children}</div>; case "recovery": return <div {...props} data-capability-state="recovery">{children}</div>; case "submitting": return <div {...props} data-capability-state="submitting">{children}</div>; case "uncertain": return <div {...props} data-capability-state="uncertain">{children}</div>; case "reconciliation": return <div {...props} data-capability-state="reconciliation">{children}</div>; case "receipt": return <div {...props} data-capability-state="receipt">{children}</div>; default: return <div {...props} data-capability-state="ready">{children}</div>;
} }
const moneyInput = (cents) => cents === null ? "" : (cents / 100).toFixed(2);
const toDraft = (config) => config ? { ...structuredClone(config), thresholdInput: moneyInput(config.actualsReviewThresholdCents), minimumInput: moneyInput(config.comparisonPolicy?.minimumCents ?? null), approvalInput: moneyInput(config.packPolicy?.approval?.thresholdCents ?? null) } : null;
function configOf(draft) { const { thresholdInput, minimumInput, approvalInput, ...config } = draft; if (config.actualsReviewThresholdCents !== null) { config.actualsReviewThresholdCents = workflowMoneyInputToCents(thresholdInput); if (config.actualsReviewThresholdCents === null) throw Error("Enter an explicit review threshold in USD."); } if (config.comparisonPolicy) { config.comparisonPolicy = { ...config.comparisonPolicy, minimumCents: workflowMoneyInputToCents(minimumInput) }; if (config.comparisonPolicy.minimumCents === null) throw Error("Enter an explicit comparison minimum in USD."); } if (config.packPolicy?.approval?.thresholdCents !== null && config.packPolicy?.approval) { config.packPolicy = { approval: { ...config.packPolicy.approval, thresholdCents: workflowMoneyInputToCents(approvalInput) } }; if (config.packPolicy.approval.thresholdCents === null) throw Error("Enter an explicit approval threshold in USD."); } return normalizeWorkflowConfig(config); }
export default function TenantWorkflowConfigurationStudio(props) {
  const [kind, setKind] = useState("event_execution");
  return <Studio key={JSON.stringify([props.organizationId, props.principalId, props.role, props.enabled, props.source, kind])} {...props} workflowKind={kind} onSelectKind={setKind} />;
}
function Studio({ workflowKind: KIND, onSelectKind, organizationId, principalId, role, enabled, source, open = true, onClose, onDismissGuardChange, onInteractionStateChange }) {
  const eligible = enabled === true && source === "firebase" && role === "admin" && Boolean(organizationId && principalId); const scope = { organizationId, principalId, workflowKind: KIND };
  const [pending] = useState(() => eligible ? readPendingWorkflowCommand(scope, "definition") : null);
  const [read, setRead] = useState({ state: "loading", snapshot: null, error: "" }), [draft, setDraft] = useState(null), [base, setBase] = useState(null), [preview, setPreview] = useState(null), [confirmation, setConfirmation] = useState(""), [retireReason, setRetireReason] = useState(""), [inputError, setInputError] = useState("");
  const [mutation, setMutation] = useState(pending ? { state: pending.definitive ? "error" : "uncertain", command: pending.command, error: `The original configuration request for ${pending.command.workflowKind.replaceAll("_", " ")} needs review.` } : { state: "ready" });
  const mounted = useRef(true), sequence = useRef(0), inFlight = useRef(false), outcome = useRef(null), heading = useRef(null), previousMutation = useRef(mutation.state);
  const blocked = BLOCKED.has(mutation.state), dirty = Boolean(draft && JSON.stringify(draft) !== JSON.stringify(base)), busy = blocked || read.state === "loading";
  const load = async () => { if (!eligible) return; const token = ++sequence.current; setRead((prior) => ({ ...prior, state: "loading", error: "" })); setPreview(null); setConfirmation(""); try { const result = await getWorkflowConfiguration({ organizationId, workflowKind: KIND }); if (!mounted.current || token !== sequence.current) return; const s = result.snapshot; setRead({ state: s.availability === "schema_drift" ? "recovery" : ["seed", "unpublished"].includes(s.state) ? "empty" : "success", snapshot: s, error: "" }); const value = toDraft(s.draft || s.activeVersion?.config || blankConfig(KIND)); setDraft(value); setBase(value); } catch (error) { if (mounted.current && token === sequence.current) setRead((prior) => ({ ...prior, state: prior.snapshot ? "stale" : "error", error: error.message })); } };
  useEffect(() => { mounted.current = true; heading.current?.focus(); void load(); return () => { mounted.current = false; sequence.current += 1; }; }, []);
  useEffect(() => { if (mutation.state !== previousMutation.current && ["receipt", "uncertain", "error", "recovery"].includes(mutation.state)) outcome.current?.focus(); previousMutation.current = mutation.state; }, [mutation.state]);
  const requestDismiss = useCallback((reason = "close", continuation = null) => { if (blocked) { setInputError("Check the original configuration request before leaving Studio."); return { status: "blocked", reason: "unresolved", trigger: reason }; } if (dirty && !window.confirm("Discard unsaved workflow configuration changes?")) return { status: "guarded", reason: "dirty", trigger: reason }; onInteractionStateChange?.({ dirty: false, busy: false }); continuation?.(); return { status: "dismissed", trigger: reason }; }, [blocked, dirty, onInteractionStateChange]);
  useEffect(() => { onInteractionStateChange?.({ dirty, busy: blocked }); }, [dirty, blocked, onInteractionStateChange]);
  useEffect(() => { onDismissGuardChange?.(open ? { modelId: "workflow-studio-navigation-guard-v1", open: true, dirty, busy: blocked, requestDismiss } : null); return () => onDismissGuardChange?.(null); }, [open, dirty, blocked, requestDismiss, onDismissGuardChange]);
  useEffect(() => { if (!dirty && !blocked) return; const warn = (event) => { event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty, blocked]);
  const run = async (command, reconcile = false) => { if (inFlight.current) return; inFlight.current = true; sequence.current += 1; setMutation({ state: reconcile ? "reconciliation" : "submitting", command }); setInputError(""); try { const result = await applyWorkflowDefinitionCommand({ ...scope, ...command }); if (!mounted.current) return; setMutation({ state: "receipt", receipt: result.receipt }); await load(); } catch (error) { if (mounted.current) setMutation({ state: isDefinitiveWorkflowError(error) ? "error" : "uncertain", command, error: error.message }); } finally { inFlight.current = false; } };
  const command = (kind, fields) => ({ organizationId, workflowKind: KIND, requestId: createWorkflowRequestId(), expectedRevision: read.snapshot.revision, command: kind, ...fields });
  const disabled = blocked || !["empty", "success"].includes(read.state) || read.snapshot?.availability !== "available";
  const update = (field, value) => { setDraft((prior) => ({ ...prior, [field]: value })); setPreview(null); setConfirmation(""); setInputError(""); };
  const updateTask = (index, field, value) => update("taskTemplates", draft.taskTemplates.map((task, i) => i === index ? { ...task, [field]: value } : task));
  const save = (event) => { event.preventDefault(); if (disabled) return; try { void run(command("save_draft", { config: configOf(draft) })); } catch (error) { setInputError(error.message); } };
  const previewPublish = async () => { if (disabled || dirty || !read.snapshot?.draft) return; setRead((prior) => ({ ...prior, state: "loading", error: "" })); try { const result = await previewWorkflowDefinition({ organizationId, principalId, workflowKind: KIND, expectedRevision: read.snapshot.revision }); if (!mounted.current) return; if (result.preview.actor.uid !== principalId) throw Error("The publication preview belongs to a different administrator."); setPreview(result.preview); setRead((prior) => ({ ...prior, state: prior.snapshot.state === "seed" ? "empty" : "success" })); } catch (error) { if (mounted.current) setRead((prior) => ({ ...prior, state: "stale", error: error.message })); } };
  const reset = async () => { if (!resetDefinitiveWorkflowCommand(scope, "definition")) return; setMutation({ state: "recovery" }); await load(); if (mounted.current) setMutation({ state: "ready" }); };
  if (!eligible) return <State state="recovery"><p>Workflow Configuration Studio requires a connected, enabled workspace and administrator access.</p></State>;
  const guide = GUIDES[KIND];
  const status = read.snapshot?.state;
  const statusLabel = { seed: "Standard checklist", retired: "Paused for new work", unpublished: "Not yet published", published: "Published for new work" }[status];
  const addTask = suggested => update("taskTemplates", [...draft.taskTemplates, { taskKey: nextTaskKey(draft.taskTemplates), label: suggested ? guide.task : "", instruction: suggested ? guide.instruction : "", ownerRole: "admin", dueOffsetMinutes: 0, communicationTemplateRef: null }]);
  return <section className="workflow-studio" aria-label="Workflow Configuration Studio" data-capability-id="tenant-workflow-configuration" hidden={!open}>
    <header className="workflow-studio__header"><div><p className="workflow-studio__eyebrow">Team standards</p><h2 ref={heading} tabIndex={-1}>Business workflows</h2><p>Clear checks and handoffs, from the first quote to the next event.</p></div><button type="button" className="ghost" onClick={() => requestDismiss("close", onClose)}>Back to Library</button></header>
    <nav className="workflow-studio__choices" aria-label="Workflow pack">{WORKFLOW_KINDS.map((kind, index) => <button type="button" key={kind} data-workflow-kind={kind} aria-pressed={KIND === kind} disabled={blocked} onClick={() => { if (kind !== KIND) requestDismiss("switch-pack", () => onSelectKind(kind)); }}><span aria-hidden="true">{String(index + 1).padStart(2, "0")}</span>{LABELS[kind]}</button>)}</nav>
    <div className="workflow-studio__intro"><div><h3>{guide.outcome}</h3><p>{guide.description}</p></div>{statusLabel && <span className={`workflow-studio__status${status === "retired" ? " workflow-studio__status--paused" : ""}`}>{statusLabel}</span>}</div>
    <State state={read.state}>{read.state === "loading" && <p role="status">Loading workflow configuration...</p>}{read.error && <p className="error-note" role="alert">{read.error}</p>}{read.snapshot?.availability === "schema_drift" && <p className="warning-note">This saved format needs support before it can be edited or published.</p>}{read.snapshot?.availability === "available" && <div className="workflow-studio__scope"><p>{status === "retired" ? "Existing work keeps its saved rules. Review and publish a draft to start using this workflow again." : status === "seed" ? "The standard checklist is available now. Customize a draft when your team needs different checks." : status === "unpublished" ? "Build your checklist below, then review and publish it for new work." : "New work uses the published rules. Existing events keep the version they started with."}</p><button type="button" className="ghost" disabled={busy || dirty} onClick={() => void load()}>Refresh configuration</button></div>}</State>
    {draft && <form aria-label="Workflow definition draft" onSubmit={save} onInvalidCapture={event => { for (let parent = event.target.parentElement; parent; parent = parent.parentElement) if (parent.tagName === "DETAILS") parent.open = true; }}><fieldset className="workflow-studio__form" disabled={disabled}><legend className="sr-only">Draft configuration</legend>
      <section className="workflow-studio__section" aria-labelledby="workflow-team-checklist"><div className="workflow-studio__section-heading"><div><p className="workflow-studio__eyebrow">01 · The work</p><h3 id="workflow-team-checklist">Your team's checklist</h3></div><span>{draft.taskTemplates.length} of 12 tasks</span></div><label className="field workflow-studio__name">Workflow name<input maxLength={80} required value={draft.name} onChange={event => update("name", event.target.value)} /></label>
      <p className="source-note">Task timing starts from {guide.anchor}. Completing a task records the handoff; the event or quote action is recorded separately.</p>
      <div className="workflow-studio__tasks">{draft.taskTemplates.map((task, index) => <TaskEditor key={index} {...{ task, index, draft, updateTask }} removeTask={() => update("taskTemplates", draft.taskTemplates.filter((_, i) => i !== index))} />)}</div>
      {!draft.taskTemplates.length && <div className="workflow-studio__starter"><strong>Start with one clear handoff</strong><p>{guide.task}. You can tailor the owner, timing and instructions before saving.</p><button type="button" className="ghost" onClick={() => addTask(true)}>Use suggested checklist</button></div>}
      <button type="button" className="ghost" disabled={draft.taskTemplates.length >= 12} onClick={() => addTask(false)}>Add task</button>
      </section>
      <section className="workflow-studio__section" aria-labelledby="workflow-team-checks"><div className="workflow-studio__section-heading"><div><p className="workflow-studio__eyebrow">02 · The checks</p><h3 id="workflow-team-checks">What needs a review?</h3></div></div><PackPolicyEditor draft={draft} update={update} /></section>
      <details className="workflow-studio__settings"><summary><span><strong>Team access and timing</strong><span className="workflow-studio__task-meta">{draft.allowedRoles.map(roleLabel).join(" and ")} · Administrator follow-up {duration(draft.escalationPolicy.afterMinutes).toLowerCase()}</span></span></summary><div className="workflow-studio__settings-body"><Check checked={draft.allowedRoles.includes("sales")} onChange={event => update("allowedRoles", event.target.checked ? ["admin", "sales"] : ["admin"])}>Allow sales to complete assigned tasks</Check><p className="source-note">Event phases, checkpoints, issues and cost recording still require administrator access.</p><div className="workflow-studio__grid"><Timing label="Workflow due after scheduled start" value={draft.duePolicy.offsetMinutes} onChange={value => update("duePolicy", { offsetMinutes: value })} /><Timing label="Administrator follow-up after due" value={draft.escalationPolicy.afterMinutes} onChange={value => update("escalationPolicy", { afterMinutes: value, role: "admin" })} /></div><p className="source-note">The scheduled start is {guide.anchor}. These timings create due-work observations; they do not send reminders.</p></div></details>
      {KIND === "event_execution" && <details className="workflow-studio__settings"><summary><span><strong>Cost review and tolerances</strong><span className="workflow-studio__task-meta">Optional checks on recorded costs</span></span></summary><div className="workflow-studio__settings-body"><Check checked={draft.actualsReviewThresholdCents !== null} onChange={event => update("actualsReviewThresholdCents", event.target.checked ? 0 : null)}>Require review when complete actual costs meet a declared threshold</Check>{draft.actualsReviewThresholdCents !== null && <label className="field">Actuals review threshold (USD)<input inputMode="decimal" required value={draft.thresholdInput} onChange={event => update("thresholdInput", event.target.value)} /></label>}<Check checked={draft.comparisonPolicy !== null} onChange={event => update("comparisonPolicy", event.target.checked ? { laborBasisPoints: "", purchasingBasisPoints: "", minimumCents: 0 } : null)}>Set cost comparison tolerances</Check>{draft.comparisonPolicy && <><div className="workflow-studio__grid"><label className="field">Labor tolerance (basis points)<input type="number" required min={0} max={10000} value={draft.comparisonPolicy.laborBasisPoints} onChange={event => update("comparisonPolicy", { ...draft.comparisonPolicy, laborBasisPoints: event.target.value === "" ? "" : Number(event.target.value) })} /></label><label className="field">Purchasing tolerance (basis points)<input type="number" required min={0} max={10000} value={draft.comparisonPolicy.purchasingBasisPoints} onChange={event => update("comparisonPolicy", { ...draft.comparisonPolicy, purchasingBasisPoints: event.target.value === "" ? "" : Number(event.target.value) })} /></label></div><label className="field">Minimum comparison tolerance (USD)<input inputMode="decimal" required value={draft.minimumInput} onChange={event => update("minimumInput", event.target.value)} /></label><p className="source-note">100 basis points equals 1%. These values never change recorded costs or pricing.</p></>}</div></details>}
      <div className="workflow-studio__save"><p><strong>{dirty ? "Unsaved changes" : read.snapshot?.draft ? "Saved draft" : "Ready to customize"}</strong><span>Saving a draft does not change any live work.</span></p><button className="cta" type="submit" disabled={!dirty && Boolean(read.snapshot?.draft || read.snapshot?.activeVersion)}>Save workflow draft</button></div>
    </fieldset></form>}
    {inputError && <p className="error-note" role="alert">{inputError}</p>}
    <div ref={outcome} className="workflow-studio__outcome" tabIndex={-1} role="group" aria-label="Configuration request outcome"><State state={mutation.state}>{mutation.error && <p className="error-note" role="alert">{mutation.error}</p>}{["submitting", "reconciliation"].includes(mutation.state) && <p role="status">{mutation.state === "reconciliation" ? "Checking the original configuration request..." : "Recording configuration change..."}</p>}{mutation.state === "uncertain" && <><p>The result is not confirmed. Check the original request before making another change.</p><button type="button" className="cta" onClick={() => void run(mutation.command, true)}>Check original configuration request</button></>}{mutation.state === "error" && <button type="button" className="ghost" onClick={() => void reset()}>Refresh and review configuration</button>}{mutation.state === "recovery" && <p>Refreshing current definition before editing.</p>}{mutation.receipt && <><p role="status"><strong>{mutation.receipt.command === "save_draft" ? "Workflow draft saved." : mutation.receipt.command === "publish" ? "Workflow published for new work." : "Workflow paused for new work."}</strong> {mutation.receipt.command === "save_draft" ? "Review it below before publishing." : "Existing work keeps its saved rules."}</p><details className="workflow-studio__details"><summary>Saved change details</summary><p>Receipt: {mutation.receipt.receiptId}. The current status above reflects the latest available read.</p></details></>}</State></div>
    <section className="workflow-studio__publish" aria-label="Publish workflow"><div><p className="workflow-studio__eyebrow">03 · Put it into practice</p><h3>Review before publishing</h3><State state="partial"><p>Publication applies to new work. Existing events keep their rules until a separate, reviewed update. Nothing is sent to a customer.</p></State></div><button type="button" className="ghost" disabled={disabled || dirty || !read.snapshot?.draft || read.snapshot?.lifetimeVersionCount >= 50} onClick={() => void previewPublish()}>Validate and preview publication</button>{dirty && <p className="source-note">Save your draft first so the preview matches the saved changes.</p>}{read.snapshot?.lifetimeVersionCount >= 50 && <p className="warning-note">This workflow has reached its 50-version publication limit. Existing work keeps its saved rules.</p>}</section>
    {preview && <section className="workflow-studio__preview" aria-label="Workflow publication preview"><h3>Ready for your review</h3><p><strong>{preview.config.name}</strong> · {preview.config.taskTemplates.length} tasks for new work.</p><details className="workflow-studio__details" open><summary>Review every publication change</summary><WorkflowConfigurationComparison current={read.snapshot.activeVersion?.config} proposed={preview.config} proposedLabel="Draft configuration" /></details><p>Confirm this exact version by typing: <strong>{preview.confirmationText}</strong></p><label className="field">Publication confirmation<input value={confirmation} disabled={disabled} onChange={event => setConfirmation(event.target.value)} /></label><button type="button" className="cta" disabled={disabled || dirty || confirmation !== preview.confirmationText} onClick={() => void run(command("publish", { previewDigest: preview.previewDigest, confirmationText: confirmation }))}>Publish workflow version</button></section>}
    <details className="workflow-studio__details"><summary>Version history and availability</summary><p>Definition: {statusLabel || "Not available"}. Head revision {read.snapshot?.revision ?? "unavailable"}; {read.snapshot?.lifetimeVersionCount ?? "unavailable"} of 50 lifetime versions.</p>{read.snapshot?.state === "published" && <div><h3>Pause this workflow for new work</h3><p>Existing events keep their saved version. A reviewed publication is required before new work can use this workflow again.</p><label className="field">Retirement reason<input maxLength={240} value={retireReason} disabled={disabled} onChange={event => setRetireReason(event.target.value)} /></label><button type="button" className="ghost" disabled={disabled || dirty || !retireReason.trim()} onClick={() => void run(command("retire", { versionId: read.snapshot.activeVersion.versionId, reason: retireReason }))}>Retire active workflow version</button></div>}</details>
  </section>;
}
