import WorkflowConfigurationComparison from "./WorkflowConfigurationComparison";
import { useCallback, useEffect, useRef, useState } from "react";
import { applyWorkflowDefinitionCommand, CHECKPOINT_CODES, createWorkflowRequestId, WORKFLOW_KINDS, getWorkflowConfiguration, isDefinitiveWorkflowError, normalizeWorkflowConfig, previewWorkflowDefinition, readPendingWorkflowCommand, resetDefinitiveWorkflowCommand, workflowMoneyInputToCents } from "../lib/tenantWorkflowClient";
const LABELS = { event_execution: "Event execution", quote_review: "Quote approval", final_guest_count: "Final guest count", closeout_follow_up: "Closeout follow-up" };
const defaultPolicy = kind => kind === "quote_review" ? { approval: { basis: "absolute_total_delta_cents", thresholdCents: null, allowedRoles: ["admin", "sales"] } } : kind === "event_execution" ? { phaseConstraints: { in_progress: { requiredCheckpoints: [], blockOpenUrgentIssues: false }, completed: { requiredCheckpoints: [], blockOpenUrgentIssues: false } }, checkpointPrerequisites: Object.fromEntries(CHECKPOINT_CODES.map(code => [code, []])) } : { responsibleRoles: ["admin", "sales"], ...(kind === "closeout_follow_up" ? { followUpOffsetDays: 0 } : {}) };
const blankConfig = kind => ({ schemaVersion: 2, workflowKind: kind, name: LABELS[kind], allowedRoles: ["admin", "sales"], actualsReviewThresholdCents: null, comparisonPolicy: null, duePolicy: { offsetMinutes: 0 }, escalationPolicy: { afterMinutes: 60, role: "admin" }, taskTemplates: [], packPolicy: defaultPolicy(kind) });
const checkStyle = { display: "inline-flex", alignItems: "center", gap: "0.5rem" };
const checkInput = { width: "auto", flexShrink: 0 };
function PackPolicyEditor({ draft, update }) {
  const policy = draft.packPolicy;
  if (!policy) return <p>This existing version uses the original event rules. <button type="button" className="ghost" onClick={() => { update("schemaVersion", 2); update("packPolicy", defaultPolicy("event_execution")); }}>Add governed event constraints to this draft</button></p>;
  const roleValue = policy.approval?.allowedRoles || policy.responsibleRoles;
  const setRole = allowed => update("packPolicy", policy.approval ? { approval: { ...policy.approval, allowedRoles: allowed } } : { ...policy, responsibleRoles: allowed });
  const toggle = (list, code, checked) => checked ? [...list, code] : list.filter(item => item !== code);
  const label = value => value.replaceAll("_", " ");
  return <fieldset><legend>Governing pack policy</legend>
    {roleValue && <><label style={checkStyle}><input style={checkInput} type="checkbox" checked={roleValue.includes("sales")} onChange={event => setRole(event.target.checked ? ["admin", "sales"] : ["admin"])} /> Allow sales in this pack's responsible roles</label>{roleValue.some(role => !draft.allowedRoles.includes(role)) && <p role="alert">Restore sales in coordination roles or remove sales from this pack's responsible roles before saving.</p>}</>}
    {policy.approval && <><p>Administrator approval remains required for governed dependency impacts. This threshold adds approval based on absolute total change.</p><label style={checkStyle}><input style={checkInput} type="checkbox" checked={policy.approval.thresholdCents !== null} onChange={event => update("packPolicy", { approval: { ...policy.approval, thresholdCents: event.target.checked ? 0 : null } })} /> Require approval at a declared USD threshold</label>{policy.approval.thresholdCents !== null && <label className="field">Approval threshold (USD)<input inputMode="decimal" required value={draft.approvalInput} onChange={event => update("approvalInput", event.target.value)} /></label>}<p>A declared zero requires approval even when the total change is zero. A blank undeclared threshold adds no threshold rule.</p></>}
    {draft.workflowKind === "closeout_follow_up" && <label className="field">Follow-up after event (tenant calendar days)<input type="number" min={0} max={90} required value={policy.followUpOffsetDays} onChange={event => update("packPolicy", { ...policy, followUpOffsetDays: event.target.value === "" ? "" : Number(event.target.value) })} /></label>}
    {policy.phaseConstraints && <>{["in_progress", "completed"].map(phase => <fieldset key={phase}><legend>Before phase {label(phase)}</legend>{CHECKPOINT_CODES.map(code => <label key={code} style={checkStyle}><input style={checkInput} type="checkbox" checked={policy.phaseConstraints[phase].requiredCheckpoints.includes(code)} onChange={event => update("packPolicy", { ...policy, phaseConstraints: { ...policy.phaseConstraints, [phase]: { ...policy.phaseConstraints[phase], requiredCheckpoints: toggle(policy.phaseConstraints[phase].requiredCheckpoints, code, event.target.checked) } } })} /> Require {label(code)}</label>)}<label style={checkStyle}><input style={checkInput} type="checkbox" checked={policy.phaseConstraints[phase].blockOpenUrgentIssues} onChange={event => update("packPolicy", { ...policy, phaseConstraints: { ...policy.phaseConstraints, [phase]: { ...policy.phaseConstraints[phase], blockOpenUrgentIssues: event.target.checked } } })} /> Block while urgent issues remain open</label></fieldset>)}<details><summary>Checkpoint prerequisites</summary>{CHECKPOINT_CODES.map(code => <fieldset key={code}><legend>Before recording {label(code)}</legend>{CHECKPOINT_CODES.filter(other => other !== code).map(other => <label key={other} style={checkStyle}><input style={checkInput} type="checkbox" checked={policy.checkpointPrerequisites[code].includes(other)} onChange={event => update("packPolicy", { ...policy, checkpointPrerequisites: { ...policy.checkpointPrerequisites, [code]: toggle(policy.checkpointPrerequisites[code], other, event.target.checked) } })} /> Require {label(other)}</label>)}</fieldset>)}<p>Prerequisites must not form a cycle.</p></details></>}
  </fieldset>;
}
const BLOCKED = new Set(["submitting", "uncertain", "reconciliation", "error", "recovery"]);
function State({ state, children }) { const props = { "data-capability-id": "tenant-workflow-configuration" }; switch (state) {
  case "loading": return <div {...props} data-capability-state="loading">{children}</div>; case "empty": return <div {...props} data-capability-state="empty">{children}</div>; case "success": return <div {...props} data-capability-state="success">{children}</div>; case "stale": return <div {...props} data-capability-state="stale">{children}</div>; case "partial": return <div {...props} data-capability-state="partial">{children}</div>; case "error": return <div {...props} data-capability-state="error">{children}</div>; case "recovery": return <div {...props} data-capability-state="recovery">{children}</div>; case "submitting": return <div {...props} data-capability-state="submitting">{children}</div>; case "uncertain": return <div {...props} data-capability-state="uncertain">{children}</div>; case "reconciliation": return <div {...props} data-capability-state="reconciliation">{children}</div>; case "receipt": return <div {...props} data-capability-state="receipt">{children}</div>; default: return <div {...props} data-capability-state="ready">{children}</div>;
} }
const moneyInput = (cents) => cents === null ? "" : (cents / 100).toFixed(2);
const toDraft = (config) => config ? { ...structuredClone(config), thresholdInput: moneyInput(config.actualsReviewThresholdCents), minimumInput: moneyInput(config.comparisonPolicy?.minimumCents ?? null), approvalInput: moneyInput(config.packPolicy?.approval?.thresholdCents ?? null) } : null;
function configOf(draft) { const { thresholdInput, minimumInput, approvalInput, ...config } = draft; if (config.actualsReviewThresholdCents !== null) { config.actualsReviewThresholdCents = workflowMoneyInputToCents(thresholdInput); if (config.actualsReviewThresholdCents === null) throw Error("Enter an explicit review threshold in USD."); } if (config.comparisonPolicy) { config.comparisonPolicy = { ...config.comparisonPolicy, minimumCents: workflowMoneyInputToCents(minimumInput) }; if (config.comparisonPolicy.minimumCents === null) throw Error("Enter an explicit comparison minimum in USD."); } if (config.packPolicy?.approval?.thresholdCents !== null && config.packPolicy?.approval) { config.packPolicy = { approval: { ...config.packPolicy.approval, thresholdCents: workflowMoneyInputToCents(approvalInput) } }; if (config.packPolicy.approval.thresholdCents === null) throw Error("Enter an explicit approval threshold in USD."); } return normalizeWorkflowConfig(config); }
export default function TenantWorkflowConfigurationStudio(props) {
  const [kind, setKind] = useState("event_execution");
  return <Studio key={JSON.stringify([props.organizationId, props.principalId, props.role, props.enabled, props.source, kind])} {...props} workflowKind={kind} onSelectKind={setKind} />;
}
function Studio({ workflowKind: KIND, onSelectKind, organizationId, principalId, role, enabled, source, open = true, onClose, onDismissGuardChange, onInteractionStateChange }) {
  const eligible = enabled === true && source === "firebase" && role === "admin" && Boolean(organizationId && principalId); const scope = { organizationId, principalId, workflowKind: KIND };
  const [pending] = useState(() => eligible ? readPendingWorkflowCommand(scope, "definition") : null);
  const [read, setRead] = useState({ state: "loading", snapshot: null, error: "" }), [draft, setDraft] = useState(null), [base, setBase] = useState(null), [preview, setPreview] = useState(null), [confirmation, setConfirmation] = useState(""), [retireReason, setRetireReason] = useState(""), [inputError, setInputError] = useState("");
  const [mutation, setMutation] = useState(pending ? { state: pending.definitive ? "error" : "uncertain", command: pending.command, error: `The original configuration request for ${pending.command.workflowKind.replaceAll("_", " ")} needs review.` } : { state: "ready" });
  const mounted = useRef(true), sequence = useRef(0), inFlight = useRef(false), outcome = useRef(null), heading = useRef(null), previousMutation = useRef(mutation.state);
  const blocked = BLOCKED.has(mutation.state), dirty = Boolean(draft && JSON.stringify(draft) !== JSON.stringify(base)), busy = blocked || read.state === "loading";
  const load = async () => { if (!eligible) return; const token = ++sequence.current; setRead((prior) => ({ ...prior, state: "loading", error: "" })); setPreview(null); setConfirmation(""); try { const result = await getWorkflowConfiguration({ organizationId, workflowKind: KIND }); if (!mounted.current || token !== sequence.current) return; const s = result.snapshot; setRead({ state: s.availability === "schema_drift" ? "recovery" : ["seed", "unpublished"].includes(s.state) ? "empty" : "success", snapshot: s, error: "" }); const value = toDraft(s.draft || s.activeVersion?.config || (KIND !== "event_execution" ? blankConfig(KIND) : null)); setDraft(value); setBase(value); } catch (error) { if (mounted.current && token === sequence.current) setRead((prior) => ({ ...prior, state: prior.snapshot ? "stale" : "error", error: error.message })); } };
  useEffect(() => { mounted.current = true; heading.current?.focus(); void load(); return () => { mounted.current = false; sequence.current += 1; }; }, []);
  useEffect(() => { if (mutation.state !== previousMutation.current && ["receipt", "uncertain", "error", "recovery"].includes(mutation.state)) outcome.current?.focus(); previousMutation.current = mutation.state; }, [mutation.state]);
  const requestDismiss = useCallback((reason = "close", continuation = null) => { if (blocked) { setInputError("Check the original configuration request before leaving Studio."); return { status: "blocked", reason: "unresolved", trigger: reason }; } if (dirty && !window.confirm("Discard unsaved workflow configuration changes?")) return { status: "guarded", reason: "dirty", trigger: reason }; onInteractionStateChange?.({ dirty: false, busy: false }); continuation?.(); return { status: "dismissed", trigger: reason }; }, [blocked, dirty, onInteractionStateChange]);
  useEffect(() => { onInteractionStateChange?.({ dirty, busy: blocked }); }, [dirty, blocked, onInteractionStateChange]);
  useEffect(() => { onDismissGuardChange?.(open ? { modelId: "workflow-studio-navigation-guard-v1", open: true, dirty, busy: blocked, requestDismiss } : null); return () => onDismissGuardChange?.(null); }, [open, dirty, blocked, requestDismiss, onDismissGuardChange]);
  useEffect(() => { if (!dirty && !blocked) return; const warn = (event) => { event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty, blocked]);
  const run = async (command, reconcile = false) => { if (inFlight.current) return; inFlight.current = true; sequence.current += 1; setMutation({ state: reconcile ? "reconciliation" : "submitting", command }); setInputError(""); try { const result = await applyWorkflowDefinitionCommand({ ...scope, ...command }); if (!mounted.current) return; setMutation({ state: "receipt", receipt: result.receipt }); await load(); } catch (error) { if (mounted.current) setMutation({ state: isDefinitiveWorkflowError(error) ? "error" : "uncertain", command, error: error.message }); } finally { inFlight.current = false; } };
  const command = (kind, fields) => ({ organizationId, workflowKind: KIND, requestId: createWorkflowRequestId(), expectedRevision: read.snapshot.revision, command: kind, ...fields });
  const disabled = blocked || !["empty", "success"].includes(read.state) || read.snapshot?.availability !== "available";
  const update = (field, value) => { setDraft((prior) => ({ ...prior, [field]: value })); setPreview(null); setConfirmation(""); setInputError(""); };
  const updateTask = (index, field, value) => update("taskTemplates", draft.taskTemplates.map((task, i) => i === index ? { ...task, [field]: value } : task));
  const save = (event) => { event.preventDefault(); if (disabled) return; try { void run(command("save_draft", { config: configOf(draft) })); } catch (error) { setInputError(error.message); } };
  const previewPublish = async () => { if (disabled || dirty || !read.snapshot?.draft) return; setRead((prior) => ({ ...prior, state: "loading", error: "" })); try { const result = await previewWorkflowDefinition({ organizationId, principalId, workflowKind: KIND, expectedRevision: read.snapshot.revision }); if (!mounted.current) return; if (result.preview.actor.uid !== principalId) throw Error("The publication preview belongs to a different administrator."); setPreview(result.preview); setRead((prior) => ({ ...prior, state: prior.snapshot.state === "seed" ? "empty" : "success" })); } catch (error) { if (mounted.current) setRead((prior) => ({ ...prior, state: "stale", error: error.message })); } };
  const reset = async () => { if (!resetDefinitiveWorkflowCommand(scope, "definition")) return; setMutation({ state: "recovery" }); await load(); if (mounted.current) setMutation({ state: "ready" }); };
  if (!eligible) return <State state="recovery"><p>Workflow Configuration Studio requires a connected, enabled workspace and administrator access.</p></State>;
  return <section aria-label="Workflow Configuration Studio" data-capability-id="tenant-workflow-configuration" style={{ minWidth: 0, overflowWrap: "anywhere" }} hidden={!open}>
    <h2 ref={heading} tabIndex={-1}>Workflow Configuration Studio</h2><p className="source-note">Publish bounded coordination tasks and review obligations for new workflow instances. Existing instances keep their pinned version until an administrator previews and confirms a migration. Published pack rules govern their supported domain obligations. They do not create new mutation or communication permissions.</p>
    <label className="field">Workflow pack<select aria-label="Workflow pack" value={KIND} disabled={blocked} onChange={event => { const nextKind = event.target.value; requestDismiss("switch-pack", () => onSelectKind(nextKind)); }}>{WORKFLOW_KINDS.map(kind => <option key={kind} value={kind}>{LABELS[kind]}</option>)}</select></label>
    <div className="right-actions"><button type="button" className="ghost" onClick={() => requestDismiss("close", onClose)}>Back to Library</button><button type="button" className="ghost" disabled={busy || dirty} onClick={() => void load()}>Refresh configuration</button></div>
    <State state={read.state}>{read.state === "loading" && <p role="status">Loading workflow configuration...</p>}{read.error && <p role="alert">{read.error}</p>}{read.snapshot?.availability === "schema_drift" && <p>This definition schema is unsupported. Publication is unavailable.</p>}{read.snapshot?.availability === "available" && <p>Definition: <strong>{read.snapshot.state === "seed" ? "Source-controlled seed" : read.snapshot.state === "retired" ? "Retired: new instances blocked" : read.snapshot.state === "unpublished" ? "Unpublished: no policy is active" : "Tenant published"}</strong>. Head revision {read.snapshot.revision}; {read.snapshot.lifetimeVersionCount} of 50 lifetime versions.</p>}</State>
    {read.snapshot?.availability === "available" && <State state="partial"><p className="source-note">Draft edits have no effect on events. Publication applies only to new instances. Manual handoff references do not send messages.</p></State>}
    {draft && <form aria-label="Workflow definition draft" onSubmit={save}><fieldset disabled={disabled}><legend>Draft configuration</legend>
      <label className="field">Definition name<input maxLength={80} required value={draft.name} onChange={(e) => update("name", e.target.value)} /></label>
      <label style={{ display: "inline-flex", alignItems: "center", gap: "0.5rem" }}><input style={{ width: "auto", flexShrink: 0 }} type="checkbox" checked={draft.allowedRoles.includes("sales")} onChange={(e) => update("allowedRoles", e.target.checked ? ["admin", "sales"] : ["admin"])} /> Allow sales to acknowledge assigned coordination tasks</label><p className="source-note">Admin remains enabled. Sales task ownership requires this permission; phase, checkpoint, issue, and actuals changes remain admin-only.</p>
      <PackPolicyEditor draft={draft} update={update} />
      <label className="field">Workflow due offset (minutes)<input type="number" min={0} max={43200} required value={draft.duePolicy.offsetMinutes} onChange={(e) => update("duePolicy", { offsetMinutes: e.target.value === "" ? "" : Number(e.target.value) })} /></label>
      <label className="field">Escalation after due (minutes)<input type="number" min={0} max={43200} required value={draft.escalationPolicy.afterMinutes} onChange={(e) => update("escalationPolicy", { afterMinutes: e.target.value === "" ? "" : Number(e.target.value), role: "admin" })} /></label>
      {KIND === "event_execution" && <><label style={{ display: "inline-flex", alignItems: "center", gap: "0.5rem" }}><input style={{ width: "auto", flexShrink: 0 }} type="checkbox" checked={draft.actualsReviewThresholdCents !== null} onChange={(e) => update("actualsReviewThresholdCents", e.target.checked ? 0 : null)} /> Require review when complete actual costs meet a declared threshold</label>{draft.actualsReviewThresholdCents !== null && <label className="field">Actuals review threshold (USD)<input inputMode="decimal" required value={draft.thresholdInput} onChange={(e) => update("thresholdInput", e.target.value)} /></label>}
      <details><summary>Optional comparison tolerances</summary><label style={{ display: "inline-flex", alignItems: "center", gap: "0.5rem" }}><input style={{ width: "auto", flexShrink: 0 }} type="checkbox" checked={draft.comparisonPolicy !== null} onChange={(e) => update("comparisonPolicy", e.target.checked ? { laborBasisPoints: "", purchasingBasisPoints: "", minimumCents: 0 } : null)} /> Declare comparison policy</label>{draft.comparisonPolicy && <><label className="field">Labor tolerance (basis points)<input type="number" required min={0} max={10000} value={draft.comparisonPolicy.laborBasisPoints} onChange={(e) => update("comparisonPolicy", { ...draft.comparisonPolicy, laborBasisPoints: e.target.value === "" ? "" : Number(e.target.value) })} /></label><label className="field">Purchasing tolerance (basis points)<input type="number" required min={0} max={10000} value={draft.comparisonPolicy.purchasingBasisPoints} onChange={(e) => update("comparisonPolicy", { ...draft.comparisonPolicy, purchasingBasisPoints: e.target.value === "" ? "" : Number(e.target.value) })} /></label><label className="field">Minimum comparison tolerance (USD)<input inputMode="decimal" required value={draft.minimumInput} onChange={(e) => update("minimumInput", e.target.value)} /></label><p className="source-note">100 basis points equals 1%. These declared comparison values do not change recorded costs or pricing.</p></>}</details></>}
      <h3>Named tasks ({draft.taskTemplates.length}/12)</h3>{draft.taskTemplates.map((task, index) => <fieldset key={index}><legend>Task {index + 1}</legend><label className="field">Task key<input aria-label={`Task ${index + 1} key`} required maxLength={48} pattern="[a-z][a-z0-9_]{0,47}" value={task.taskKey} onChange={(e) => updateTask(index, "taskKey", e.target.value)} /></label><label className="field">Task label<input aria-label={`Task ${index + 1} label`} required maxLength={80} value={task.label} onChange={(e) => updateTask(index, "label", e.target.value)} /></label><label className="field">Instruction<textarea aria-label={`Task ${index + 1} instruction`} maxLength={240} rows={2} value={task.instruction} onChange={(e) => updateTask(index, "instruction", e.target.value)} /></label><label className="field">Owner role<select aria-label={`Task ${index + 1} owner`} value={task.ownerRole} onChange={(e) => updateTask(index, "ownerRole", e.target.value)}>{!draft.allowedRoles.includes(task.ownerRole) && <option value={task.ownerRole}>{task.ownerRole} — permission removed</option>}{draft.allowedRoles.map((role) => <option key={role}>{role}</option>)}</select>{!draft.allowedRoles.includes(task.ownerRole) && <span role="alert">Choose an allowed owner for this task or restore sales permission before saving.</span>}</label><label className="field">Due offset (minutes)<input aria-label={`Task ${index + 1} due offset`} type="number" required min={0} max={43200} value={task.dueOffsetMinutes} onChange={(e) => updateTask(index, "dueOffsetMinutes", e.target.value === "" ? "" : Number(e.target.value))} /></label><label className="field">Manual communication reference<select aria-label={`Task ${index + 1} handoff`} value={task.communicationTemplateRef || ""} onChange={(e) => updateTask(index, "communicationTemplateRef", e.target.value || null)}><option value="">No handoff</option><option value="internal_event_brief_v1">Internal event brief</option><option value="post_event_review_v1">Post-event review</option></select></label><button className="ghost" type="button" onClick={() => update("taskTemplates", draft.taskTemplates.filter((_, i) => i !== index))}>Remove task {index + 1}</button></fieldset>)}
      <button type="button" className="ghost" disabled={draft.taskTemplates.length >= 12} onClick={() => update("taskTemplates", [...draft.taskTemplates, { taskKey: `task_${draft.taskTemplates.length + 1}`, label: "", instruction: "", ownerRole: "admin", dueOffsetMinutes: 0, communicationTemplateRef: null }])}>Add task</button><button className="cta" type="submit" disabled={!dirty && Boolean(read.snapshot?.draft || read.snapshot?.activeVersion)}>Save workflow draft</button>
    </fieldset></form>}
    {inputError && <p role="alert">{inputError}</p>}
    <button type="button" className="ghost" disabled={disabled || dirty || !read.snapshot?.draft || read.snapshot?.lifetimeVersionCount >= 50} onClick={() => void previewPublish()}>Validate and preview publication</button>
    {preview && <section aria-label="Workflow publication preview"><h3>Publish {preview.candidateVersionId}</h3><p>Current: {read.snapshot.activeVersion?.config.name || "No active version"}. Draft: {preview.config.name}. Tasks {read.snapshot.activeVersion?.config.taskTemplates.length || 0} → {preview.config.taskTemplates.length}.</p><details><summary>Review every publication change</summary><WorkflowConfigurationComparison current={read.snapshot.activeVersion?.config} proposed={preview.config} proposedLabel="Draft configuration" /></details><p>Type exactly: <strong>{preview.confirmationText}</strong></p><label className="field">Publication confirmation<input value={confirmation} disabled={disabled} onChange={(e) => setConfirmation(e.target.value)} /></label><button type="button" className="cta" disabled={disabled || dirty || confirmation !== preview.confirmationText} onClick={() => void run(command("publish", { previewDigest: preview.previewDigest, confirmationText: confirmation }))}>Publish workflow version</button></section>}
    {read.snapshot?.state === "published" && <details><summary>Retire the active version</summary><p>Retirement blocks new instances. Existing pinned events remain unchanged.</p><label className="field">Retirement reason<input maxLength={240} value={retireReason} disabled={disabled} onChange={(e) => setRetireReason(e.target.value)} /></label><button type="button" className="ghost" disabled={disabled || dirty || !retireReason.trim()} onClick={() => void run(command("retire", { versionId: read.snapshot.activeVersion.versionId, reason: retireReason }))}>Retire active workflow version</button></details>}
    <div ref={outcome} tabIndex={-1} role="group" aria-label="Configuration request outcome"><State state={mutation.state}>{mutation.error && <p role="alert">{mutation.error}</p>}{["submitting", "reconciliation"].includes(mutation.state) && <p role="status">{mutation.state === "reconciliation" ? "Checking the original configuration request..." : "Recording configuration change..."}</p>}{mutation.state === "uncertain" && <><p>No outcome is assumed. Keep the original configuration request unchanged.</p><button type="button" className="cta" onClick={() => void run(mutation.command, true)}>Check original configuration request</button></>}{mutation.state === "error" && <button type="button" className="ghost" onClick={() => void reset()}>Refresh and review configuration</button>}{mutation.state === "recovery" && <p>Refreshing current definition before editing.</p>}{mutation.receipt && <p role="status">Configuration {mutation.receipt.command.replaceAll("_", " ")} recorded. Receipt: {mutation.receipt.receiptId}. Refresh status above shows whether the current configuration is available.</p>}</State></div>
  </section>;
}
