import { useEffect, useRef, useState } from "react";
import { applyWorkflowPackCommand, formatWorkflowSchedule, getWorkflowPackSnapshot, previewWorkflowPackMigration, readPendingWorkflowPackCommand, resetDefinitiveWorkflowPackCommand } from "../lib/workflowPackClient";
import { createWorkflowRequestId, isDefinitiveWorkflowError } from "../lib/tenantWorkflowClient";
import WorkflowConfigurationComparison from "./WorkflowConfigurationComparison";
const LABELS = { quote_review: "Quote approval coordination", final_guest_count: "Final-count coordination", closeout_follow_up: "Closeout follow-up coordination", event_execution: "Event coordination" };
const BLOCKED = new Set(["submitting", "uncertain", "reconciliation", "error", "recovery"]);
function State({ state, children }) { const props = { "data-capability-id": "workflow-pack-coordination" }; switch (state) {
  case "loading": return <div {...props} data-capability-state="loading">{children}</div>; case "empty": return <div {...props} data-capability-state="empty">{children}</div>; case "success": return <div {...props} data-capability-state="success">{children}</div>; case "stale": return <div {...props} data-capability-state="stale">{children}</div>; case "partial": return <div {...props} data-capability-state="partial">{children}</div>; case "error": return <div {...props} data-capability-state="error">{children}</div>; case "recovery": return <div {...props} data-capability-state="recovery">{children}</div>; case "submitting": return <div {...props} data-capability-state="submitting">{children}</div>; case "uncertain": return <div {...props} data-capability-state="uncertain">{children}</div>; case "reconciliation": return <div {...props} data-capability-state="reconciliation">{children}</div>; case "receipt": return <div {...props} data-capability-state="receipt">{children}</div>; default: return <div {...props} data-capability-state="ready">{children}</div>;
} }
export default function WorkflowPackPolicyPanel(props) { return <Panel key={JSON.stringify([props.organizationId, props.quoteId, props.workflowKind, props.principalId, props.role, props.sourceVersionId, props.sourceReceiptId, props.simulationReceiptId, props.enabled])} {...props} />; }
function Panel({ organizationId, quoteId, workflowKind, principalId, role, source = "firebase", enabled, sourceVersionId, sourceReceiptId, simulationReceiptId, domainRevision = "", otherMutationBlocked = false }) {
  const eligible = enabled === true && source === "firebase" && ["admin", "sales"].includes(role) && Boolean(organizationId && quoteId && principalId && sourceVersionId && sourceReceiptId && LABELS[workflowKind]);
  const scope = { organizationId, quoteId, workflowKind, principalId, ...(workflowKind === "quote_review" ? { simulationReceiptId } : {}) };
  const [pending] = useState(() => eligible ? readPendingWorkflowPackCommand(scope) : null);
  const [read, setRead] = useState({ state: "loading", snapshot: null, error: "" }), [mutation, setMutation] = useState(pending ? { state: pending.definitive ? "error" : "uncertain", command: pending.command, error: "The original pack request still needs review." } : { state: "ready" });
  const [selection, setSelection] = useState(null), [note, setNote] = useState(""), [migration, setMigration] = useState(null), [confirmation, setConfirmation] = useState("");
  const mounted = useRef(true), sequence = useRef(0), inFlight = useRef(false), editor = useRef(null), outcome = useRef(null), priorMutation = useRef(mutation.state), priorDomain = useRef(domainRevision), priorBlocked = useRef(otherMutationBlocked), focusEditor = useRef(false);
  const blocked = BLOCKED.has(mutation.state), disabled = blocked || otherMutationBlocked || read.state !== "success", snapshot = read.snapshot;
  const refresh = async () => { if (!eligible) return; const token = ++sequence.current; setRead(prior => ({ ...prior, state: "loading", error: "" })); setSelection(null); setMigration(null); setNote(""); setConfirmation(""); try { const result = await getWorkflowPackSnapshot(scope); if (!mounted.current || token !== sequence.current) return; if (result.snapshot.source.sourceVersionId !== sourceVersionId || result.snapshot.source.sourceReceiptId !== sourceReceiptId) throw Error("The workflow source changed. Reopen this exact record before continuing."); setRead({ state: result.snapshot.availability === "available" ? "success" : "empty", snapshot: result.snapshot, error: "" }); } catch (error) { if (mounted.current && token === sequence.current) setRead(prior => ({ ...prior, state: prior.snapshot ? "stale" : "error", error: error.message })); } };
  useEffect(() => { mounted.current = true; void refresh(); return () => { mounted.current = false; sequence.current += 1; }; }, []);
  useEffect(() => { if (otherMutationBlocked && !priorBlocked.current) { sequence.current += 1; setRead(prior => ({ ...prior, state: prior.snapshot ? "stale" : "loading", error: "Domain evidence is changing. Refresh is required before coordination." })); setSelection(null); setMigration(null); } if (!otherMutationBlocked && (priorBlocked.current || priorDomain.current !== domainRevision) && !blocked) void refresh(); priorBlocked.current = otherMutationBlocked; priorDomain.current = domainRevision; }, [otherMutationBlocked, domainRevision, blocked]);
  useEffect(() => { if (selection && focusEditor.current) { focusEditor.current = false; editor.current?.focus(); } }, [selection]);
  useEffect(() => { if (priorMutation.current !== mutation.state && ["receipt", "uncertain", "error", "recovery"].includes(mutation.state)) outcome.current?.focus(); priorMutation.current = mutation.state; }, [mutation.state]);
  const run = async (command, replay = false) => { if (inFlight.current) return; inFlight.current = true; sequence.current += 1; setMutation({ state: replay ? "reconciliation" : "submitting", command }); try { const result = await applyWorkflowPackCommand({ ...command, principalId }); if (!mounted.current) return; setMutation({ state: "receipt", receipt: result.receipt }); await refresh(); } catch (error) { if (mounted.current) setMutation({ state: error.code === "event-mutation-blocked" ? "ready" : isDefinitiveWorkflowError(error) ? "error" : "uncertain", command, error: error.message }); } finally { inFlight.current = false; } };
  const choose = task => { if (disabled) return; focusEditor.current = true; setSelection({ command: task.state === "acknowledged" ? "task_reopen" : "task_ack", taskKey: task.taskKey, label: task.label }); setNote(""); };
  const preview = async () => { if (disabled || role !== "admin") return; const token = ++sequence.current; setRead(prior => ({ ...prior, state: "loading", error: "" })); setSelection(null); try { const result = await previewWorkflowPackMigration({ ...scope, sourceVersionId, sourceReceiptId, expectedRevision: snapshot.revision }); if (!mounted.current || token !== sequence.current) return; setMigration(result.preview); setRead(prior => ({ ...prior, state: "success" })); if (result.preview.compatible) { focusEditor.current = true; setSelection({ command: "migrate", label: "Migrate pinned workflow" }); setNote(""); setConfirmation(""); } } catch (error) { if (mounted.current && token === sequence.current) setRead(prior => ({ ...prior, state: "stale", error: error.message })); } };
  const submit = event => { event.preventDefault(); if (disabled || !selection || !note.trim() || /[\u0000-\u001f\u007f]/u.test(note)) return; const { principalId: ignored, ...requestScope } = scope; const command = { ...requestScope, sourceVersionId, sourceReceiptId, requestId: createWorkflowRequestId(), expectedRevision: snapshot.revision, command: selection.command, note: note.trim() }; if (selection.taskKey) command.taskKey = selection.taskKey; if (selection.command === "migrate") { if (!migration?.compatible || confirmation !== migration.confirmation) return; Object.assign(command, { previewDigest: migration.previewDigest, confirmation }); } void run(command); };
  const reset = async () => { if (!resetDefinitiveWorkflowPackCommand(scope)) return; setMutation({ state: "recovery" }); await refresh(); if (mounted.current) setMutation({ state: "ready" }); };
  if (!eligible) return <State state="recovery"><p>Workflow coordination requires an enabled connected workspace, staff access, and an exact source.</p></State>;
  return <section aria-label={LABELS[workflowKind]} data-workflow-pack={workflowKind} data-capability-id="workflow-pack-coordination" style={{ minWidth: 0, overflowWrap: "anywhere" }}>
    <h3>{LABELS[workflowKind]}</h3><button type="button" className="ghost" disabled={blocked || otherMutationBlocked || read.state === "loading"} onClick={() => void refresh()}>Refresh pack coordination</button>
    <State state={read.state}>{read.state === "loading" && <p role="status">Loading pinned workflow tasks...</p>}{read.error && <p role="alert">{read.error}</p>}{snapshot?.availability === "not_yet_available" && <p>{snapshot.initializationEligibility.eligible ? `The next eligible domain action will bind ${snapshot.nextDefinition.config.name}, version ${snapshot.nextDefinition.version}.` : `No coordinator is active: ${snapshot.initializationEligibility.reasonCode.replaceAll("_", " ")}.` } No instance is created by this read.</p>}</State>
    {snapshot && <State state="partial"><p>Task acknowledgements record internal coordination. They do not approve a quote, apply a final guest count, complete a closeout, or send a message.</p></State>}
    {snapshot?.availability === "available" && <><p><strong>{snapshot.definitionName}</strong> · published version {snapshot.definitionPin.version}.</p><p>Due {formatWorkflowSchedule(snapshot.due)}. Escalation {formatWorkflowSchedule(snapshot.escalation)} to administrator.</p>
      <ul className="command-center-list" aria-label="Pack coordination tasks">{snapshot.tasks.map(task => <li className="command-center-row" key={task.taskKey}><div><strong>{task.label}</strong><p>{task.instruction}</p><p>{task.ownerRole} · {task.state} · {task.urgency}. Due {formatWorkflowSchedule(task.due)}; escalation {formatWorkflowSchedule(task.escalation)}.</p>{task.note && <p>Recorded note: {task.note}</p>}{task.communicationHandoff && <details><summary>Manual handoff: {task.communicationHandoff.label}</summary><p>{task.communicationHandoff.guidance}</p><p>No message is sent here.</p></details>}</div>{(role === "admin" || task.ownerRole === role && snapshot.configuration.allowedRoles.includes(role)) && <button type="button" className="ghost" disabled={disabled} onClick={() => choose(task)}>{task.state === "acknowledged" ? "Reopen" : "Acknowledge"} {task.label}</button>}</li>)}</ul>{!snapshot.tasks.length && <p>No named tasks are configured.</p>}
      <details><summary>Pinned policy and source evidence</summary><WorkflowConfigurationComparison current={snapshot.configuration} proposed={null} /><p>Source {snapshot.source.sourceVersionId}; receipt {snapshot.source.sourceReceiptId}. Coordinator revision {snapshot.revision}, updated {snapshot.updatedAtISO}.</p><p>Latest receipt {snapshot.lastReceiptId}. Only latest receipt coverage is claimed.</p></details>
      {role === "admin" && <button type="button" className="ghost" disabled={disabled} onClick={() => void preview()}>Preview pack migration</button>}
    </>}
    {migration && <section aria-label="Pack migration preview"><h4>Migration to {migration.targetDefinitionPin.versionId}</h4><p>{migration.compatible ? "Compatible migration. Review the policy and task effects before confirming." : "Migration is incompatible."}</p><ul>{migration.reasons.map(reason => <li key={reason}>{reason.replaceAll("_", " ")}</li>)}</ul><WorkflowConfigurationComparison current={snapshot?.configuration} proposed={migration.targetConfiguration} /></section>}
    {selection && <form aria-label="Review pack coordination change" onSubmit={submit}><h4>{selection.label}</h4><label className="field">Coordination reason<input ref={editor} required maxLength={240} disabled={disabled} value={note} onChange={event => setNote(event.target.value)} /></label>{selection.command === "migrate" && migration && <><p>Type exactly: <strong>{migration.confirmation}</strong></p><label className="field">Migration confirmation<input disabled={disabled} value={confirmation} onChange={event => setConfirmation(event.target.value)} /></label></>}<button type="submit" className="cta" disabled={disabled || !note.trim() || selection.command === "migrate" && confirmation !== migration?.confirmation}>Record pack coordination</button><button type="button" className="ghost" disabled={blocked} onClick={() => { setSelection(null); setMigration(null); }}>Keep current coordination</button></form>}
    <div ref={outcome} tabIndex={-1} role="group" aria-label="Pack request outcome"><State state={mutation.state}>{mutation.error && <p role="alert">{mutation.error}</p>}{["submitting", "reconciliation"].includes(mutation.state) && <p role="status">{mutation.state === "reconciliation" ? "Checking the original pack request..." : "Recording pack coordination..."}</p>}{mutation.state === "uncertain" && <><p>No outcome is assumed. Check the unchanged original request.</p><button type="button" className="cta" onClick={() => void run(mutation.command, true)}>Check original pack request</button></>}{mutation.state === "error" && <button type="button" className="ghost" onClick={() => void reset()}>Refresh and review pack</button>}{mutation.state === "recovery" && <p>Refreshing current pack evidence.</p>}{mutation.receipt && <p role="status">Coordination {mutation.receipt.command.replaceAll("_", " ")} recorded. Receipt {mutation.receipt.receiptId}. The current read above determines the next action.</p>}</State></div>
  </section>;
}
