import { createRequire } from "node:module";
import { expect, test } from "vitest";
const require = createRequire(import.meta.url), attendance = require("../../../functions/quoteAttendance.js");
const refs = { organizationId: "org-a", quoteId: "quote-a", sourceVersionId: "version-a", acceptanceReceiptId: "accept-a" }, source = { ...refs, pricedCount: 120 }, actor = { organizationId: "org-a", uid: "sales-a", role: "sales" }, portal = { organizationId: "org-a", role: "customer", portalKeySha256: "a".repeat(64), portalIssuedAtISO: "2026-09-01T00:00:00.000Z" }, timing = { dueDate: "2026-09-12", policyReferenceId: "debt-guest-count", timezone: "America/Chicago" }, at = "2026-09-05T20:00:00.000Z";
const request = (command = "request_confirmation", extra = {}) => ({ ...refs, requestId: "attendance_request_00001", expectedAttendanceRevision: 0, command, ...extra });
const initial = () => attendance.planCommand({ source, actor, timing, nowISO: at, request: request() });
function respond(first, extra = {}, by = actor) { return attendance.planCommand({ source, actor: by, state: first.nextState, currentReceipt: first.receipt, nowISO: at, request: request(by.role === "customer" ? "submit_response" : "record_response", { requestId: "attendance_response_0001", expectedAttendanceRevision: first.nextState.revision, confirmationRequestId: first.nextState.currentRequest.requestReceiptId, count: 120, ...(by.role === "customer" ? {} : { note: "Recorded from the customer call" }), ...extra }) }); }
test("attendance requests and matching responses stay proposed and preserve immutable evidence", () => { const first = initial(), second = respond(first); expect(source.pricedCount).toBe(120); expect(second.nextState.latestResponse.sourceType).toBe("staff_recorded"); expect(second.nextState.latestResponse.submittedByRole).toBe("sales"); expect(second.nextState).not.toHaveProperty("appliedRevisionId"); expect(attendance.publicReceipt(second.receipt).count).toBe(120); expect(attendance.submissionReference(second.receipt).receiptDigest).toBe(second.receipt.receiptDigest); expect(Object.isFrozen(second.receipt.resultState)).toBe(true); });
test("later responses supersede retained receipts and new requests replace only current projection", () => { const first = initial(), second = respond(first), third = respond(second, { requestId: "attendance_response_0002", count: 130 }); expect(third.nextState.latestResponse.supersedesReceiptId).toBe(second.receipt.receiptId); expect(second.receipt.resultState.latestResponse.count).toBe(120); const next = attendance.planCommand({ source, actor, timing, nowISO: at, state: third.nextState, currentReceipt: third.receipt, request: request("request_confirmation", { requestId: "attendance_request_00002", expectedAttendanceRevision: 3 }) }); expect(next.nextState.latestResponse).toBeNull(); expect(() => respond(next)).not.toThrow(); });
test("portal projection exposes only own issuance response and no private acceptance actors or note", () => { const first = initial(), second = respond(first, { count: 130 }, portal); const projected = attendance.projectSnapshot({ source, state: second.nextState, receipt: second.receipt, accessMode: "portal", portalIdentity: portal }); expect(projected.latestResponse.count).toBe(130); expect(projected).not.toHaveProperty("acceptanceReceiptId"); expect(projected.latestResponse).not.toHaveProperty("actor"); expect(projected.latestResponse).not.toHaveProperty("note"); expect(projected.request).not.toHaveProperty("requestedBy"); expect(JSON.stringify(projected)).not.toContain(portal.portalKeySha256); const foreign = attendance.projectSnapshot({ source, state: second.nextState, receipt: second.receipt, accessMode: "portal", portalIdentity: { ...portal, portalIssuedAtISO: at } }); expect(foreign.latestResponse).toBeNull(); const staff = respond(first); expect(attendance.projectSnapshot({ source, state: staff.nextState, receipt: staff.receipt, accessMode: "portal", portalIdentity: portal }).latestResponse).toBeNull(); });
test("exact historical replay survives current state while cross-principal payload and source collisions fail", () => { const first = initial(), second = respond(first); const replay = attendance.planCommand({ request: first.receipt.request, actor, existingReceipt: first.receipt, source: { ...source, sourceVersionId: "new-source" }, state: second.nextState }); expect(replay.idempotent).toBe(true); expect(replay.nextState).toBeNull(); expect(replay.receipt.resultRevision).toBe(1); for (const change of [{ actor: { ...actor, uid: "other" } }, { request: { ...first.receipt.request, sourceVersionId: "other" } }, { request: { ...first.receipt.request, expectedAttendanceRevision: 1 } }]) expect(() => attendance.planCommand({ request: first.receipt.request, actor, existingReceipt: first.receipt, ...change })).toThrow(); });
test("new attendance commands reject stale source CAS replaced request customer impersonation and bounds", () => { const first = initial(); for (const extra of [{ expectedAttendanceRevision: 0 }, { sourceVersionId: "other" }, { confirmationRequestId: "attendance_command_" + "a".repeat(48) }, { count: 0 }, { count: 401 }, { count: 1.5 }, { note: "" }]) expect(() => respond(first, extra)).toThrow(); expect(() => attendance.planCommand({ source, actor: portal, timing, nowISO: at, request: request() })).toThrow(); expect(() => attendance.planCommand({ source, actor: { ...actor, organizationId: "other" }, timing, nowISO: at, request: request() })).toThrow(); expect(() => attendance.planCommand({ source, actor, timing: null, nowISO: at, request: request() })).toThrow(); expect(() => attendance.normalizeStaffCommand({ ...first.receipt.request, dueDate: "2026-01-01" })).toThrow(); });
test("receipt and state integrity reject contradictory rehashed outcomes orphan journals and missing receipts", () => { const first = initial(), second = respond(first); const bad = structuredClone(second.receipt); bad.resultState.latestResponse.count = 140; const { receiptDigest, ...body } = bad; bad.receiptDigest = attendance.digest(body); expect(() => attendance.verifyReceipt(bad)).toThrow(/outcome/); expect(() => attendance.projectSnapshot({ source, state: second.nextState, receipt: first.receipt })).toThrow(); expect(() => attendance.projectSnapshot({ source, receipt: first.receipt })).toThrow(); expect(() => attendance.planCommand({ source, actor, timing, nowISO: at, state: first.nextState, request: request() })).toThrow(); });
test("empty attendance and due timing remain explicit without inferred requests or delivery", () => { const empty = attendance.projectSnapshot({ source }); expect(empty.availability).toBe("not_yet_available"); expect(empty.request).toBeNull(); expect(empty.latestResponse).toBeNull(); expect(empty.pricedCount).toBe(120); for (const invalid of [{ ...timing, dueDate: "2026-02-31" }, { ...timing, timezone: "made-up" }]) expect(() => attendance.normalizeTiming(invalid)).toThrow(); });

function acceptedFixture(status = "accepted") {
  const issued = "2026-09-01T00:00:00.000Z", accepted = "2026-09-02T00:00:00.000Z", revision = `${refs.sourceVersionId}@${issued}`;
  const proposalSnapshot = { organizationId: refs.organizationId, quoteId: refs.quoteId, revisionId: revision, portalIssuedAtISO: issued, event: { guests: 120, date: "2026-09-12" } };
  const snapshotSha256 = require("node:crypto").createHash("sha256").update(JSON.stringify(proposalSnapshot)).digest("hex");
  const receipt = { receiptId: refs.acceptanceReceiptId, quoteRevisionId: revision, acceptedAtISO: accepted, portalIssuedAtISO: issued, snapshotSha256 };
  const snapshot = { id: refs.quoteId, organizationId: refs.organizationId, customerId: "customer-a", event: { date: "2026-09-12", guests: 120 } };
  return { organizationId: refs.organizationId, quoteId: refs.quoteId, sourceQuote: { ...snapshot, status, activeVersionId: refs.sourceVersionId, acceptanceReceipt: receipt }, sourceVersion: { versionId: refs.sourceVersionId, quoteId: refs.quoteId, organizationId: refs.organizationId, customerId: "customer-a", snapshot }, acceptanceReceiptDocument: { ...receipt, organizationId: refs.organizationId, quoteId: refs.quoteId, proposalSnapshot } };
}
test("attendance accepted source resolver proves private receipt and immutable priced count for accepted and booked records", () => { for (const status of ["accepted", "booked"]) expect(attendance.resolveAcceptedSource(acceptedFixture(status))).toEqual(source); });
test("attendance accepted source rejects forged private snapshots wrong customer stale version and contradictory counts", () => {
  for (const alter of [f => { f.sourceQuote.status = "draft"; }, f => { f.sourceQuote.organizationId = "foreign"; }, f => { f.sourceQuote.activeVersionId = "new"; }, f => { f.sourceVersion.snapshot.customerId = "other"; }, f => { f.acceptanceReceiptDocument.proposalSnapshot.event.guests = 121; }, f => { f.sourceQuote.event = { ...f.sourceQuote.event, guests: 121 }; }, f => { f.sourceVersion.legacySynthetic = true; }, f => { f.acceptanceReceiptDocument = null; }]) { const input = acceptedFixture(); alter(input); expect(() => attendance.resolveAcceptedSource(input)).toThrow(); }
});
