import { createRequire } from "node:module";
import { beforeEach, expect, test, vi } from "vitest";
const require = createRequire(import.meta.url), definitions = require("../../../functions/workflowDefinitions.js"), execution = require("../../../functions/workflowExecution.js");
const transport = vi.hoisted(() => ({ call: vi.fn(), callable: vi.fn() })); vi.mock("firebase/functions", () => ({ httpsCallable: transport.callable })); vi.mock("../firebase", () => ({ cloudFunctions: {}, firebaseReady: true }));
const org = "org-a", scope = { organizationId: org, principalId: "admin-a", workflowKind: "event_execution" }, event = { organizationId: org, quoteId: "quote-a", principalId: "admin-a", sourceVersionId: "version-a", acceptanceReceiptId: "accept-a" }, at = "2026-09-05T10:00:00.000Z", requestId = "workflow_request_00000001";
const seed = definitions.seedPublishedVersion(), config = seed.config, actor = { organizationId: org, uid: "admin-a", role: "admin" };
const env = (field, value, type = "definition", extras = {}) => ({ ok: true, storage: "firebase", organizationId: org, ...(type === "definition" ? { workflowKind: "event_execution" } : { quoteId: "quote-a" }), [field]: value, ...extras });
function eventSnapshot() { const source = { organizationId: org, workflowKind: "event_execution", subjectId: "quote-a", sourceVersionId: "version-a", sourceReceiptId: "accept-a" }, domainRef = { kind: "event_phase", revision: 1, receiptId: `event_ops_command_${"a".repeat(48)}`, policyDigest: "b".repeat(64), receiptDigest: "c".repeat(64) }; const plan = execution.planCommand({ source, request: { command: "initialize", requestId, expectedRevision: 0 }, actor, definition: seed, domainRef, nowISO: at, internal: true }); return { ...execution.projectSnapshot({ source, instance: plan.nextInstance, receipt: plan.receipt, observedAtISO: at }), organizationId: org, quoteId: "quote-a", sourceVersionId: "version-a", acceptanceReceiptId: "accept-a", ledgerId: `event_ops_${"d".repeat(48)}`, phaseRevision: 1, phaseReceiptId: domainRef.receiptId }; }
function receipt(command, type = "definition") { return env("receipt", { receiptId: `${type === "definition" ? "workflow_definition_command_" : "workflow_command_"}${"e".repeat(48)}`, requestId: command.requestId, command: command.command, priorRevision: command.expectedRevision, resultRevision: command.expectedRevision + 1, recordedAtISO: at, ...(type === "definition" ? { versionId: command.command === "save_draft" ? "" : "event_execution_v1" } : { definitionPin: definitions.definitionPin(seed) }) }, type, { idempotent: false }); }
let client, guard;
beforeEach(async () => { vi.resetModules(); vi.clearAllMocks(); transport.callable.mockReturnValue(transport.call); client = await import("../tenantWorkflowClient"); guard = await import("../eventOperatingMutationGuard"); });
test("workflow client verifies real seed and coordinator projections without widening authority", async () => {
  transport.call.mockResolvedValueOnce({ data: env("snapshot", definitions.projectDefinitionSnapshot({ organizationId: org })) }); expect((await client.getWorkflowConfiguration(scope)).snapshot.state).toBe("seed");
  transport.call.mockResolvedValueOnce({ data: env("snapshot", eventSnapshot(), "event") }); const result = await client.getEventWorkflowSnapshot(event); expect(result.snapshot.definitionSource).toBe("source_controlled_seed"); expect(result.snapshot.actualsReview.state).toBe("not_applicable"); expect(Object.isFrozen(result.snapshot.tasks[0])).toBe(true);
  for (const alter of [(s) => s.source.sourceReceiptId = "foreign", (s) => s.actualsReview.state = "required", (s) => s.domainRef.revision = 2, (s) => s.tasks[0].ownerRole = "sales", (s) => s.configuration.taskTemplates[0].communicationTemplateRef = "provider_send"]) { const s = eventSnapshot(); alter(s); transport.call.mockResolvedValueOnce({ data: env("snapshot", s, "event") }); await expect(client.getEventWorkflowSnapshot(event)).rejects.toBeTruthy(); }
});
test("definition field bounds keep optional null distinct from explicit zero and reject ambient code", () => {
  expect(client.workflowMoneyInputToCents("")).toBeNull(); expect(client.workflowMoneyInputToCents("0")).toBe(0); expect(client.workflowMoneyInputToCents("0.01")).toBe(1); expect(client.workflowMoneyInputToCents("1e2")).toBeNull(); expect(client.workflowMoneyInputToCents("1.001")).toBeNull();
  expect(client.normalizeWorkflowConfig({ ...config, actualsReviewThresholdCents: 0 }).actualsReviewThresholdCents).toBe(0); expect(client.normalizeWorkflowConfig(config).actualsReviewThresholdCents).toBeNull();
  for (const invalid of [{ allowedRoles: ["sales"] }, { name: "https://untrusted.test" }, { actualsReviewThresholdCents: -1 }, { taskTemplates: Array(13).fill(config.taskTemplates[0]) }, { taskTemplates: [config.taskTemplates[0], config.taskTemplates[0]] }, { comparisonPolicy: { laborBasisPoints: 0, purchasingBasisPoints: 0 } }]) expect(() => client.normalizeWorkflowConfig({ ...config, ...invalid })).toThrow();
});
test("definition pending intent survives uncertainty and gate denial with promise deduplication", async () => {
  const command = { ...scope, requestId, expectedRevision: 0, command: "save_draft", config }; let reject; transport.call.mockReturnValueOnce(new Promise((_, no) => { reject = no; })); const first = client.applyWorkflowDefinitionCommand(command), duplicate = client.applyWorkflowDefinitionCommand({ ...command }); expect(duplicate).toBe(first); expect(transport.call).toHaveBeenCalledTimes(1);
  reject({ code: "functions/unavailable" }); await expect(first).rejects.toMatchObject({ uncertain: true }); transport.call.mockRejectedValueOnce({ code: "functions/permission-denied" }); await expect(client.applyWorkflowDefinitionCommand(command)).rejects.toMatchObject({ uncertain: true }); expect(client.resetDefinitiveWorkflowCommand(scope, "definition")).toBe(false);
  await expect(client.applyWorkflowDefinitionCommand({ ...command, requestId: "workflow_request_00000002" })).rejects.toMatchObject({ code: "event-mutation-blocked" });
  transport.call.mockResolvedValueOnce({ data: { ...receipt(command), idempotent: true } }); await expect(client.applyWorkflowDefinitionCommand(command)).resolves.toHaveProperty("idempotent", true); expect(client.readPendingWorkflowCommand(scope, "definition")).toBeNull(); expect(transport.call.mock.calls[0][0]).toEqual(transport.call.mock.calls[2][0]); expect(transport.call.mock.calls[0][0]).not.toHaveProperty("principalId");
});
test("workflow uncertainty excludes all three operational siblings while org configuration remains independent", async () => {
  const command = { ...event, requestId, expectedRevision: 1, command: "task_ack", taskKey: "review_event_context", note: "Reviewed context" }; transport.call.mockRejectedValueOnce({ code: "functions/unavailable" }); await expect(client.applyEventWorkflowCommand(command)).rejects.toMatchObject({ uncertain: true });
  for (const owner of ["phase", "work", "actuals"]) expect(() => guard.beginEventOperatingMutation(event, owner, { requestId: "other" })).toThrow("existing event request"); expect(client.readPendingWorkflowCommand({ ...event }).command.requestId).toBe(requestId);
  const definition = { ...scope, requestId, expectedRevision: 0, command: "save_draft", config }; transport.call.mockResolvedValueOnce({ data: receipt(definition) }); await client.applyWorkflowDefinitionCommand(definition); expect(guard.readEventOperatingMutationGuard(event).owner).toBe("workflow");
  transport.call.mockResolvedValueOnce({ data: receipt(command, "event") }); await client.applyEventWorkflowCommand(command); expect(guard.readEventOperatingMutationGuard(event)).toBeNull();
});
test("workflow previews and receipts must bind exact publication version and source", async () => {
  const draft = definitions.planCommand({ request: { organizationId: org, workflowKind: "event_execution", requestId, expectedRevision: 0, command: "save_draft", config }, actor, nowISO: at }); const preview = definitions.previewPublish({ organizationId: org, actor, head: draft.nextHead, currentReceipt: draft.receipt }); transport.call.mockResolvedValueOnce({ data: env("preview", preview) }); expect((await client.previewWorkflowDefinition({ ...scope, expectedRevision: 1 })).preview.confirmationText).toBe(preview.confirmationText);
  const command = { ...scope, requestId, expectedRevision: 1, command: "publish", previewDigest: preview.previewDigest, confirmationText: preview.confirmationText }; const wrong = receipt(command); wrong.receipt.versionId = "event_execution_v2"; transport.call.mockResolvedValueOnce({ data: wrong }); await expect(client.applyWorkflowDefinitionCommand(command)).rejects.toMatchObject({ uncertain: true });
  await expect(client.applyEventWorkflowCommand({ ...event, requestId, expectedRevision: 1, command: "task_ack", taskKey: "review_event_context", note: "Two\nlines" })).rejects.toMatchObject({ code: "invalid-argument" });
});

test("workflow source projections reject contradictory initialization seed and urgency evidence", async () => {
  const base = eventSnapshot(); const absent = { source: base.source, instanceId: base.instanceId, observedAtISO: at, historyCoverage: "latest_receipt_only", availability: "not_yet_available", reasonCode: "phase_ledger_missing", revision: 0, tasks: [], actualsReview: { state: "not_yet_available" }, organizationId: org, quoteId: "quote-a", sourceVersionId: "version-a", acceptanceReceiptId: "accept-a", ledgerId: base.ledgerId, phaseRevision: 0, phaseReceiptId: "", nextDefinition: seed, initializationEligibility: { eligible: true, reasonCode: "seed" } };
  transport.call.mockResolvedValueOnce({ data: env("snapshot", absent, "event") }); expect((await client.getEventWorkflowSnapshot(event)).snapshot.initializationEligibility.eligible).toBe(true);
  for (const altered of [{ ...absent, phaseRevision: 2, phaseReceiptId: base.phaseReceiptId }, { ...absent, initializationEligibility: { eligible: true, reasonCode: "retired" } }, { ...base, configuration: { ...base.configuration, actualsReviewThresholdCents: 0 }, actualsReview: { state: "not_yet_available", actualsRef: null, thresholdCents: 0 } }, { ...base, tasks: [{ ...base.tasks[0], urgency: "acknowledged" }] }]) { transport.call.mockResolvedValueOnce({ data: env("snapshot", altered, "event") }); await expect(client.getEventWorkflowSnapshot(event)).rejects.toBeTruthy(); }
  const draft = definitions.planCommand({ request: { organizationId: org, workflowKind: "event_execution", requestId, expectedRevision: 0, command: "save_draft", config }, actor, nowISO: at }); const preview = definitions.previewPublish({ organizationId: org, actor, head: draft.nextHead, currentReceipt: draft.receipt }); transport.call.mockResolvedValueOnce({ data: env("preview", { ...preview, actor: { ...actor, uid: "foreign-admin" } }) }); await expect(client.previewWorkflowDefinition({ ...scope, expectedRevision: 1 })).rejects.toBeTruthy();
});
test("migration preview requires bounded target configuration before typed review", async () => {
  const s = eventSnapshot(), preview = { instanceId: s.instanceId, source: s.source, expectedRevision: s.revision, currentDefinitionPin: s.definitionPin, targetDefinitionPin: { ...s.definitionPin, version: 1, versionId: "event_execution_v1" }, targetConfiguration: { ...config, name: "New coordination" }, domainRef: s.domainRef, compatible: true, reasons: [], confirmation: "MIGRATE event_execution_v1", previewDigest: "d".repeat(64) };
  transport.call.mockResolvedValueOnce({ data: env("preview", preview, "event") }); expect((await client.previewEventWorkflowMigration({ ...event, expectedRevision: s.revision })).preview.targetConfiguration.name).toBe("New coordination");
  for (const invalid of [undefined, { ...config, allowedRoles: ["sales"] }, { ...config, providerSend: true }]) { const bad = { ...preview, targetConfiguration: invalid }; if (invalid === undefined) delete bad.targetConfiguration; transport.call.mockResolvedValueOnce({ data: env("preview", bad, "event") }); await expect(client.previewEventWorkflowMigration({ ...event, expectedRevision: s.revision })).rejects.toBeTruthy(); }
});

test.each(["quote_review", "final_guest_count", "closeout_follow_up"])("%s definitions publish exact v2 policy without seed fallback", async workflowKind => {
  const scope2 = { ...scope, workflowKind }, packPolicy = workflowKind === "quote_review" ? { approval: { basis: "absolute_total_delta_cents", thresholdCents: 0, allowedRoles: ["admin", "sales"] } } : { responsibleRoles: ["admin", "sales"], ...(workflowKind === "closeout_follow_up" ? { followUpOffsetDays: 2 } : {}) };
  const config2 = { ...structuredClone(config), schemaVersion: 2, workflowKind, packPolicy };
  const envelope = (field, value) => ({ ok: true, storage: "firebase", organizationId: org, workflowKind, [field]: value });
  transport.call.mockResolvedValueOnce({ data: envelope("snapshot", definitions.projectDefinitionSnapshot({ organizationId: org, workflowKind })) }); expect((await client.getWorkflowConfiguration(scope2)).snapshot.state).toBe("unpublished");
  const draft = definitions.planCommand({ request: { organizationId: org, workflowKind, requestId, expectedRevision: 0, command: "save_draft", config: config2 }, actor, nowISO: at });
  const preview = definitions.previewPublish({ organizationId: org, workflowKind, actor, head: draft.nextHead, currentReceipt: draft.receipt });
  transport.call.mockResolvedValueOnce({ data: envelope("preview", preview) }); expect((await client.previewWorkflowDefinition({ ...scope2, expectedRevision: 1 })).preview.config).toEqual(config2);
  const publish = definitions.planCommand({ request: { organizationId: org, workflowKind, requestId: "workflow_publish_0000001", expectedRevision: 1, command: "publish", previewDigest: preview.previewDigest, confirmationText: preview.confirmationText }, actor, head: draft.nextHead, currentReceipt: draft.receipt, nowISO: at });
  transport.call.mockResolvedValueOnce({ data: envelope("snapshot", definitions.projectDefinitionSnapshot({ organizationId: org, workflowKind, head: publish.nextHead, currentReceipt: publish.receipt, activeVersion: publish.publishedVersion })) }); expect((await client.getWorkflowConfiguration(scope2)).snapshot.activeVersion.schemaVersion).toBe(2);
  expect(() => client.normalizeWorkflowConfig({ ...config2, actualsReviewThresholdCents: 0 })).toThrow();
});
test("v2 event constraints reject cycles and disabled responsible roles", () => {
  const config2 = { ...structuredClone(config), schemaVersion: 2, packPolicy: { phaseConstraints: { in_progress: { requiredCheckpoints: ["venue_access"], blockOpenUrgentIssues: true }, completed: { requiredCheckpoints: [], blockOpenUrgentIssues: false } }, checkpointPrerequisites: { venue_access: ["team_briefing"], team_briefing: ["venue_access"], service_handoff: [], pack_down: [] } } };
  expect(() => client.normalizeWorkflowConfig(config2)).toThrow(/cycle/); config2.packPolicy.checkpointPrerequisites.team_briefing = []; expect(client.normalizeWorkflowConfig(config2).schemaVersion).toBe(2);
});

test("uncertain definition intent holds the organization lock across workflow pack selectors and remount", async () => {
  const pending = { ...scope, requestId, expectedRevision: 0, command: "save_draft", config }; transport.call.mockRejectedValueOnce({ code: "functions/unavailable" }); await expect(client.applyWorkflowDefinitionCommand(pending)).rejects.toMatchObject({ uncertain: true });
  const otherScope = { ...scope, workflowKind: "final_guest_count" }; expect(client.readPendingWorkflowCommand(otherScope, "definition").command.workflowKind).toBe("event_execution");
  const otherConfig = { ...structuredClone(config), schemaVersion: 2, workflowKind: "final_guest_count", packPolicy: { responsibleRoles: ["admin", "sales"] } };
  await expect(client.applyWorkflowDefinitionCommand({ ...otherScope, requestId: "workflow_other_request_001", expectedRevision: 0, command: "save_draft", config: otherConfig })).rejects.toMatchObject({ code: "event-mutation-blocked" });
  transport.call.mockResolvedValueOnce({ data: receipt(pending) }); await client.applyWorkflowDefinitionCommand(pending); expect(client.readPendingWorkflowCommand(otherScope, "definition")).toBeNull();
});
