import { createRequire } from "node:module";
import { beforeEach, expect, test, vi } from "vitest";
const require = createRequire(import.meta.url), definitions = require("../../../functions/workflowDefinitions.js"), execution = require("../../../functions/workflowExecution.js");
const transport = vi.hoisted(() => ({ call: vi.fn() })); vi.mock("firebase/functions", () => ({ httpsCallable: () => transport.call })); vi.mock("../firebase", () => ({ cloudFunctions: {}, firebaseReady: true }));
let client;
const at = "2026-09-05T20:00:00.000Z", actor = { organizationId: "org-a", uid: "admin-a", role: "admin" }, scope = { organizationId: "org-a", quoteId: "quote-a", workflowKind: "final_guest_count", principalId: "admin-a" };
function fixture(kind = "final_guest_count", calendar = false) {
  const source = { schemaVersion: 2, organizationId: "org-a", workflowKind: kind, subjectId: "quote-a", sourceVersionId: "version-a", sourceReceiptId: kind === "quote_review" ? "simulation-a" : "accept-a" };
  const packPolicy = kind === "quote_review" ? { approval: { basis: "absolute_total_delta_cents", thresholdCents: 0, allowedRoles: ["admin", "sales"] } } : kind === "event_execution" ? { phaseConstraints: { in_progress: { requiredCheckpoints: [], blockOpenUrgentIssues: false }, completed: { requiredCheckpoints: [], blockOpenUrgentIssues: false } }, checkpointPrerequisites: { venue_access: [], team_briefing: [], service_handoff: [], pack_down: [] } } : { responsibleRoles: ["admin", "sales"], ...(kind === "closeout_follow_up" ? { followUpOffsetDays: 2 } : {}) };
  const config = { ...structuredClone(definitions.seedPublishedVersion().config), schemaVersion: 2, workflowKind: kind, packPolicy };
  const body = { schemaVersion: 2, organizationId: "org-a", definitionId: kind, workflowKind: kind, versionId: `${kind}_v1`, version: 1, config, publishedBy: actor, publishedAtISO: at, seed: false }, definition = { ...body, definitionDigest: execution.digest(body) };
  const domainRef = { schemaVersion: 2, adapterId: `${kind}_v2`, sourceDigest: execution.digest(source), observationKind: "immutable_receipt", evidenceId: "domain-a", evidenceDigest: "a".repeat(64), domainPolicyDigest: "b".repeat(64), stateCode: "recorded", recordedAtISO: at };
  const result = execution.planCommand({ source, request: { command: "initialize", requestId: "workflow_pack_initial_001", expectedRevision: 0 }, actor, definition, domainRef, scheduleAnchor: calendar ? { kind: "tenant_calendar_date", date: "2026-09-07", timeZone: "America/Chicago" } : { kind: "instant", atISO: at }, nowISO: at, internal: true });
  return { snapshot: execution.projectSnapshot({ source, instance: result.nextInstance, receipt: result.receipt, observedAtISO: at }), definition };
}
const env = (field, value, kind = scope.workflowKind) => ({ ok: true, storage: "firebase", organizationId: "org-a", quoteId: "quote-a", workflowKind: kind, [field]: value });
const command = { ...scope, sourceVersionId: "version-a", sourceReceiptId: "accept-a", requestId: "workflow_pack_request_0001", expectedRevision: 1, command: "task_ack", taskKey: "review_event_context", note: "Reviewed exact source" };
const receipt = input => ({ ...env("receipt", { receiptId: `workflow_command_${"a".repeat(48)}`, requestId: input.requestId, command: input.command, priorRevision: input.expectedRevision, resultRevision: input.expectedRevision + 1, recordedAtISO: at, definitionPin: fixture(input.workflowKind).snapshot.definitionPin }, input.workflowKind), idempotent: true });
beforeEach(async () => { vi.resetModules(); vi.resetAllMocks(); client = await import("../workflowPackClient"); });
test("workflow pack client accepts all four exact projections and preserves tenant calendar schedules", async () => {
  for (const kind of ["final_guest_count", "quote_review", "closeout_follow_up", "event_execution"]) { const f = fixture(kind, kind === "closeout_follow_up"); transport.call.mockResolvedValueOnce({ data: env("snapshot", f.snapshot, kind) }); const result = await client.getWorkflowPackSnapshot({ ...scope, workflowKind: kind, ...(kind === "quote_review" ? { simulationReceiptId: "simulation-a" } : {}) }); expect(result.snapshot.definitionPin.workflowKind).toBe(kind); if (kind === "closeout_follow_up") expect(client.formatWorkflowSchedule(result.snapshot.due)).toContain("2026-09-07 at 00:00 (America/Chicago, tenant calendar)"); }
});
test("workflow pack projection fails closed on wrong source contradictory urgency and undeclared policy", async () => {
  for (const alter of [s => { s.source.subjectId = "other"; }, s => { s.tasks[0].urgency = "acknowledged"; }, s => { s.due.atISO = "2026-09-06T00:00:00.000Z"; }, s => { s.configuration.packPolicy.responsibleRoles = ["sales"]; }, s => { s.actualsReview.state = "acknowledged"; }, s => { s.domainRef.revision = 2; }, s => { s.domainRef.sourceDigest = "c".repeat(64); }]) { const s = fixture().snapshot; alter(s); transport.call.mockResolvedValueOnce({ data: env("snapshot", s) }); await expect(client.getWorkflowPackSnapshot(scope)).rejects.toBeTruthy(); }
});
test("pack uncertainty retains source and principal across remount and deduplicates exact replay", async () => {
  let reject; transport.call.mockReturnValueOnce(new Promise((_, no) => { reject = no; })); const first = client.applyWorkflowPackCommand(command), duplicate = client.applyWorkflowPackCommand(command); expect(first).toBe(duplicate); expect(transport.call).toHaveBeenCalledTimes(1); reject({ code: "functions/unavailable" }); await expect(first).rejects.toMatchObject({ uncertain: true });
  expect(client.readPendingWorkflowPackCommand({ ...scope }).command).toEqual(expect.objectContaining({ sourceReceiptId: "accept-a" }));
  await expect(client.applyWorkflowPackCommand({ ...command, sourceVersionId: "new-source" })).rejects.toMatchObject({ code: "event-mutation-blocked" }); transport.call.mockRejectedValueOnce({ code: "functions/permission-denied" }); await expect(client.applyWorkflowPackCommand(command)).rejects.toMatchObject({ uncertain: true }); expect(client.resetDefinitiveWorkflowPackCommand(scope)).toBe(false);
  transport.call.mockResolvedValueOnce({ data: receipt(command) }); await expect(client.applyWorkflowPackCommand(command)).resolves.toHaveProperty("idempotent", true); expect(client.readPendingWorkflowPackCommand(scope)).toBeNull(); expect(transport.call.mock.calls[0][0]).toEqual(transport.call.mock.calls[2][0]); expect(transport.call.mock.calls[0][0]).not.toHaveProperty("principalId");
});
test("event pack uncertainty excludes original phase work and actuals owners", async () => {
  const event = { ...command, workflowKind: "event_execution" }; transport.call.mockRejectedValueOnce({ code: "functions/unavailable" }); await expect(client.applyWorkflowPackCommand(event)).rejects.toMatchObject({ uncertain: true }); const guard = await import("../eventOperatingMutationGuard"); for (const owner of ["phase", "work", "actuals"]) expect(() => guard.beginEventOperatingMutation(event, owner, { requestId: "other" })).toThrow();
});
test("pack migration previews bind readable target configuration and exact current source", async () => {
  const f = fixture(), p = { instanceId: f.snapshot.instanceId, source: f.snapshot.source, expectedRevision: 1, currentDefinitionPin: f.snapshot.definitionPin, targetDefinitionPin: { ...f.snapshot.definitionPin, version: 2, versionId: "final_guest_count_v2" }, targetConfiguration: f.snapshot.configuration, domainRef: f.snapshot.domainRef, compatible: true, reasons: [], confirmation: "MIGRATE final_guest_count_v2", previewDigest: "c".repeat(64) };
  transport.call.mockResolvedValueOnce({ data: env("preview", p) }); expect((await client.previewWorkflowPackMigration({ ...scope, sourceVersionId: "version-a", sourceReceiptId: "accept-a", expectedRevision: 1 })).preview.targetConfiguration).toEqual(f.snapshot.configuration);
  transport.call.mockResolvedValueOnce({ data: env("preview", { ...p, source: { ...p.source, sourceReceiptId: "changed" } }) }); await expect(client.previewWorkflowPackMigration({ ...scope, sourceVersionId: "version-a", sourceReceiptId: "accept-a", expectedRevision: 1 })).rejects.toBeTruthy();
});
